import type { AiTool } from "./types";

/**
 * Curated list of widely-used AI tools.
 *
 * Every entry is here because the tool is well established and its purpose is
 * a stable fact. Deliberately absent: prices, star ratings and "best" rankings
 * — see the note in types.ts for why.
 */
export const AI_TOOLS: AiTool[] = [
  /* ------------------------------- chat ------------------------------- */
  {
    id: "chatgpt",
    name: "ChatGPT",
    maker: "OpenAI",
    summary: "General-purpose assistant for questions, drafting, analysis and image generation.",
    url: "https://chatgpt.com",
    category: "chat",
    alsoIn: ["writing", "research", "image"],
    bestFor: "The broadest all-rounder, and the one most people have already used.",
    freeTier: "yes",
  },
  {
    id: "claude",
    name: "Claude",
    maker: "Anthropic",
    summary: "Assistant with a large context window, strong at long documents and careful writing.",
    url: "https://claude.ai",
    category: "chat",
    alsoIn: ["writing", "code", "research"],
    bestFor: "Working through long documents and prose that needs to read like a person wrote it.",
    freeTier: "yes",
  },
  {
    id: "gemini",
    name: "Gemini",
    maker: "Google",
    summary: "Google's assistant, tied into Search, Docs, Gmail and the rest of Workspace.",
    url: "https://gemini.google.com",
    category: "chat",
    alsoIn: ["research", "productivity"],
    bestFor: "Anyone already working inside Google Workspace.",
    freeTier: "yes",
  },
  {
    id: "copilot",
    name: "Microsoft Copilot",
    maker: "Microsoft",
    summary: "Assistant built into Windows, Edge and the Microsoft 365 applications.",
    url: "https://copilot.microsoft.com",
    category: "chat",
    alsoIn: ["productivity", "writing"],
    bestFor: "Working inside Word, Excel and Outlook without leaving them.",
    freeTier: "yes",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    maker: "DeepSeek",
    summary: "Assistant built on openly published models, with strong reasoning and coding.",
    url: "https://chat.deepseek.com",
    category: "chat",
    alsoIn: ["code"],
    bestFor: "Reasoning and code when you want an openly published model behind it.",
    freeTier: "yes",
  },
  {
    id: "mistral-chat",
    name: "Le Chat",
    maker: "Mistral AI",
    summary: "European assistant built on Mistral's own open-weight model family.",
    url: "https://chat.mistral.ai",
    category: "chat",
    bestFor: "A European provider, and open weights you can self-host.",
    freeTier: "yes",
  },

  /* ------------------------------- image ------------------------------- */
  {
    id: "midjourney",
    name: "Midjourney",
    maker: "Midjourney",
    summary: "Image generator known for a distinctive, highly aesthetic house style.",
    url: "https://www.midjourney.com",
    category: "image",
    bestFor: "Striking, stylised images when look matters more than literal accuracy.",
    freeTier: "no",
  },
  {
    id: "dalle",
    name: "DALL·E",
    maker: "OpenAI",
    summary: "Image generation inside ChatGPT, strong at following a detailed description.",
    url: "https://openai.com/dall-e-3",
    category: "image",
    bestFor: "Getting exactly what you described, including readable text in the image.",
    freeTier: "limited",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    maker: "Stability AI",
    summary: "Open-weight image models you can run on your own hardware.",
    url: "https://stability.ai",
    category: "image",
    bestFor: "Running locally, fine-tuning, and full control over the pipeline.",
    freeTier: "yes",
  },
  {
    id: "firefly",
    name: "Adobe Firefly",
    maker: "Adobe",
    summary: "Image generation trained on licensed content and built into Creative Cloud.",
    url: "https://firefly.adobe.com",
    category: "image",
    alsoIn: ["design"],
    bestFor: "Commercial work where training-data provenance matters.",
    freeTier: "limited",
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    maker: "Leonardo.Ai",
    summary: "Image generation aimed at game art and concept work, with fine-tuned models.",
    url: "https://leonardo.ai",
    category: "image",
    bestFor: "Game assets and concept art with a consistent style across a set.",
    freeTier: "limited",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    maker: "Ideogram",
    summary: "Image generator that handles text inside images unusually well.",
    url: "https://ideogram.ai",
    category: "image",
    alsoIn: ["design"],
    bestFor: "Posters, logos and anything where the lettering has to be right.",
    freeTier: "limited",
  },

  /* ------------------------------- video ------------------------------- */
  {
    id: "runway",
    name: "Runway",
    maker: "Runway",
    summary: "Video generation and editing, with inpainting and motion tools alongside.",
    url: "https://runwayml.com",
    category: "video",
    bestFor: "Editing as well as generating — a full video workflow rather than clips alone.",
    freeTier: "limited",
  },
  {
    id: "sora",
    name: "Sora",
    maker: "OpenAI",
    summary: "Text-to-video model producing longer, notably coherent clips.",
    url: "https://openai.com/sora",
    category: "video",
    bestFor: "Longer shots that hold together, from a written description.",
    freeTier: "no",
  },
  {
    id: "veo",
    name: "Veo",
    maker: "Google DeepMind",
    summary: "Google's video generation model, available through its own apps.",
    url: "https://deepmind.google/technologies/veo/",
    category: "video",
    bestFor: "High-resolution clips with generated audio.",
    freeTier: "limited",
  },
  {
    id: "kling",
    name: "Kling AI",
    maker: "Kuaishou",
    summary: "Text and image to video, strong on realistic human motion.",
    url: "https://klingai.com",
    category: "video",
    bestFor: "Animating a still image into believable movement.",
    freeTier: "limited",
  },
  {
    id: "heygen",
    name: "HeyGen",
    maker: "HeyGen",
    summary: "Presenter-style videos from a script, with avatars and translation.",
    url: "https://www.heygen.com",
    category: "video",
    alsoIn: ["voice"],
    bestFor: "Talking-head training and marketing video without filming anything.",
    freeTier: "limited",
  },
  {
    id: "descript",
    name: "Descript",
    maker: "Descript",
    summary: "Edit video and podcasts by editing the transcript text.",
    url: "https://www.descript.com",
    category: "video",
    alsoIn: ["audio", "productivity"],
    bestFor: "Podcast and interview editing — cutting a sentence by deleting the words.",
    freeTier: "limited",
  },

  /* ------------------------------- audio ------------------------------- */
  {
    id: "suno",
    name: "Suno",
    maker: "Suno",
    summary: "Generates complete songs, including vocals, from a text description.",
    url: "https://suno.com",
    category: "audio",
    bestFor: "A full song with vocals from a one-line idea.",
    freeTier: "limited",
  },
  {
    id: "udio",
    name: "Udio",
    maker: "Udio",
    summary: "Music generation with fine control over sections and style.",
    url: "https://www.udio.com",
    category: "audio",
    bestFor: "Iterating on a track section by section.",
    freeTier: "limited",
  },
  {
    id: "adobe-podcast",
    name: "Adobe Podcast",
    maker: "Adobe",
    summary: "Cleans up spoken-word recordings, removing noise and room echo.",
    url: "https://podcast.adobe.com",
    category: "audio",
    bestFor: "Rescuing a recording made in a bad room.",
    freeTier: "limited",
  },

  /* ------------------------------- voice ------------------------------- */
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    maker: "ElevenLabs",
    summary: "Text to speech and voice cloning across many languages.",
    url: "https://elevenlabs.io",
    category: "voice",
    bestFor: "The most natural synthetic speech, and dubbing into other languages.",
    freeTier: "limited",
  },
  {
    id: "whisper",
    name: "Whisper",
    maker: "OpenAI",
    summary: "Open-source speech recognition that runs on your own machine.",
    url: "https://github.com/openai/whisper",
    category: "voice",
    alsoIn: ["research"],
    bestFor: "Transcription you want to run locally, with nothing uploaded.",
    freeTier: "yes",
  },
  {
    id: "otter",
    name: "Otter.ai",
    maker: "Otter.ai",
    summary: "Live meeting transcription with summaries and action items.",
    url: "https://otter.ai",
    category: "voice",
    alsoIn: ["productivity"],
    bestFor: "Meeting notes taken while the meeting is still happening.",
    freeTier: "limited",
  },

  /* -------------------------------- code -------------------------------- */
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    maker: "GitHub",
    summary: "Code completion and chat inside your editor.",
    url: "https://github.com/features/copilot",
    category: "code",
    bestFor: "In-editor completion across the widest range of editors.",
    freeTier: "limited",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    maker: "Anthropic",
    summary: "Terminal agent that reads a repository and makes multi-file changes.",
    url: "https://claude.com/claude-code",
    category: "code",
    bestFor: "Larger changes across many files, rather than line-by-line completion.",
    freeTier: "no",
  },
  {
    id: "cursor",
    name: "Cursor",
    maker: "Anysphere",
    summary: "An editor built around AI, with codebase-wide context.",
    url: "https://cursor.com",
    category: "code",
    bestFor: "Working in an editor designed around the model rather than bolted onto one.",
    freeTier: "limited",
  },
  {
    id: "v0",
    name: "v0",
    maker: "Vercel",
    summary: "Generates React and Tailwind interfaces from a description.",
    url: "https://v0.app",
    category: "code",
    alsoIn: ["design"],
    bestFor: "Getting a first working front-end quickly.",
    freeTier: "limited",
  },

  /* ------------------------------- writing ------------------------------ */
  {
    id: "grammarly",
    name: "Grammarly",
    maker: "Grammarly",
    summary: "Grammar, spelling, clarity and tone checking as you write.",
    url: "https://www.grammarly.com",
    category: "writing",
    bestFor: "Catching your own mistakes across every app you write in.",
    freeTier: "yes",
  },
  {
    id: "languagetool",
    name: "LanguageTool",
    maker: "LanguageTool",
    summary: "Open-source grammar and style checker in more than twenty languages.",
    url: "https://languagetool.org",
    category: "writing",
    bestFor: "Checking languages other than English, and self-hosting if you want to.",
    freeTier: "yes",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    maker: "Notion",
    summary: "Drafting, summarising and Q&A over your own Notion workspace.",
    url: "https://www.notion.so/product/ai",
    category: "writing",
    alsoIn: ["productivity"],
    bestFor: "Asking questions of documents you have already written.",
    freeTier: "trial",
  },

  /* ------------------------------ research ------------------------------ */
  {
    id: "perplexity",
    name: "Perplexity",
    maker: "Perplexity AI",
    summary: "Answers questions with inline citations to its sources.",
    url: "https://www.perplexity.ai",
    category: "research",
    bestFor: "Questions where you need to check where the answer came from.",
    freeTier: "yes",
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    maker: "Google",
    summary: "Grounds its answers only in documents you upload, and can narrate them.",
    url: "https://notebooklm.google.com",
    category: "research",
    bestFor: "Studying a fixed set of sources without answers drifting outside them.",
    freeTier: "yes",
  },
  {
    id: "elicit",
    name: "Elicit",
    maker: "Elicit",
    summary: "Finds and summarises academic papers for a literature review.",
    url: "https://elicit.com",
    category: "research",
    bestFor: "Systematic reviews and finding the papers that actually exist.",
    freeTier: "limited",
  },
  {
    id: "consensus",
    name: "Consensus",
    maker: "Consensus",
    summary: "Search that answers questions using findings from peer-reviewed papers.",
    url: "https://consensus.app",
    category: "research",
    bestFor: "Checking whether the evidence actually supports a claim.",
    freeTier: "limited",
  },

  /* ---------------------------- productivity ---------------------------- */
  {
    id: "zapier",
    name: "Zapier",
    maker: "Zapier",
    summary: "Connects apps into automated workflows, with AI steps available.",
    url: "https://zapier.com",
    category: "productivity",
    bestFor: "Wiring together apps that have no native integration.",
    freeTier: "limited",
  },
  {
    id: "n8n",
    name: "n8n",
    maker: "n8n",
    summary: "Source-available workflow automation you can host yourself.",
    url: "https://n8n.io",
    category: "productivity",
    bestFor: "Automation you want to run on your own infrastructure.",
    freeTier: "yes",
  },
  {
    id: "fathom",
    name: "Fathom",
    maker: "Fathom",
    summary: "Records and summarises meetings with timestamped highlights.",
    url: "https://fathom.video",
    category: "productivity",
    alsoIn: ["voice"],
    bestFor: "Meeting summaries you can hand straight to someone who missed it.",
    freeTier: "yes",
  },

  /* ------------------------------- design ------------------------------- */
  {
    id: "canva",
    name: "Canva",
    maker: "Canva",
    summary: "Design tool with generation, background removal and layout suggestions built in.",
    url: "https://www.canva.com",
    category: "design",
    bestFor: "Getting a decent-looking design without being a designer.",
    freeTier: "yes",
  },
  {
    id: "figma-ai",
    name: "Figma AI",
    maker: "Figma",
    summary: "Generation, search and rewriting inside Figma.",
    url: "https://www.figma.com/ai/",
    category: "design",
    bestFor: "Teams already designing in Figma.",
    freeTier: "limited",
  },
  {
    id: "gamma",
    name: "Gamma",
    maker: "Gamma",
    summary: "Generates presentations, documents and simple sites from a prompt.",
    url: "https://gamma.app",
    category: "design",
    alsoIn: ["productivity"],
    bestFor: "A presentation draft in a couple of minutes.",
    freeTier: "limited",
  },
  {
    id: "remove-bg",
    name: "remove.bg",
    maker: "Kaleido",
    summary: "Removes the background from an image automatically.",
    url: "https://www.remove.bg",
    category: "design",
    alsoIn: ["image"],
    bestFor: "Cutting out a subject in one step.",
    freeTier: "limited",
  },

  /* --------------------------------- 3d --------------------------------- */
  {
    id: "luma",
    name: "Luma AI",
    maker: "Luma Labs",
    summary: "Turns photos and video into 3D captures, and generates video.",
    url: "https://lumalabs.ai",
    category: "3d",
    alsoIn: ["video"],
    bestFor: "Capturing a real object as a 3D scene using a phone.",
    freeTier: "limited",
  },
  {
    id: "meshy",
    name: "Meshy",
    maker: "Meshy",
    summary: "Generates textured 3D models from text or a single image.",
    url: "https://www.meshy.ai",
    category: "3d",
    bestFor: "Quick 3D assets for prototyping a game or scene.",
    freeTier: "limited",
  },
  {
    id: "spline",
    name: "Spline",
    maker: "Spline",
    summary: "Browser-based 3D design with generation features.",
    url: "https://spline.design",
    category: "3d",
    alsoIn: ["design"],
    bestFor: "3D for websites, without learning a full 3D package.",
    freeTier: "yes",
  },
];

export const AI_TOOL_COUNT = AI_TOOLS.length;

/** Includes tools whose secondary categories match, so nothing is hidden. */
export function toolsInCategory(category: string): AiTool[] {
  return AI_TOOLS.filter(
    (tool) => tool.category === category || tool.alsoIn?.includes(category as never),
  );
}

/** When this list was last reviewed by hand. Shown on the page. */
export const DIRECTORY_REVIEWED = "September 2026";
