/**
 * Word lists behind the writing tools.
 *
 * Everything here is a judgement about English usage, kept separate from the
 * matching engine so the lists can be read, argued with and corrected without
 * touching any logic. Nothing in this file is generated or guessed at runtime.
 */

/** Misspellings that spell-check catches but people still ship. */
export const MISSPELLINGS: Record<string, string> = {
  accomodate: "accommodate", acheive: "achieve",
  aquire: "acquire", accross: "across", agressive: "aggressive", apparant: "apparent",
  arguement: "argument", assasination: "assassination", basicly: "basically",
  begining: "beginning", beleive: "believe", belive: "believe", buisness: "business",
  calender: "calendar", cemetary: "cemetery", changable: "changeable",
  collegue: "colleague", comming: "coming", commited: "committed",
  commitee: "committee", completly: "completely", concious: "conscious",
  curiousity: "curiosity", definately: "definitely", definitly: "definitely",
  dilemna: "dilemma", dissapear: "disappear", dissapoint: "disappoint",
  ecstacy: "ecstasy", embarass: "embarrass", enviroment: "environment",
  existance: "existence", experiance: "experience", explaination: "explanation",
  familar: "familiar", finaly: "finally", flourescent: "fluorescent",
  foriegn: "foreign", freind: "friend", futher: "further", gaurd: "guard",
  glamourous: "glamorous", goverment: "government", grammer: "grammar",
  gratefull: "grateful", guidence: "guidance", harrass: "harass",
  hieght: "height", hierachy: "hierarchy", humourous: "humorous",
  idiosyncracy: "idiosyncrasy", immediatly: "immediately", independant: "independent",
  indispensible: "indispensable", inteligent: "intelligent", interupt: "interrupt",
  irresistable: "irresistible", knowlege: "knowledge", labratory: "laboratory",
  liason: "liaison", libary: "library", lightening: "lightning", maintainance: "maintenance",
  maintenence: "maintenance", managment: "management", medcine: "medicine",
  millenium: "millennium", miniscule: "minuscule", mischevious: "mischievous", neccessary: "necessary", necesary: "necessary",
  negociate: "negotiate", noticable: "noticeable", occassion: "occasion",
  occured: "occurred", occurance: "occurrence", occurence: "occurrence",
  ocasion: "occasion", oppurtunity: "opportunity", parliment: "parliament",
  particuarly: "particularly", pasttime: "pastime", perseverence: "perseverance",
  personel: "personnel", persistant: "persistent", posession: "possession",
  possesion: "possession", potatoe: "potato",
  preceed: "precede", prefered: "preferred", presance: "presence",
  privelege: "privilege", priviledge: "privilege", probaly: "probably",
  proffesional: "professional", pronounciation: "pronunciation",
  publically: "publicly", questionaire: "questionnaire", readible: "readable",
  realy: "really", recieve: "receive", reccomend: "recommend", recomend: "recommend",
  refered: "referred", refrence: "reference", relevent: "relevant",
  religous: "religious", repitition: "repetition", restarant: "restaurant",
  rythm: "rhythm", secratary: "secretary", seperate: "separate", sieze: "seize",
  similiar: "similar", sincerly: "sincerely", speach: "speech", sucessful: "successful",
  succesful: "successful", supercede: "supersede", suprise: "surprise",
  surpirse: "surprise", tendancy: "tendency", threshhold: "threshold",
  tommorow: "tomorrow", tommorrow: "tomorrow", tounge: "tongue",
  truely: "truly", unfortunatly: "unfortunately", untill: "until",
  usualy: "usually", vaccuum: "vacuum", vegtable: "vegetable", vehical: "vehicle",
  visable: "visible", wierd: "weird", wellcome: "welcome", wich: "which",
  writting: "writing", writen: "written", yeild: "yield", alot: "a lot",
  cant: "can't", dont: "don't", wont: "won't", isnt: "isn't", didnt: "didn't",
  doesnt: "doesn't", couldnt: "couldn't", wouldnt: "wouldn't", shouldnt: "shouldn't",
  havent: "haven't", hasnt: "hasn't", wasnt: "wasn't", werent: "weren't",
  thats: "that's", whats: "what's", youre: "you're",
  theyre: "they're", ive: "I've", im: "I'm",
  arent: "aren't", aint: "isn't", everytime: "every time",
  incase: "in case", inspite: "in spite", infront: "in front", eachother: "each other",
  aswell: "as well", atleast: "at least", nowdays: "nowadays", ofcourse: "of course",
  offcourse: "of course", inorder: "in order",
  thankyou: "thank you", upto: "up to", wanna: "want to", gonna: "going to",
  gotta: "got to", kinda: "kind of", sorta: "sort of", cuz: "because",
  becuase: "because", becasue: "because", becuse: "because", teh: "the",
  taht: "that", adn: "and", hte: "the", tihs: "this", jsut: "just",
  woudl: "would", coudl: "could", shoudl: "should", thier: "their",
  freinds: "friends", peaple: "people", peopel: "people", stuidents: "students",
  studnets: "students", reserach: "research", resaerch: "research",
  anaylsis: "analysis", analize: "analyse", conclussion: "conclusion",
  concusion: "conclusion", intoduction: "introduction", introdution: "introduction",
  paragarph: "paragraph", assignement: "assignment", assigment: "assignment",
  univeristy: "university", univercity: "university",
  proffesor: "professor", profesor: "professor", curriculam: "curriculum",
  sylabus: "syllabus", biblography: "bibliography", bibiliography: "bibliography",
  citaton: "citation", refrences: "references", apendix: "appendix",
  hypothisis: "hypothesis", hypothsis: "hypothesis", experiement: "experiment",
  methodolgy: "methodology", statisics: "statistics", sattistics: "statistics",
  varaible: "variable", varibles: "variables", signifigant: "significant",
  signficant: "significant", correlaton: "correlation", theroy: "theory",
  arguemnt: "argument", evidance: "evidence", critera: "criteria",
  phenomenom: "phenomenon", critisism: "criticism", critisize: "criticise", paticipants: "participants",
  partcipants: "participants", questionairre: "questionnaire",
};

/** Word pairs people reach for interchangeably that mean different things. */
export interface Confusion {
  wrong: RegExp;
  right: string;
  note: string;
}

export const CONFUSIONS: Confusion[] = [
  { wrong: /\byour\s+(?=(?:a|the|going|not|welcome|right|wrong|so|very|really|just|too)\b)/gi, right: "you're", note: "\"You're\" is short for \"you are\". \"Your\" shows possession." },
  { wrong: /\bits\s+(?=(?:a|an|the|not|been|going|clear|important|true|possible|likely)\b)/gi, right: "it's", note: "\"It's\" is short for \"it is\". \"Its\" shows possession and has no apostrophe." },
  { wrong: /\bit's\s+(?=(?:own|value|purpose|size|name|role|effect|impact|use|form|structure)\b)/gi, right: "its", note: "Possessive \"its\" takes no apostrophe." },
  { wrong: /\bthere\s+(?=(?:own|house|car|work|results|findings|argument|paper|essay|opinion)\b)/gi, right: "their", note: "\"Their\" shows possession; \"there\" refers to a place." },
  { wrong: /\bthere\s+(?=(?:is|are|was|were)\s+(?:no|a|an|some|many|several|two|three)\b)/gi, right: "there", note: "" },
  { wrong: /\bwould\s+of\b/gi, right: "would have", note: "\"Would of\" is a mishearing of \"would have\"." },
  { wrong: /\bcould\s+of\b/gi, right: "could have", note: "\"Could of\" is a mishearing of \"could have\"." },
  { wrong: /\bshould\s+of\b/gi, right: "should have", note: "\"Should of\" is a mishearing of \"should have\"." },
  { wrong: /\bmust\s+of\b/gi, right: "must have", note: "\"Must of\" is a mishearing of \"must have\"." },
  { wrong: /\bthen\s+(?=(?:the|a|an|any|most|more|less|fewer|other|I|we|he|she|they)\b(?=[^.!?]*\b(?:better|worse|more|less|greater|smaller|higher|lower)\b))/gi, right: "than", note: "Comparisons use \"than\"; \"then\" is about time." },
  { wrong: /\bloose\s+(?=(?:the|a|an|his|her|their|my|your|our|it|weight|money|control|track|sight)\b)/gi, right: "lose", note: "\"Lose\" is the verb; \"loose\" means not tight." },
  { wrong: /\baffect\s+(?=(?:of|on)\b)/gi, right: "effect", note: "\"Effect\" is usually the noun; \"affect\" is usually the verb." },
  { wrong: /\bthe\s+affect\b/gi, right: "the effect", note: "\"Effect\" is the noun." },
  { wrong: /\beffects?\s+(?=(?:the|a|an|his|her|their|our|my|your)\s+\w+\s+(?:by|in|through)\b)/gi, right: "affects", note: "\"Affect\" is the verb meaning to influence." },
  { wrong: /\bcomplimentary\s+(?=(?:to|with|angle|colour|color|pair)\b)/gi, right: "complementary", note: "\"Complementary\" means completing; \"complimentary\" means praising or free." },
  { wrong: /\bprincipal\s+(?=(?:of\s+(?:the\s+)?(?:matter|thing|law|physics|design|operation))\b)/gi, right: "principle", note: "A \"principle\" is a rule; a \"principal\" is a person or the main one." },
  { wrong: /\bwhose\s+(?=(?:going|coming|been|not|the\s+one)\b)/gi, right: "who's", note: "\"Who's\" is short for \"who is\"; \"whose\" shows possession." },
  { wrong: /\bto\s+(?=(?:much|many|late|early|small|large|big|far|often|little|expensive)\b)/gi, right: "too", note: "\"Too\" means excessively." },
  { wrong: /\balot\b/gi, right: "a lot", note: "\"A lot\" is two words." },
  { wrong: /\beveryday\s+(?=(?:I|we|they|he|she|you|the\s+students)\b)/gi, right: "every day", note: "\"Every day\" is the time phrase; \"everyday\" is the adjective." },
  { wrong: /\bcite\s+(?=(?:of\s+the|was\s+chosen|selection)\b)/gi, right: "site", note: "A \"site\" is a place; to \"cite\" is to quote a source." },
  { wrong: /\bfarther\s+(?=(?:evidence|research|analysis|discussion|reading|work|study)\b)/gi, right: "further", note: "\"Further\" is figurative; \"farther\" is physical distance." },
  { wrong: /\bamount\s+of\s+(?=(?:people|students|participants|items|words|studies|papers|results|things|reasons)\b)/gi, right: "number of", note: "Use \"number of\" for things you can count." },
  { wrong: /\bless\s+(?=(?:people|students|participants|items|words|studies|papers|results|things|reasons)\b)/gi, right: "fewer", note: "Use \"fewer\" for things you can count." },
];

/** Long phrases with short equivalents. The core of the concision check. */
export const WORDY: Record<string, string> = {
  "a large number of": "many", "a majority of": "most", "a number of": "several",
  "a small number of": "a few", "a sufficient amount of": "enough",
  "along the lines of": "like", "an adequate number of": "enough",
  "as a consequence of": "because of", "as a matter of fact": "in fact",
  "as a means of": "to", "as a result of": "because of", "as of yet": "yet",
  "as to whether": "whether", "at all times": "always", "at the conclusion of": "after",
  "at the present time": "now", "at this point in time": "now", "at this time": "now",
  "based on the fact that": "because", "by means of": "by", "by virtue of": "by",
  "came to the conclusion": "concluded", "carry out an investigation": "investigate",
  "concerning the matter of": "about", "conduct an analysis of": "analyse",
  "despite the fact that": "although", "due to the fact that": "because",
  "during the course of": "during", "during the time that": "while",
  "each and every": "every", "except for the fact that": "except that",
  "for the purpose of": "to", "for the reason that": "because",
  "give consideration to": "consider", "give rise to": "cause",
  "has the ability to": "can", "has the capacity to": "can",
  "have an effect on": "affect", "in a timely manner": "promptly",
  "in accordance with": "under", "in addition to the fact that": "besides",
  "in all likelihood": "probably", "in an effort to": "to",
  "in close proximity to": "near", "in connection with": "about",
  "in excess of": "more than", "in light of the fact that": "because",
  "in order to": "to", "in relation to": "about", "in spite of the fact that": "although",
  "in the absence of": "without", "in the event that": "if",
  "in the near future": "soon", "in the vicinity of": "near",
  "in this day and age": "today", "is able to": "can", "is capable of": "can",
  "is going to": "will", "is indicative of": "indicates", "is representative of": "represents",
  "it is apparent that": "apparently", "it is clear that": "clearly",
  "it is important to note that": "note that", "it is often the case that": "often",
  "it should be noted that": "note that", "make a decision": "decide",
  "make an assumption": "assume", "make reference to": "refer to",
  "notwithstanding the fact that": "although", "on a daily basis": "daily",
  "on a regular basis": "regularly", "on account of the fact that": "because",
  "on the grounds that": "because", "on the occasion of": "when",
  "because of the fact that": "because", "in view of the fact that": "because",
  "regardless of the fact that": "although", "aware of the fact that": "aware that",
  "given the fact that": "given that", "the fact of the matter is that": "",
  "owing to the fact that": "because", "prior to": "before",
  "provided that": "if", "put an end to": "end", "reach a conclusion": "conclude",
  "subsequent to": "after", "take into consideration": "consider",
  "the fact that": "that", "the majority of": "most", "the manner in which": "how",
  "the question as to whether": "whether", "the reason why is that": "because",
  "there is a need for": "we need", "this is a subject that": "this subject",
  "through the use of": "using", "until such time as": "until",
  "with reference to": "about", "with regard to": "about",
  "with the exception of": "except", "with the result that": "so",
  "would seem to suggest": "suggests", "a total of": "", "absolutely essential": "essential",
  "advance planning": "planning", "basic fundamentals": "fundamentals",
  "close proximity": "proximity", "completely eliminate": "eliminate",
  "end result": "result", "final outcome": "outcome", "free gift": "gift",
  "future plans": "plans", "join together": "join", "new innovation": "innovation",
  "past history": "history", "personal opinion": "opinion", "period of time": "period",
  "repeat again": "repeat", "return back": "return", "revert back": "revert",
  "same identical": "identical", "still remains": "remains", "sum total": "total",
  "true fact": "fact", "unexpected surprise": "surprise", "very unique": "unique",
  "completely unique": "unique", "actual fact": "fact", "added bonus": "bonus",
  "brief summary": "summary", "collaborate together": "collaborate",
  "consensus of opinion": "consensus", "each individual": "each",
  "first and foremost": "first", "general consensus": "consensus",
  "important essentials": "essentials", "integral part": "part",
  "mutual cooperation": "cooperation", "necessary requirement": "requirement",
  "null and void": "void", "over exaggerate": "exaggerate",
  "plan ahead": "plan", "postpone until later": "postpone",
  "protest against": "protest", "rate of speed": "speed",
  "reason why": "reason", "regular routine": "routine",
  "serious crisis": "crisis", "small in size": "small",
  "surrounded on all sides": "surrounded", "terrible tragedy": "tragedy",
  "usual custom": "custom", "various different": "various",
  "whether or not": "whether", "close down": "close", "cancel out": "cancel",
};

/** Words that add length without adding meaning. */
export const FILLER = [
  "actually", "basically", "certainly", "definitely", "essentially",
  "extremely", "fairly", "highly", "honestly", "just", "literally",
  "obviously", "particularly", "perhaps", "practically", "pretty",
  "quite", "rather", "really", "relatively", "simply", "slightly",
  "somewhat", "totally", "truly", "utterly", "very", "virtually",
];

/** Hedges that make academic claims sound unsure. */
export const HEDGES = [
  "arguably", "apparently", "conceivably", "could be", "i believe",
  "i feel", "i guess", "i suppose", "i think", "in my opinion",
  "kind of", "maybe", "might be", "more or less", "perhaps",
  "possibly", "presumably", "seems to", "sort of", "to some extent",
];

/** Verbs weak enough that the sentence usually improves without them. */
export const NOMINALISATIONS: Record<string, string> = {
  "make a decision": "decide", "provide assistance": "help",
  "give an explanation": "explain", "perform an analysis": "analyse",
  "conduct a review": "review", "take action": "act",
  "reach an agreement": "agree", "have a discussion": "discuss",
  "offer a suggestion": "suggest", "carry out a comparison": "compare",
  "undertake an examination": "examine", "provide a description": "describe",
  "make an improvement": "improve", "achieve a reduction": "reduce",
  "conduct an investigation": "investigate", "make a contribution": "contribute",
  "made a decision": "decided", "provided assistance": "helped",
  "gave an explanation": "explained", "performed an analysis": "analysed",
  "conducted a review": "reviewed", "took action": "acted",
  "reached an agreement": "agreed", "had a discussion": "discussed",
  "offered a suggestion": "suggested", "carried out a comparison": "compared",
  "undertook an examination": "examined", "provided a description": "described",
  "made an improvement": "improved", "achieved a reduction": "reduced",
  "conducted an investigation": "investigated", "made a contribution": "contributed",
};

/** Clichés and stock phrases that weaken academic and professional prose. */
export const CLICHES = [
  "at the end of the day", "think outside the box", "low hanging fruit",
  "move the needle", "circle back", "touch base", "game changer",
  "paradigm shift", "in today's society", "since the dawn of time",
  "throughout history", "in this modern world", "needless to say",
  "it goes without saying", "last but not least", "few and far between",
  "the tip of the iceberg", "a double edged sword", "when all is said and done",
  "each and every one", "time and time again", "first and foremost",
];

/** Tone signals. Each word contributes to one axis. */
export const TONE_LEXICON: Record<string, string[]> = {
  formal: [
    "furthermore", "moreover", "consequently", "nevertheless", "notwithstanding",
    "therefore", "thus", "hence", "whereas", "accordingly", "subsequently",
    "demonstrate", "indicate", "establish", "constitute", "comprise",
    "utilise", "utilize", "endeavour", "commence", "ascertain", "regarding",
    "pursuant", "aforementioned", "herein", "thereby", "wherein",
  ],
  casual: [
    "stuff", "things", "kind of", "sort of", "a lot", "loads", "tons",
    "okay", "ok", "yeah", "cool", "awesome", "huge", "super", "totally",
    "guys", "gonna", "wanna", "kinda", "basically", "anyway", "so",
    "pretty much", "bunch", "whatever", "figure out", "get", "got",
  ],
  confident: [
    "will", "must", "clearly", "certainly", "undoubtedly", "definitely",
    "prove", "proves", "demonstrates", "establishes", "confirms",
    "always", "never", "guarantee", "ensure", "know", "know that",
    "the evidence shows", "without question",
  ],
  tentative: [
    "may", "might", "could", "perhaps", "possibly", "seems", "appears",
    "suggests", "somewhat", "arguably", "presumably", "tends to",
    "i think", "i believe", "in my opinion", "it is possible",
    "relatively", "fairly", "to some extent",
  ],
  positive: [
    "excellent", "effective", "successful", "valuable", "beneficial",
    "improve", "improved", "strong", "clear", "useful", "significant",
    "promising", "robust", "compelling", "advantage", "opportunity",
    "support", "supports", "achieve", "achieved", "progress",
  ],
  negative: [
    "fail", "failed", "failure", "poor", "weak", "flawed", "problem",
    "problematic", "difficult", "limitation", "concern", "risk",
    "insufficient", "inadequate", "decline", "damage", "unfortunately",
    "however", "although", "despite", "lack", "lacking", "error",
  ],
  urgent: [
    "immediately", "urgent", "now", "critical", "asap", "deadline",
    "must", "required", "essential", "imperative", "priority", "quickly",
  ],
  friendly: [
    "please", "thanks", "thank you", "welcome", "happy", "glad",
    "appreciate", "hope", "looking forward", "great", "wonderful",
    "sure", "of course", "no problem", "feel free",
  ],
};

/**
 * Synonyms used by the rewording suggestions.
 *
 * Deliberately conservative: only near-equivalents that hold in most contexts.
 * A larger list would produce the thesaurus-salad that makes spun text obvious.
 */
export const SYNONYMS: Record<string, string[]> = {
  important: ["significant", "key", "central", "crucial"],
  significant: ["notable", "considerable", "substantial", "important"],
  show: ["demonstrate", "reveal", "indicate", "illustrate"],
  shows: ["demonstrates", "reveals", "indicates", "illustrates"],
  showed: ["demonstrated", "revealed", "indicated", "illustrated"],
  use: ["employ", "apply", "draw on", "make use of"],
  uses: ["employs", "applies", "draws on"],
  used: ["employed", "applied", "drew on"],
  make: ["create", "produce", "generate", "form"],
  makes: ["creates", "produces", "generates"],
  get: ["obtain", "acquire", "receive", "gain"],
  gets: ["obtains", "acquires", "receives"],
  big: ["large", "substantial", "considerable", "extensive"],
  small: ["minor", "limited", "modest", "slight"],
  good: ["effective", "strong", "sound", "favourable"],
  bad: ["poor", "weak", "unfavourable", "flawed"],
  help: ["assist", "support", "aid", "enable"],
  helps: ["assists", "supports", "aids", "enables"],
  think: ["consider", "believe", "hold", "argue"],
  says: ["states", "argues", "notes", "observes"],
  said: ["stated", "argued", "noted", "observed"],
  many: ["numerous", "several", "a range of", "various"],
  a_lot: ["considerably", "substantially", "greatly"],
  because: ["since", "as", "given that"],
  but: ["yet", "however", "although"],
  also: ["in addition", "moreover", "furthermore"],
  so: ["therefore", "consequently", "as a result"],
  however: ["nevertheless", "yet", "even so"],
  problem: ["issue", "difficulty", "challenge", "concern"],
  problems: ["issues", "difficulties", "challenges", "concerns"],
  idea: ["concept", "notion", "proposal", "argument"],
  ideas: ["concepts", "notions", "proposals", "arguments"],
  result: ["outcome", "finding", "consequence"],
  results: ["outcomes", "findings", "consequences"],
  study: ["research", "investigation", "analysis"],
  studies: ["research", "investigations", "analyses"],
  method: ["approach", "technique", "procedure"],
  methods: ["approaches", "techniques", "procedures"],
  increase: ["rise", "growth", "expansion"],
  decrease: ["fall", "decline", "reduction"],
  change: ["shift", "alteration", "transformation"],
  people: ["individuals", "participants", "the public"],
  very: ["highly", "notably", "particularly"],
  really: ["genuinely", "truly", "particularly"],
  found: ["discovered", "identified", "observed"],
  need: ["require", "call for", "demand"],
  needs: ["requires", "calls for", "demands"],
  start: ["begin", "commence", "initiate"],
  end: ["conclude", "finish", "complete"],
  look: ["examine", "consider", "inspect"],
  give: ["provide", "offer", "supply"],
  gives: ["provides", "offers", "supplies"],
  part: ["element", "component", "aspect"],
  parts: ["elements", "components", "aspects"],
  way: ["method", "approach", "means"],
  ways: ["methods", "approaches", "means"],
  hard: ["difficult", "demanding", "challenging"],
  easy: ["straightforward", "simple", "accessible"],
  new: ["recent", "novel", "emerging"],
  old: ["earlier", "previous", "long-standing"],
};

/** Transitions, grouped by the relationship they signal. */
export const TRANSITIONS: Record<string, string[]> = {
  addition: ["furthermore", "moreover", "in addition", "additionally", "also", "similarly", "likewise"],
  contrast: ["however", "nevertheless", "conversely", "on the other hand", "by contrast", "yet", "although"],
  cause: ["therefore", "consequently", "as a result", "thus", "hence", "accordingly", "because of this"],
  example: ["for example", "for instance", "to illustrate", "specifically", "namely", "in particular"],
  sequence: ["first", "next", "then", "subsequently", "finally", "meanwhile"],
  conclusion: ["in conclusion", "overall", "in summary", "to conclude", "taken together", "on balance"],
};
