import type { Tool } from "../types";

/**
 * Calculators. Every one shows the formula next to the answer.
 */
export const CALCULATORS_TOOLS: Tool[] = [
  {
    id: "age",
    name: "Age Calculator",
    short: "Work out an exact age in years, months and days.",
    long:
      "Enter a date of birth and DO101 works out the exact age today, or on any date you choose, down to the day. It also shows total months, weeks, days and the countdown to the next birthday.",
    category: "calculator",
    route: "/calculators/age",
    keywords: ["age calculator", "calculate age", "how old am i", "date of birth calculator", "age in days", "birthday countdown"],
    aliases: ["how old am i", "calculate my age", "birthday calculator"],
    icon: "🎂",
    accent: "fire",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "numbers",
    related: ["percentage", "discount", "bmi", "timestamp-converter"],
    seoTitle: "Free Age Calculator — Exact Age in Years, Months & Days | DO101",
    seoDescription:
      "Calculate your exact age in years, months and days from a date of birth, plus total weeks, days, hours and a countdown to your next birthday.",
    steps: ["Enter the date of birth.", "Leave the second date as today, or pick another date.", "Read the exact age and the extra breakdowns."],
    features: ["Exact years, months and days", "Totals in months, weeks, days, hours and minutes", "Days until the next birthday", "Day of the week you were born", "Calculated locally"],
    faqs: [
      { q: "How is an exact age calculated?", a: "DO101 counts whole years first, then whole months from that anniversary, then the remaining days — the same way you would say it out loud. Calendar month lengths and leap years are handled properly." },
      { q: "Why does the day count differ from other calculators?", a: "Some tools approximate a month as 30 days. DO101 uses the real calendar, so February and 31-day months are counted correctly." },
    ],
    featured: true,
  },
  {
    id: "percentage",
    name: "Percentage Calculator",
    short: "Every percentage question in one place, with the formula shown.",
    long:
      "Work out what X% of a number is, what percentage one number is of another, and percentage increase or decrease between two values. Each answer shows the formula so you can check the working.",
    category: "calculator",
    route: "/calculators/percentage",
    keywords: ["percentage calculator", "calculate percentage", "percent of a number", "percentage increase", "percentage decrease", "percent change"],
    aliases: ["percent calculator", "work out percentage", "what percent is"],
    icon: "％",
    accent: "fire",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "numbers",
    related: ["discount", "trading-analyzer", "age", "bmi", "word-counter"],
    seoTitle: "Free Percentage Calculator — Percent Of, Change & Increase | DO101",
    seoDescription:
      "Calculate a percentage of a number, what percent one number is of another, and percentage increase or decrease. Formula shown with every answer.",
    steps: ["Pick the kind of percentage question you have.", "Type the two numbers.", "Read the answer and the formula underneath."],
    features: ["What is X% of Y", "X is what percent of Y", "Percentage increase and decrease", "Formula displayed with every result", "Instant, no page reload"],
    faqs: [
      { q: "How do I calculate a percentage increase?", a: "Subtract the old value from the new value, divide by the old value, then multiply by 100. Going from 80 to 100 is (100 − 80) / 80 × 100 = 25% increase." },
      { q: "Why is a 50% rise followed by a 50% fall not back to the start?", a: "Because each percentage applies to a different base. 100 rises to 150, then 50% of 150 is 75 — so you land at 75, not 100." },
    ],
    featured: true,
  },
  {
    id: "discount",
    name: "Discount Calculator",
    short: "See the sale price, the amount saved and the real discount.",
    long:
      "Enter an original price and a discount to see what you pay and what you save. It also works backwards: enter the original and sale prices to find the true percentage off, and stack a second discount or add tax.",
    category: "calculator",
    route: "/calculators/discount",
    keywords: ["discount calculator", "sale price calculator", "percent off calculator", "how much do i save", "double discount"],
    aliases: ["percent off", "sale price", "calculate discount"],
    icon: "🏷️",
    accent: "fire",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "numbers",
    related: ["percentage", "trading-analyzer", "age", "bmi", "qr-generator"],
    seoTitle: "Free Discount Calculator — Sale Price & Percent Off | DO101",
    seoDescription:
      "Calculate a sale price, the amount saved, stacked discounts and the true percentage off. Free discount calculator with the maths shown.",
    steps: ["Enter the original price.", "Enter the discount percentage, or the price you were quoted.", "Read the final price and your saving."],
    features: ["Discount to final price", "Final price back to true percentage off", "Stack a second discount correctly", "Optional tax on top", "Formula shown"],
    faqs: [
      { q: "How do stacked discounts work?", a: "They multiply rather than add. 20% off then a further 10% off is 0.8 × 0.9 = 0.72, so 28% off in total — not 30%." },
      { q: "Is tax applied before or after the discount?", a: "In most places the discount comes first and tax is charged on the reduced price. DO101 follows that order and shows both lines." },
    ],
  },
  {
    id: "bmi",
    name: "BMI Calculator",
    short: "Body Mass Index in metric or imperial, with the range explained.",
    long:
      "Calculate Body Mass Index from height and weight in either metric or imperial units, and see where the result sits on the standard adult scale. BMI is a rough screening number, not a diagnosis — the page explains what it does and does not tell you.",
    category: "calculator",
    route: "/calculators/bmi",
    keywords: ["bmi calculator", "body mass index", "calculate bmi", "bmi chart", "healthy weight calculator"],
    aliases: ["body mass index", "am i overweight calculator"],
    icon: "⚖️",
    accent: "fire",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "numbers",
    related: ["percentage", "age", "discount", "timestamp-converter"],
    seoTitle: "Free BMI Calculator — Metric & Imperial Body Mass Index | DO101",
    seoDescription:
      "Calculate Body Mass Index in metric or imperial units and see the standard adult categories explained, with a clear note on BMI's limits.",
    steps: ["Choose metric or imperial.", "Enter your height and weight.", "Read your BMI and the category scale beneath it."],
    features: ["Metric (cm / kg) and imperial (ft, in / lb)", "Category scale with your position marked", "Healthy weight range for your height", "Plain-English limitations section", "Calculated on your device"],
    faqs: [
      { q: "Is BMI accurate?", a: "BMI is a population-level screening tool. It does not distinguish muscle from fat, and it can misclassify athletes, older adults, pregnant people and children. Treat it as one rough signal, not a verdict on your health." },
      { q: "What is the formula?", a: "Metric: weight in kilograms divided by height in metres squared. Imperial: 703 × weight in pounds ÷ height in inches squared." },
      { q: "Does DO101 store my measurements?", a: "No. The calculation runs in the page and nothing is transmitted or saved." },
    ],
  },
  {
    id: "compound-interest",
    name: "Compound Interest Calculator",
    short: "See what savings grow to with monthly deposits, year by year.",
    long:
      "Enter a starting amount, a monthly deposit, an interest rate and a number of years, and see exactly what it grows to — with the split between what you paid in and what the interest added, year by year. It handles every compounding frequency properly, even when your deposits are monthly and the account compounds quarterly, shows the effective annual rate and how long money takes to double, and can restate the final figure in today's money after inflation. Everything is calculated in your browser.",
    category: "calculator",
    route: "/calculators/compound-interest",
    keywords: [
      "compound interest calculator", "savings calculator", "investment growth calculator",
      "monthly contribution calculator", "compound interest formula", "future value calculator",
      "sip calculator", "interest on savings", "effective annual rate", "rule of 72",
    ],
    aliases: ["compound interest", "savings growth", "how much will my savings grow", "investment calculator"],
    icon: "📈",
    accent: "grass",
    browserOnly: true,
    aiInvocable: false,
    input: "numbers",
    output: "numbers",
    related: ["loan-emi", "percentage", "currency-converter", "discount"],
    seoTitle: "Compound Interest Calculator with Monthly Deposits | DO101",
    seoDescription:
      "Free compound interest calculator with monthly deposits. See your balance year by year, interest earned, effective rate, doubling time and value after inflation.",
    steps: [
      "Enter the amount you are starting with and what you will add each month.",
      "Set the annual interest rate, how often it compounds, and the number of years.",
      "Read the final balance and how much of it is interest rather than your own money.",
      "Add an inflation rate to see what that balance is worth in today's money.",
      "Scroll the year-by-year table to see when interest starts outpacing your deposits.",
    ],
    features: [
      "Monthly deposits with yearly, half-yearly, quarterly, monthly or daily compounding",
      "Correct when deposits and compounding happen at different frequencies",
      "Deposit at the start or end of each month",
      "Paid-in versus interest, as a chart and a year-by-year table",
      "Effective annual rate and the time it takes money to double",
      "Final balance in today's money, after inflation",
      "Calculated in your browser — nothing is sent anywhere",
    ],
    faqs: [
      { q: "What is compound interest?", a: "Interest earned on interest. Each period, the interest is added to the balance, so the next period's interest is calculated on a slightly bigger number. Over long periods that snowballs: at 7% a year, money roughly doubles every ten years." },
      { q: "What formula does it use?", a: "With no deposits, the standard A = P(1 + r/n)^(nt), where r is the annual rate and n the number of compounding periods a year. With monthly deposits it works month by month using the monthly rate equivalent to your compounding frequency, which gives the same answer as the formula when there are no deposits and handles deposits correctly when there are." },
      { q: "Does it matter how often interest compounds?", a: "A little. More frequent compounding earns slightly more at the same stated rate, which is why the calculator shows the effective annual rate. 6% compounded monthly is about 6.17% a year; compounded daily it is about 6.18%. The rate itself and the time you leave it matter far more." },
      { q: "Should I deposit at the start or end of the month?", a: "Depositing at the start means each deposit earns interest for that month too, so the result is slightly higher. Most salary-funded savings land near the start of the month; the difference is small either way." },
      { q: "What does 'in today's money' mean?", a: "Inflation makes the same amount buy less over time. If you enter an inflation rate, the calculator divides the final balance by how much prices will have risen, so you can see what it would buy in today's terms." },
      { q: "Is this a prediction of my investment returns?", a: "No. It assumes a fixed rate for the whole period and ignores tax and fees. That is exact for a fixed deposit, but anything invested in markets goes up and down, and past returns do not predict future ones." },
    ],
  },
  {
    id: "loan-emi",
    name: "Loan & EMI Calculator",
    short: "Monthly payment, total interest and a full repayment schedule for any loan.",
    long:
      "Work out the monthly payment (EMI) on a home, car or personal loan from the amount, interest rate and term, and see how much of what you repay is interest. A full amortisation schedule shows each payment split into interest and principal, by year or by month. Add an extra monthly payment to see how many months sooner the loan is cleared and how much interest that saves. Uses the same annuity formula lenders use, and runs entirely in your browser.",
    category: "calculator",
    route: "/calculators/loan-emi",
    keywords: [
      "emi calculator", "loan calculator", "home loan emi calculator", "car loan calculator",
      "personal loan emi", "mortgage calculator", "amortization schedule", "loan repayment calculator",
      "interest calculator", "prepayment calculator",
    ],
    aliases: ["emi", "loan emi", "mortgage payment", "monthly loan payment", "amortisation"],
    icon: "🏦",
    accent: "sky",
    browserOnly: true,
    aiInvocable: false,
    input: "numbers",
    output: "numbers",
    related: ["compound-interest", "percentage", "discount", "currency-converter"],
    seoTitle: "EMI Calculator — Loan Payment & Amortisation Schedule | DO101",
    seoDescription:
      "Free EMI and loan calculator for home, car and personal loans. Monthly payment, total interest, full amortisation schedule and how much overpaying saves.",
    steps: [
      "Enter the loan amount, the yearly interest rate and the term in years or months.",
      "Read the monthly payment, the total interest and the total you will repay.",
      "See what share of your repayments goes to interest.",
      "Add an extra monthly amount to see how much sooner the loan clears and the interest saved.",
      "Open the schedule by year or by month to see each payment split into interest and principal.",
    ],
    features: [
      "EMI from the standard annuity formula lenders use",
      "Total interest, total repaid and interest as a share of the total",
      "Amortisation schedule by year or by every month",
      "Extra monthly payments: months saved and interest saved",
      "Term in years or months, and zero-interest loans handled",
      "The formula shown next to the answer",
      "Calculated in your browser — nothing is sent anywhere",
    ],
    faqs: [
      { q: "What is an EMI?", a: "An equated monthly instalment: the fixed amount you pay every month so that a loan, with its interest, is fully repaid by the end of the term. Early payments are mostly interest and later ones mostly principal, but the amount stays the same." },
      { q: "How is EMI calculated?", a: "EMI = P × r × (1 + r)^n ÷ ((1 + r)^n − 1), where P is the loan amount, r the monthly interest rate (the yearly rate ÷ 12 ÷ 100) and n the number of monthly payments. A ₹5,00,000 loan at 9.5% over 20 years comes to about ₹4,661 a month." },
      { q: "Why is so much of my early payment interest?", a: "Interest is charged on what you still owe. At the start you owe the whole amount, so most of the payment covers interest; as the balance falls, more of each payment goes to principal. The schedule shows that shift year by year." },
      { q: "Does paying extra each month really help?", a: "Usually a lot, because every extra payment goes straight to principal and stops interest being charged on it for the rest of the term. The calculator shows the months and interest saved. Check first whether your lender charges a prepayment fee." },
      { q: "Is this accurate for a floating-rate loan?", a: "Only until the rate changes. It assumes one fixed rate for the whole term. If your rate moves, re-run it with the new rate and the remaining balance and term." },
      { q: "Does it include fees and insurance?", a: "No. Processing fees, loan insurance and taxes vary by lender and are not part of the EMI formula, so add them separately when comparing offers." },
    ],
  },
  {
    id: "position-size",
    name: "Forex & Gold Position Size Calculator",
    short: "The right lot size for your stop-loss and risk limit, in any account currency.",
    long:
      "Enter your account balance, how much of it you are willing to lose on one trade, and where your stop-loss goes, and get the position size in lots that keeps the loss at exactly that limit. Works for gold (XAU/USD), silver and the major forex pairs, converts pip values into any account currency — including the cross pairs most calculators get wrong — and rounds down to whole 0.01 lots so the real risk can only come in under your limit. Leverage is treated as a ceiling you set, never a recommendation.",
    category: "calculator",
    route: "/calculators/position-size",
    keywords: [
      "position size calculator", "lot size calculator", "forex position size calculator",
      "gold lot size calculator", "xauusd lot size", "risk calculator forex", "forex risk management",
      "how many lots should i trade", "position sizing", "mt5 lot size calculator",
    ],
    aliases: ["lot size", "position size", "forex lot calculator", "gold position size", "risk per trade"],
    icon: "⚖️",
    accent: "sun",
    browserOnly: true,
    aiInvocable: false,
    input: "numbers",
    output: "numbers",
    related: ["pip-value", "trading-analyzer", "currency-converter", "compound-interest"],
    seoTitle: "Forex & Gold Position Size Calculator — Lot Size | DO101",
    seoDescription:
      "Free position size calculator for forex and gold (XAU/USD). Lot size from your stop-loss and risk %, in any account currency, rounded so risk stays under your limit.",
    steps: [
      "Choose your account currency and enter your balance and the percentage you will risk.",
      "Pick the instrument and enter your entry price.",
      "Enter the stop-loss as a distance in pips or as a price.",
      "Read the lot size, the money at risk and what one pip is worth at that size.",
      "For cross pairs, check the conversion rate — the ECB rate is filled in and you can type your broker's.",
    ],
    features: [
      "Lot size from stop distance and risk percentage",
      "Gold, silver and 12 major and cross forex pairs",
      "Pip values converted into 31 account currencies, cross pairs included",
      "Stop-loss by pips or by price",
      "Rounds down to 0.01 lots so risk never exceeds your limit",
      "Warns when leverage, not your risk limit, caps the size",
      "Calculated in your browser — nothing is sent anywhere",
    ],
    faqs: [
      { q: "How is position size calculated?", a: "Money at risk ÷ (stop distance × value of one pip per lot). With a $10,000 account risking 1%, you can lose $100; on gold, a 500-pip ($5) stop costs $500 per standard lot, so the size is 100 ÷ 500 = 0.20 lots." },
      { q: "What does one pip mean on gold?", a: "On XAU/USD a pip is usually $0.01 and a standard lot is 100 ounces, so one pip is worth $1 per lot and a $1 move in price is $100 per lot. Brokers differ, so check your platform's contract size — the calculator uses the common retail values." },
      { q: "Why do I need a conversion rate for some pairs?", a: "A pip is worth a fixed amount of the pair's quote currency. If that is not your account currency — EUR/GBP for a dollar account, say — it has to be converted. The calculator fills in the ECB reference rate automatically, and you can type your broker's rate instead." },
      { q: "What leverage should I use?", a: "This calculator will not suggest one, because the right answer depends on your circumstances. Leverage never changes what your stop costs — the position size does — but it caps how big a position you are allowed to hold, and higher leverage means a smaller adverse move can wipe out the account." },
      { q: "Why is the lot size rounded down?", a: "Brokers trade in steps, usually 0.01 lots. Rounding down means the actual risk can only come out slightly under your limit, never over it. If the correct size is below 0.01, the calculator says so rather than rounding up past your limit." },
      { q: "Is this financial advice?", a: "No. It is arithmetic on the numbers you enter. It does not know your circumstances and does not suggest trades." },
    ],
  },
  {
    id: "pip-value",
    name: "Pip Value Calculator",
    short: "What one pip is worth on any forex pair or gold, in your own currency.",
    long:
      "Pick a forex pair or gold, choose your account currency and position size, and see exactly what one pip — and any move you choose — is worth. It shows standard, mini and micro lots side by side and explains the calculation for each case: pairs quoted in your currency, pairs where your currency is the base, and cross pairs that need converting. Conversion uses the European Central Bank's daily reference rates, fetched from your browser, and you can type your broker's own price instead.",
    category: "calculator",
    route: "/calculators/pip-value",
    keywords: [
      "pip value calculator", "pip calculator", "forex pip calculator", "gold pip value",
      "xauusd pip value", "how much is a pip", "pip value usdjpy", "lot size pip value",
      "mini lot pip value", "micro lot pip value",
    ],
    aliases: ["pip calculator", "pip value", "how much is one pip", "forex pips"],
    icon: "📐",
    accent: "sun",
    browserOnly: true,
    aiInvocable: false,
    input: "numbers",
    output: "numbers",
    related: ["position-size", "trading-analyzer", "currency-converter", "percentage"],
    seoTitle: "Pip Value Calculator — Forex & Gold, Any Currency | DO101",
    seoDescription:
      "Free pip value calculator for forex pairs and gold. What one pip is worth for standard, mini and micro lots, converted into your account currency at ECB rates.",
    steps: [
      "Pick the instrument and your account currency.",
      "Enter your position size in lots and a price move in pips.",
      "Read what one pip and your chosen move are worth.",
      "Compare standard, mini and micro lots in the table.",
    ],
    features: [
      "Pip value for gold, silver and 12 forex pairs",
      "31 account currencies, including cross-pair conversion",
      "Standard, mini and micro lots side by side",
      "Value of any pip move you choose",
      "ECB reference rates filled in, or type your broker's price",
      "Explains which of the three calculations applies",
      "Calculated in your browser — nothing is sent anywhere",
    ],
    faqs: [
      { q: "How much is one pip worth?", a: "Contract size × pip size, converted into your account currency. On EUR/USD a standard lot is 100,000 euros and a pip is 0.0001, so one pip is $10 per lot. On gold it is usually $1 per lot, and on USD/JPY around $6–7 depending on the price." },
      { q: "Why is a USD/JPY pip not worth $10?", a: "Because USD/JPY is priced in yen. A pip is 1,000 yen per standard lot, and turning that into dollars means dividing by the price. At 150 yen per dollar, that is about $6.67." },
      { q: "What are standard, mini and micro lots?", a: "A standard lot is 100,000 units of the base currency, a mini lot 10,000 and a micro lot 1,000 — or 1, 0.1 and 0.01 lots. Gold is quoted differently: a standard lot is usually 100 troy ounces." },
      { q: "Where do the conversion rates come from?", a: "The European Central Bank's daily reference rates, fetched straight from your browser through the free Frankfurter service. They are published once per working day, so for precise figures type in your broker's live price." },
      { q: "Is a pip the same as a point?", a: "Not always. On five-digit forex quotes a point is a tenth of a pip. On gold many platforms call $0.01 a point and others a pip. The calculator states the pip size it is using for each instrument." },
    ],
  },
];
