import type { Tool } from "../types";

/**
 * File and data format converters. Documents, spreadsheets and structured
 * data, all converted inside the visitor's browser.
 */
export const CONVERTERS_TOOLS: Tool[] = [
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    short: "Turn a spreadsheet export into JSON.",
    long: "Converts CSV into JSON, detecting the delimiter automatically, honouring quoted fields with embedded commas and newlines, and optionally converting numbers and booleans to real types.",
    category: "converter",
    route: "/tools/csv-to-json",
    keywords: ["csv to json", "convert csv to json", "csv json converter", "spreadsheet to json", "excel csv to json"],
    aliases: ["convert csv file to json", "csv json"],
    icon: "📊",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-to-csv", "json-formatter", "xml-to-json", "yaml-to-json"],
    seoTitle: "CSV to JSON Converter — Free Online Tool | DO101",
    seoDescription: "Convert CSV to JSON with automatic delimiter detection, proper quoted-field handling and optional type conversion. Free and browser-based.",
    steps: [
      "Paste your CSV, or export one from your spreadsheet.",
      "Confirm the header row and delimiter.",
      "Copy or download the JSON.",
    ],
    features: [
      "Detects comma, semicolon, tab and pipe delimiters",
      "Handles quoted fields containing commas and newlines",
      "Optional number and boolean conversion",
      "Header row produces objects; no header produces arrays",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "How are quoted fields handled?",
        a: "Properly. A field wrapped in quotes may contain commas, newlines and escaped quotes, and all of it is preserved — which is where naive split-on-comma converters go wrong.",
      },
      {
        q: "Why is my ID column turning into a number?",
        a: "Type conversion turns numeric-looking values into numbers, which can drop leading zeros. Switch off \"convert numbers and booleans\" to keep everything as strings.",
      },
      {
        q: "Is my spreadsheet uploaded?",
        a: "No. Conversion happens on your device, which matters when the file contains customer data.",
      },
    ],
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    short: "Flatten a JSON array into a spreadsheet-ready CSV.",
    long: "Turns an array of JSON objects into CSV, building the header from the union of every object's keys so records with missing fields still line up. Values containing commas or quotes are escaped correctly.",
    category: "converter",
    route: "/tools/json-to-csv",
    keywords: ["json to csv", "convert json to csv", "json to excel", "json csv converter", "api response to spreadsheet"],
    aliases: ["json to spreadsheet", "export json as csv"],
    icon: "📈",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["csv-to-json", "json-formatter", "json-to-yaml", "json-minifier"],
    seoTitle: "JSON to CSV Converter — Free Online Tool | DO101",
    seoDescription: "Convert a JSON array into CSV ready for Excel or Google Sheets, with correct escaping and a header built from every key. Free and private.",
    steps: [
      "Paste a JSON array.",
      "Choose the delimiter and whether to include a header.",
      "Copy or download the CSV.",
    ],
    features: [
      "Header built from the union of all keys",
      "Correct quoting for commas, quotes and newlines",
      "Nested objects serialised as JSON in the cell",
      "Comma, semicolon, tab or pipe output",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "What happens to nested objects?",
        a: "CSV is flat, so a nested object or array is written into the cell as JSON text. Flatten the structure first if you need separate columns.",
      },
      {
        q: "Why do some rows have empty cells?",
        a: "The header is the union of every object's keys, so a record missing a field gets an empty cell rather than a shifted row.",
      },
      {
        q: "Will Excel open it correctly?",
        a: "Yes. If your locale uses semicolons as the list separator, choose semicolon as the delimiter and Excel will split the columns properly.",
      },
    ],
  },
  {
    id: "excel-to-csv",
    name: "Excel to CSV",
    short: "Export a spreadsheet sheet as plain CSV.",
    long: "Reads .xlsx, .xls and .ods files and writes clean, correctly-quoted CSV — the format almost every other system will accept.",
    category: "converter",
    route: "/tools/excel-to-csv",
    keywords: ["excel to csv", "xlsx to csv", "convert excel to csv", "spreadsheet to csv"],
    aliases: ["xlsx to csv", "save excel as csv"],
    icon: "📊",
    accent: "sky",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["csv-to-excel", "csv-to-json", "excel-to-pdf", "json-to-csv"],
    seoTitle: "Excel to CSV Converter — Free & In-Browser | DO101",
    seoDescription: "Convert Excel .xlsx, .xls and .ods files to correctly-quoted CSV. Free, no upload, and processed entirely inside your browser.",
    steps: [
      "Add your Excel file.",
      "Check the preview.",
      "Download the CSV.",
    ],
    features: [
      "Reads .xlsx, .xls and .ods",
      "Correct quoting for commas and newlines",
      "Preview before downloading",
      "No row limit beyond your device's memory",
      "Parsed on your device",
    ],
    faqs: [
      {
        q: "What happens to multiple sheets?",
        a: "CSV holds a single table, so the first sheet is exported and the tool tells you when others were left out. Convert each sheet separately if you need them all.",
      },
      {
        q: "Are dates preserved?",
        a: "Dates are written as the text your spreadsheet displays, which avoids the classic problem of them arriving as raw serial numbers.",
      },
    ],
  },
  {
    id: "csv-to-excel",
    name: "CSV to Excel",
    short: "Turn a CSV into a real .xlsx workbook.",
    long: "Parses CSV — handling quoted fields containing commas and newlines — and writes a genuine Excel workbook, so the file opens cleanly without an import wizard.",
    category: "converter",
    route: "/tools/csv-to-excel",
    keywords: ["csv to excel", "csv to xlsx", "convert csv to excel", "open csv in excel"],
    aliases: ["csv to xlsx", "make excel from csv"],
    icon: "📈",
    accent: "sky",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["excel-to-csv", "csv-to-json", "excel-to-pdf", "json-to-csv"],
    seoTitle: "CSV to Excel Converter — Free XLSX Export | DO101",
    seoDescription: "Convert CSV files into real Excel .xlsx workbooks with correct handling of quoted fields. Free, no sign-up, and entirely in your browser.",
    steps: [
      "Add your CSV file.",
      "Check the preview.",
      "Download the .xlsx workbook.",
    ],
    features: [
      "Handles quoted fields with commas and newlines",
      "Produces a genuine .xlsx, not a renamed CSV",
      "Preview before downloading",
      "No account or upload",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "Why not just rename the file?",
        a: "Renaming a .csv to .xlsx produces a file Excel refuses to open. This writes a real workbook in the correct format.",
      },
      {
        q: "Will leading zeros survive?",
        a: "Values are written as text where they are not clearly numeric, which preserves things like 007 and phone numbers better than a plain CSV import.",
      },
    ],
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    short: "Convert between 31 currencies at today's ECB reference rate, with history.",
    long:
      "Convert between 31 currencies at the European Central Bank's daily reference rate, including the US dollar, euro, pound, yen, Indian rupee and Nepalese rupee. See the rate both ways, a chart of the pair over one month, three months or a year, and what you would actually receive once a bank or card adds its margin — the part other converters leave out. Rates come straight from the ECB via the free Frankfurter service, fetched by your browser, with no account and no sign-up.",
    category: "converter",
    route: "/tools/currency-converter",
    keywords: [
      "currency converter", "exchange rate", "usd to inr", "usd to eur", "eur to gbp",
      "usd to npr", "inr to npr", "dollar to rupee", "live exchange rates", "ecb exchange rate",
      "currency exchange calculator", "forex rates today",
    ],
    aliases: ["exchange rates", "convert currency", "money converter", "fx converter", "currency calculator"],
    icon: "💱",
    accent: "grass",
    browserOnly: true,
    aiInvocable: false,
    input: "numbers",
    output: "numbers",
    related: ["pip-value", "compound-interest", "loan-emi", "percentage"],
    seoTitle: "Currency Converter — ECB Exchange Rates, 31 Currencies | DO101",
    seoDescription:
      "Free currency converter using official ECB reference rates: USD, EUR, GBP, INR, NPR, JPY and more. Rate history charts and what a bank margin really costs.",
    steps: [
      "Enter an amount and pick the currencies to convert from and to, or tap a popular pair.",
      "Read the converted amount and the rate in both directions.",
      "Move the margin slider to see what a bank or card would actually give you.",
      "Check the chart to see how the pair has moved over a month, three months or a year.",
    ],
    features: [
      "31 currencies at the ECB's daily reference rate",
      "Nepalese rupee included, derived from its official peg to the Indian rupee",
      "Rate both ways, and the amount in six other major currencies",
      "What a bank, card or exchange margin really costs you",
      "One-month, three-month and one-year history chart",
      "Popular pairs one tap away",
      "No account — rates are fetched directly by your browser",
    ],
    faqs: [
      { q: "Where do these exchange rates come from?", a: "The European Central Bank, which publishes an official reference rate for 30 currencies at around 16:00 CET every working day. The converter fetches them straight from your browser through the free Frankfurter service. At weekends and on holidays the last working day's rate is shown, with its date." },
      { q: "Why is my bank's rate different?", a: "Because the reference rate is the mid-market rate, and every bank, card and exchange counter adds a margin on top. That margin is the real cost of the exchange, often 2–5% and sometimes more at airports. The slider shows what a given margin leaves you with." },
      { q: "How is the Nepalese rupee converted?", a: "The ECB does not publish a rate for the Nepalese rupee, but Nepal Rastra Bank pegs it to the Indian rupee at 1 INR = 1.60 NPR. The converter uses the ECB's Indian rupee rate and applies that peg, and says so whenever NPR is selected." },
      { q: "Are these live rates?", a: "They are daily reference rates, updated once each working day — accurate and official, but not tick-by-tick. For trading, use your broker's live quote." },
      { q: "How are rates between two non-euro currencies worked out?", a: "Through the euro, the way the ECB publishes them. USD to INR, for example, is the euro's INR rate divided by the euro's USD rate. That is the standard way cross rates are built from reference rates." },
    ],
  },
  {
    id: "video-to-mp3",
    name: "Video to MP3",
    short: "Convert any video to MP3 — MP4, MOV, WebM and more. Free, and nothing is uploaded.",
    long:
      "Turn a video into an MP3 in your browser: a lecture, a Zoom or Teams recording, a phone video, a screen recording or a video you uploaded yourself. Pick the quality from 128 to 320 kbps, trim to just the part you want, and switch to mono for speech to halve the size. The audio is decoded by your own browser and encoded to MP3 on your device, so the file is never uploaded — there is no size-limited server queue, no watermark, no sign-up and no cost.",
    category: "converter",
    route: "/tools/video-to-mp3",
    keywords: [
      "video to mp3", "mp4 to mp3", "convert video to mp3", "mp4 to mp3 converter",
      "extract audio from video", "video to audio converter", "mov to mp3", "webm to mp3",
      "m4a to mp3", "wav to mp3", "convert mp4 to mp3 free", "video to mp3 converter online",
      "iphone video to mp3", "zoom recording to mp3",
    ],
    aliases: [
      "mp4 to mp3", "extract audio", "audio extractor", "video to audio", "mp3 converter",
      "rip audio from my video", "convert to mp3",
    ],
    icon: "🎵",
    accent: "fire",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["youtube-downloader", "image-converter", "heic-to-jpg", "pdf-compress"],
    seoTitle: "Video to MP3 Converter — Free MP4 to MP3, No Upload | DO101",
    seoDescription:
      "Convert MP4, MOV, WebM and other videos to MP3 free in your browser. Choose 128–320 kbps, trim the clip, go mono for speech. No upload, no sign-up, no watermark.",
    steps: [
      "Drop a video or audio file in, or tap Choose file — MP4, MOV, WebM, M4A and WAV all work.",
      "Pick the MP3 quality. 192 kbps suits most things; 128 kbps with Mono is plenty for speech.",
      "Optionally type a start and end time to keep only part of it.",
      "Press Convert to MP3, listen to the result, and download it.",
    ],
    features: [
      "Converts MP4, MOV, M4V, WebM, M4A, AAC, WAV, OGG, FLAC and more",
      "Quality from 128 to 320 kbps, with the file size shown before you convert",
      "Trim to a start and end time without a separate editor",
      "Mono option that halves the size of lectures and voice notes",
      "Preview the video and the finished MP3 on the page",
      "Runs in your browser — the file is never uploaded, so it stays private",
      "Free, no sign-up, no watermark and no daily limit",
    ],
    faqs: [
      {
        q: "How do I convert an MP4 to MP3?",
        a: "Drop the MP4 onto this page, choose a quality, and press Convert to MP3. The audio track is decoded and re-encoded as an MP3 on your own device, and a download button appears when it is done. The same works for MOV, WebM, M4V and most other video files.",
      },
      {
        q: "Is this video to MP3 converter really free?",
        a: "Yes. There is no sign-up, no watermark, no daily limit and no paid tier. Because the conversion runs on your own device, it costs DO101 nothing to run, so there is nothing to charge for.",
      },
      {
        q: "Are my videos uploaded anywhere?",
        a: "No. Your browser decodes the audio itself and the MP3 encoder (lamejs) runs as JavaScript on this page. There is no upload endpoint behind the tool — you can disconnect from the internet after the page has loaded and it still works.",
      },
      {
        q: "Which MP3 quality should I choose?",
        a: "192 kbps is a good default for music and sounds the same as the source to most listeners. 320 kbps is the highest MP3 allows. For lectures, podcasts and voice notes, 128 kbps with Mono switched on is clear and about a quarter of the size of 320 kbps stereo.",
      },
      {
        q: "Can I convert only part of a video?",
        a: "Yes. Type a start time and an end time, such as 1:30 and 4:05, and only that section becomes an MP3. The estimated file size updates as you type.",
      },
      {
        q: "Is there a file size limit?",
        a: "There is no limit set by DO101, but the whole audio track is held in your browser's memory while it converts. Files up to about an hour convert comfortably on a laptop; very long or very large files can run out of memory, especially on phones. Trimming, or choosing Mono, helps.",
      },
      {
        q: "Why won't my file convert?",
        a: "The browser has to be able to decode the audio itself. MP4, MOV, M4A, WebM, MP3, WAV and OGG work in every current browser. AVI, WMV, MKV and some older formats depend on the browser — Chrome and Edge read the most. A video with no sound track has nothing to convert.",
      },
      {
        q: "Can I convert a YouTube video to MP3?",
        a: "DO101 does not download from YouTube, because YouTube's Terms of Service do not allow it. If the video is yours, download the original from YouTube Studio, then drop that file here to get an MP3. For anyone else's video, YouTube Premium offers offline listening inside the app.",
      },
      {
        q: "Does it work on iPhone and Android?",
        a: "Yes, in Safari, Chrome and other current mobile browsers. Choose the video from your photo library or files. Long videos need more memory than a phone may have, so trim them or switch on Mono.",
      },
    ],
    featured: true,
  },
];
