import type { Tool } from "../types";

/**
 * Developer tools. Parsing, encoding and hashing with the browser's own APIs.
 */
export const DEVELOPER_TOOLS: Tool[] = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    short: "Beautify, minify and validate JSON with error positions.",
    long:
      "Paste raw JSON and get readable, indented output — or minify it back down for shipping. Invalid JSON is reported with the line and column of the problem instead of a vague parse error.",
    category: "developer",
    route: "/tools/json-formatter",
    keywords: ["json formatter", "format json", "beautify json", "json pretty print", "minify json", "json parser"],
    aliases: ["pretty print json", "beautify json", "make json readable"],
    icon: "{ }",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-validator", "base64", "uuid-generator", "regex-tester"],
    seoTitle: "Free JSON Formatter & Beautifier — Online JSON Viewer | DO101",
    seoDescription:
      "Format, beautify, minify and validate JSON online. Clear error messages with line and column numbers. Free, fast and runs in your browser.",
    steps: ["Paste your JSON.", "Choose an indent size, or press minify.", "Copy or download the formatted result."],
    features: [
      "2, 4 and tab indentation",
      "Minify to the smallest valid JSON",
      "Precise error line and column",
      "Sort keys alphabetically",
      "Copy or download in one tap",
    ],
    faqs: [
      { q: "Why does my JSON fail to parse?", a: "The usual culprits are trailing commas, single quotes instead of double quotes, unquoted keys and comments. JSON allows none of those — DO101 points at the exact character that broke the parse." },
      { q: "Is my JSON sent to a server?", a: "No. Parsing uses the browser's built-in JSON engine, so payloads with API keys or customer data never leave your machine." },
      { q: "Can it handle large files?", a: "Files up to a few megabytes format instantly. Enormous documents may be slow to render because of the browser, not the parser." },
    ],
    featured: true,
  },
  {
    id: "json-validator",
    name: "JSON Validator",
    short: "Check whether JSON is valid and see exactly what broke.",
    long:
      "A focused pass/fail check for JSON. Valid documents report their type, key count and nesting depth. Invalid documents get the line, column and the offending snippet highlighted.",
    category: "developer",
    route: "/tools/json-validator",
    keywords: ["json validator", "validate json", "json checker", "is my json valid", "json syntax check"],
    aliases: ["check json", "json lint"],
    icon: "✅",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-formatter", "base64", "jwt-decoder", "regex-tester"],
    seoTitle: "Free JSON Validator — Check JSON Syntax Online | DO101",
    seoDescription:
      "Validate JSON online and get the exact line and column of any syntax error, plus structure statistics. Free and browser-based.",
    steps: ["Paste the JSON you want to check.", "Read the pass or fail banner.", "Jump to the reported line to fix an error."],
    features: ["Instant valid / invalid verdict", "Line and column of the first error", "Key count, depth and root type", "Duplicate key warning", "No upload"],
    faqs: [
      { q: "Does it validate against a JSON Schema?", a: "Not yet. This tool checks syntax — whether the document is parseable JSON. Schema validation is on the roadmap." },
      { q: "Are duplicate keys invalid?", a: "Strictly they are allowed by the spec, but almost every parser silently keeps only the last one, so DO101 warns you when it spots them." },
    ],
  },
  {
    id: "base64",
    name: "Base64 Encoder & Decoder",
    short: "Encode or decode Base64 text and files, Unicode-safe.",
    long:
      "Convert text to Base64 and back, including full Unicode and emoji, which naive implementations mangle. You can also encode a file into a Base64 data URI for embedding in CSS or HTML.",
    category: "developer",
    route: "/tools/base64",
    keywords: ["base64 encoder", "base64 decoder", "encode base64", "decode base64", "base64 to text", "data uri"],
    aliases: ["b64", "base 64", "encode to base64"],
    icon: "🔐",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["url-encoder", "json-formatter", "hash-generator", "jwt-decoder"],
    seoTitle: "Base64 Encoder & Decoder — Unicode Safe & Free | DO101",
    seoDescription:
      "Encode and decode Base64 online, with full Unicode and emoji support plus file to data-URI conversion. Free, instant and private.",
    steps: ["Choose encode or decode.", "Paste your text, or drop a file to get a data URI.", "Copy the result."],
    features: ["Unicode and emoji safe", "URL-safe Base64 variant", "File to data URI", "Instant swap between encode and decode", "Runs offline in your browser"],
    faqs: [
      { q: "Is Base64 encryption?", a: "No. Base64 is an encoding, not encryption — anyone can decode it. Never use it to protect passwords or secrets." },
      { q: "What is URL-safe Base64?", a: "A variant that replaces + and / with - and _ so the string can sit inside a URL without escaping. JWTs use it." },
      { q: "Why do emoji break in other tools?", a: "The classic btoa() function only accepts Latin-1. DO101 encodes to UTF-8 bytes first, so every character survives the round trip." },
    ],
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    short: "Percent-encode text so it is safe inside a URL.",
    long:
      "Turn spaces, ampersands, accents and emoji into percent-encoded escapes so a URL or query string survives being passed around. Choose between component encoding and full-URI encoding.",
    category: "developer",
    route: "/tools/url-encoder",
    keywords: ["url encoder", "percent encoding", "encode url", "urlencode", "query string encoder", "escape url"],
    aliases: ["urlencode", "escape url", "encode query string"],
    icon: "🔗",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["url-decoder", "base64", "json-formatter", "qr-generator"],
    seoTitle: "Free URL Encoder — Percent-Encode Text Online | DO101",
    seoDescription:
      "Encode text for safe use in URLs and query strings, with component and full-URI modes. Free online URL encoder that runs in your browser.",
    steps: ["Paste the text or URL.", "Pick component or full-URI encoding.", "Copy the encoded string."],
    features: ["encodeURIComponent and encodeURI modes", "Handles Unicode and emoji", "Query-string builder view", "One-tap copy", "No upload"],
    faqs: [
      { q: "What is the difference between the two modes?", a: "Component mode escapes everything including &, = and /, which is right for a single value. Full-URI mode leaves the characters that give a URL its structure intact." },
      { q: "Why does a space become %20 sometimes and + at others?", a: "%20 is correct everywhere. The + form only applies inside application/x-www-form-urlencoded form bodies." },
    ],
  },
  {
    id: "url-decoder",
    name: "URL Decoder",
    short: "Turn percent-encoded escapes back into readable text.",
    long:
      "Paste an encoded URL and read it in plain language, with the query parameters broken out into a table so you can see exactly what a link is carrying.",
    category: "developer",
    route: "/tools/url-decoder",
    keywords: ["url decoder", "decode url", "urldecode", "percent decode", "decode query string"],
    aliases: ["urldecode", "unescape url", "read encoded url"],
    icon: "🔓",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["url-encoder", "base64", "jwt-decoder", "json-formatter"],
    seoTitle: "Free URL Decoder — Decode Percent-Encoded URLs | DO101",
    seoDescription:
      "Decode percent-encoded URLs and query strings online, with a parameter breakdown table. Free, instant and browser-based.",
    steps: ["Paste the encoded URL.", "Read the decoded text.", "Inspect the parsed query parameters below."],
    features: ["Handles double-encoded strings", "Query parameter table", "Clear error when the input is malformed", "Unicode safe", "Nothing is uploaded"],
    faqs: [
      { q: "Why do I get a malformed URI error?", a: "A stray % that is not followed by two hex digits makes the string undecodable. DO101 tells you where it is instead of throwing a raw exception." },
      { q: "What is double encoding?", a: "When an already-encoded string is encoded again, %20 becomes %2520. Decode twice to get back to the original." },
    ],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    short: "Generate v4 UUIDs in bulk with a cryptographic source.",
    long:
      "Create random version-4 UUIDs using the browser's cryptographic random number generator. Generate one, or a thousand, and copy or download the list.",
    category: "developer",
    route: "/tools/uuid-generator",
    keywords: ["uuid generator", "guid generator", "random uuid", "uuid v4", "bulk uuid"],
    aliases: ["guid", "generate uuid", "random id"],
    icon: "🎲",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "text",
    related: ["hash-generator", "json-formatter", "base64", "timestamp-converter"],
    seoTitle: "Free UUID Generator — Bulk UUID v4 Online | DO101",
    seoDescription:
      "Generate cryptographically random UUID v4 values in bulk, with uppercase, no-dash and braces options. Free and generated in your browser.",
    steps: ["Choose how many UUIDs you need.", "Press generate.", "Copy the list or download it as a text file."],
    features: ["Up to 1,000 at a time", "Uses crypto.getRandomValues", "Uppercase, no-dash and braces formats", "Copy all or copy one", "Generated locally — never on a server"],
    faqs: [
      { q: "Are these UUIDs really unique?", a: "A v4 UUID has 122 random bits. The chance of a collision is negligible for any realistic number of IDs, which is why they are safe to generate client side." },
      { q: "Do you log the generated values?", a: "No. They are produced in your browser and never sent anywhere." },
    ],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    short: "Read the header and payload of a JSON Web Token.",
    long:
      "Paste a JWT to see its decoded header and payload, with timestamps rendered as readable dates and expiry highlighted. Decoding does not verify the signature — DO101 says so plainly rather than implying the token is trustworthy.",
    category: "developer",
    route: "/tools/jwt-decoder",
    keywords: ["jwt decoder", "decode jwt", "json web token", "jwt parser", "read jwt payload"],
    aliases: ["decode token", "jwt viewer", "read jwt"],
    icon: "🎫",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["base64", "json-formatter", "timestamp-converter", "hash-generator"],
    seoTitle: "Free JWT Decoder — Decode JSON Web Tokens Online | DO101",
    seoDescription:
      "Decode the header and payload of a JSON Web Token in your browser, with human-readable timestamps. Decoding does not verify the signature.",
    steps: ["Paste the JWT.", "Read the decoded header and payload.", "Check the expiry banner for iat, nbf and exp."],
    features: [
      "Header and payload decoded as formatted JSON",
      "iat, nbf and exp shown as local dates",
      "Expiry warning when the token is stale",
      "Standard claim explanations",
      "Decoded in your browser — tokens are never transmitted",
    ],
    faqs: [
      { q: "Does this verify the token?", a: "No. Decoding a JWT does not verify its signature. Anyone can read or forge the payload of an unverified token — only your server, holding the secret or public key, can confirm it is authentic." },
      { q: "Is it safe to paste a real token here?", a: "The decoding happens locally and nothing is sent to DO101. Even so, treat live tokens like passwords and avoid pasting production credentials into any website." },
    ],
  },
  {
    id: "timestamp-converter",
    name: "Unix Timestamp Converter",
    short: "Convert between Unix timestamps and human dates.",
    long:
      "Turn a Unix timestamp into a readable date, or a date into a timestamp. Seconds and milliseconds are both supported and auto-detected, with UTC and local time shown side by side.",
    category: "developer",
    route: "/tools/timestamp-converter",
    keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "date to timestamp", "epoch time", "milliseconds to date"],
    aliases: ["epoch converter", "unix time", "convert timestamp"],
    icon: "⏱️",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["jwt-decoder", "json-formatter", "age", "uuid-generator"],
    seoTitle: "Unix Timestamp Converter — Epoch to Date Online | DO101",
    seoDescription:
      "Convert Unix timestamps to dates and dates to timestamps, in seconds or milliseconds, with UTC and local time. Free online epoch converter.",
    steps: ["Paste a timestamp, or pick a date.", "Seconds versus milliseconds is detected automatically.", "Copy the format you need."],
    features: ["Auto-detects seconds or milliseconds", "UTC, local time and ISO 8601 output", "Relative time (\"3 hours ago\")", "Live current timestamp", "Runs offline"],
    faqs: [
      { q: "How do I tell seconds from milliseconds?", a: "A current timestamp in seconds has 10 digits; in milliseconds it has 13. DO101 checks the magnitude and tells you which it assumed." },
      { q: "What is the Unix epoch?", a: "00:00:00 UTC on 1 January 1970. A Unix timestamp counts the seconds elapsed since that moment, ignoring leap seconds." },
    ],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    short: "Test regular expressions with live matches and groups.",
    long:
      "Write a pattern, set the flags, and see every match highlighted in your test string along with the capture groups. Invalid patterns get a plain-English explanation rather than a cryptic engine error.",
    category: "developer",
    route: "/tools/regex-tester",
    keywords: ["regex tester", "regular expression tester", "test regex", "regex online", "regex match", "regex101 alternative"],
    aliases: ["regexp tester", "test regular expression", "regex checker"],
    icon: "🧪",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-formatter", "text-diff", "text-cleaner", "base64"],
    seoTitle: "Free Regex Tester — Test Regular Expressions Online | DO101",
    seoDescription:
      "Test JavaScript regular expressions with live match highlighting, capture groups, flags and a cheat sheet. Free and runs in your browser.",
    steps: ["Type your pattern and pick flags.", "Paste a test string.", "Read the highlighted matches and the capture group table."],
    features: [
      "Live match highlighting",
      "Numbered and named capture groups",
      "All JavaScript flags: g, i, m, s, u, y",
      "Catastrophic-backtracking guard with a timeout",
      "Built-in cheat sheet",
    ],
    faqs: [
      { q: "Which regex flavour is this?", a: "JavaScript (ECMAScript). Most patterns are portable, but lookbehind and named groups behave differently in older engines such as PCRE or Python." },
      { q: "Is my pattern executed safely?", a: "Patterns run as regular expressions only — DO101 never evaluates your input as JavaScript code, and a timeout stops runaway backtracking from freezing the tab." },
    ],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    short: "Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes.",
    long:
      "Hash text or a file with the browser's native Web Crypto implementation. Useful for checksums, cache keys and verifying that a download matches its published digest.",
    category: "developer",
    route: "/tools/hash-generator",
    keywords: ["hash generator", "sha256 generator", "sha1", "sha512", "checksum", "file hash", "hash text"],
    aliases: ["sha256", "checksum calculator", "generate hash"],
    icon: "#️⃣",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["base64", "uuid-generator", "jwt-decoder", "json-formatter"],
    seoTitle: "Free Hash Generator — SHA-256, SHA-1 & SHA-512 | DO101",
    seoDescription:
      "Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from text or files using Web Crypto. Free, instant and entirely in your browser.",
    steps: ["Paste text, or drop a file.", "Pick the algorithms you want.", "Copy the hex digest."],
    features: ["SHA-1, SHA-256, SHA-384 and SHA-512", "Text and file hashing", "Hex and Base64 output", "Compare against an expected digest", "Uses the browser's Web Crypto API"],
    faqs: [
      { q: "Why is MD5 not offered?", a: "Browsers do not ship MD5 in Web Crypto, and it is cryptographically broken. Adding it would mean shipping a third-party implementation for an algorithm nobody should choose today." },
      { q: "Can I verify a downloaded file?", a: "Yes. Drop the file in, pick SHA-256, and paste the publisher's digest into the compare box. The file is read locally and never uploaded." },
      { q: "Is SHA-256 safe for passwords?", a: "No. Passwords need a slow, salted algorithm such as bcrypt, scrypt or Argon2. A plain SHA hash is far too fast to be safe for that job." },
    ],
  },
  {
    id: "json-minifier",
    name: "JSON Minifier",
    short: "Strip whitespace from JSON to shrink payloads.",
    long: "Remove every unnecessary space and newline from a JSON document and see exactly how much smaller it got. Invalid JSON is reported with the line and column rather than a vague failure.",
    category: "developer",
    route: "/tools/json-minifier",
    keywords: ["json minifier", "minify json", "compress json", "json compact", "shrink json"],
    aliases: ["compact json", "minimise json"],
    icon: "📦",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-formatter", "json-validator", "json-escape", "json-to-csv"],
    seoTitle: "JSON Minifier — Compress JSON Online Free | DO101",
    seoDescription: "Minify JSON by removing all unnecessary whitespace, with before and after sizes and the percentage saved. Free and running in your browser.",
    steps: [
      "Paste your JSON.",
      "Read the size saving.",
      "Copy or download the minified output.",
    ],
    features: [
      "Removes all insignificant whitespace",
      "Before, after and percentage saved",
      "Validates as it minifies",
      "Copy or download as .json",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Does minifying change my data?",
        a: "No. It removes formatting only. Parse the minified output and you get exactly the same values back.",
      },
      {
        q: "How much will it save?",
        a: "Pretty-printed JSON is often 20–40% whitespace. Over an API serving many requests, that adds up quickly.",
      },
      {
        q: "Should I minify JSON I keep in Git?",
        a: "Usually not — formatted JSON produces readable diffs. Minify what you send over the wire, not what you version.",
      },
    ],
  },
  {
    id: "json-escape",
    name: "JSON Escape / Unescape",
    short: "Make text safe inside a JSON string, or turn it back.",
    long: "Escapes quotes, backslashes, newlines and control characters so a block of text can be embedded in a JSON string — and reverses the process when you need to read an escaped string back.",
    category: "developer",
    route: "/tools/json-escape",
    keywords: ["json escape", "escape json string", "unescape json", "json string escape online"],
    aliases: ["escape quotes for json", "unescape json string"],
    icon: "🪄",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-formatter", "json-minifier", "base64", "html-encoder"],
    seoTitle: "JSON Escape & Unescape — Free Online Tool | DO101",
    seoDescription: "Escape text for use inside a JSON string, or unescape a JSON string back to plain text. Handles quotes, newlines and control characters. Free.",
    steps: [
      "Paste your text or escaped string.",
      "Choose escape or unescape.",
      "Copy the result.",
    ],
    features: [
      "Escapes quotes, backslashes, newlines and tabs",
      "Optional surrounding quotes for a complete literal",
      "Unescape direction included",
      "Unicode safe",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "When do I need this?",
        a: "Whenever you paste multi-line text or text containing quotes into a JSON config, a test fixture or an API request body.",
      },
      {
        q: "What is the \"wrap in quotes\" option?",
        a: "It produces a complete JSON string literal, quotes included, ready to paste as a value.",
      },
    ],
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    short: "Beautify or minify XML with proper indentation.",
    long: "Re-indent XML so nesting is visible at a glance, or strip it back to a single line for transmission. Works on any XML including SVG, RSS, SOAP and configuration files.",
    category: "developer",
    route: "/tools/xml-formatter",
    keywords: ["xml formatter", "beautify xml", "format xml", "xml pretty print", "minify xml"],
    aliases: ["pretty print xml", "xml beautifier"],
    icon: "🏷️",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["xml-to-json", "json-to-xml", "json-formatter", "html-minifier"],
    seoTitle: "XML Formatter — Beautify & Minify XML Online Free | DO101",
    seoDescription: "Format XML with proper indentation or minify it to a single line. Works with SVG, RSS, SOAP and config files. Free and browser-based.",
    steps: [
      "Paste your XML.",
      "Choose beautify or minify.",
      "Copy the result.",
    ],
    features: [
      "2 or 4 space indentation",
      "Minify mode",
      "Handles declarations, comments and CDATA",
      "Works with SVG and RSS",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Does it validate my XML?",
        a: "This tool re-indents rather than validates. Use XML to JSON, which parses strictly, if you need to know whether the document is well formed.",
      },
      {
        q: "Will it break CDATA sections?",
        a: "Formatting works on tag boundaries, so CDATA content is preserved as written.",
      },
    ],
  },
  {
    id: "xml-to-json",
    name: "XML to JSON",
    short: "Convert XML documents into JSON.",
    long: "Parses XML with the browser's own strict parser and produces clean JSON, keeping attributes as @-prefixed keys and collapsing text-only elements into plain strings. Malformed XML is reported with the parser's own explanation.",
    category: "developer",
    route: "/tools/xml-to-json",
    keywords: ["xml to json", "convert xml to json", "xml json converter", "parse xml online"],
    aliases: ["convert xml file to json", "xml json"],
    icon: "➡️",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-to-xml", "xml-formatter", "json-formatter", "csv-to-json"],
    seoTitle: "XML to JSON Converter — Free Online Parser | DO101",
    seoDescription: "Convert XML to JSON with attribute handling and strict validation. Malformed XML is explained rather than silently mangled. Free and private.",
    steps: [
      "Paste your XML.",
      "Choose how to handle attributes.",
      "Copy the JSON result.",
    ],
    features: [
      "Strict parsing with clear error messages",
      "Attributes preserved as @-prefixed keys",
      "Repeated elements become arrays automatically",
      "Compact mode for text-only elements",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "How are attributes represented?",
        a: "As keys prefixed with @, so <price currency=\"GBP\"> becomes {\"@currency\": \"GBP\"}. Turn the option off to drop them.",
      },
      {
        q: "What happens to repeated elements?",
        a: "The first occurrence becomes a value; a second occurrence turns the key into an array. That is the standard convention for this conversion.",
      },
      {
        q: "Is the XML executed?",
        a: "No. It is parsed into an inert document that is never attached to the page.",
      },
    ],
  },
  {
    id: "json-to-xml",
    name: "JSON to XML",
    short: "Turn JSON into well-formed XML.",
    long: "Converts a JSON document into XML with a root element you name, arrays expanded into repeated item elements, and every value properly escaped.",
    category: "developer",
    route: "/tools/json-to-xml",
    keywords: ["json to xml", "convert json to xml", "json xml converter"],
    aliases: ["make xml from json"],
    icon: "⬅️",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["xml-to-json", "xml-formatter", "json-formatter", "json-to-yaml"],
    seoTitle: "JSON to XML Converter — Free Online Tool | DO101",
    seoDescription: "Convert JSON into well-formed XML with a custom root element and proper escaping. Free, instant, and runs entirely in your browser.",
    steps: [
      "Paste your JSON.",
      "Name the root and array item elements.",
      "Copy the XML output.",
    ],
    features: [
      "Custom root and item element names",
      "Correct escaping of &, < and >",
      "Invalid element names sanitised automatically",
      "Indented output",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Why do arrays need an item name?",
        a: "JSON array entries have no key of their own, but every XML element needs a tag. The item name fills that gap.",
      },
      {
        q: "What if my JSON keys are not valid XML names?",
        a: "Keys starting with a digit or containing punctuation are sanitised, since XML element names cannot contain them.",
      },
    ],
  },
  {
    id: "yaml-to-json",
    name: "YAML to JSON",
    short: "Convert YAML configuration into JSON.",
    long: "Parses YAML with js-yaml and outputs formatted JSON. Handy for turning a Docker Compose, Kubernetes or CI configuration into something a JSON-only tool can read.",
    category: "developer",
    route: "/tools/yaml-to-json",
    keywords: ["yaml to json", "convert yaml to json", "yml to json", "yaml parser"],
    aliases: ["yml to json", "parse yaml"],
    icon: "📜",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-to-yaml", "json-formatter", "xml-to-json", "csv-to-json"],
    seoTitle: "YAML to JSON Converter — Free Online Parser | DO101",
    seoDescription: "Convert YAML to JSON with clear error messages for invalid documents. Ideal for Docker Compose, Kubernetes and CI configs. Free and private.",
    steps: [
      "Paste your YAML.",
      "Read the JSON output.",
      "Copy or download it.",
    ],
    features: [
      "Full YAML 1.2 parsing",
      "Clear errors with the line that failed",
      "Handles anchors, multi-line strings and nesting",
      "Formatted JSON output",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Why does my YAML fail to parse?",
        a: "Almost always indentation — YAML is whitespace-sensitive and does not allow tabs for indentation. The error message names the line.",
      },
      {
        q: "Is my config uploaded?",
        a: "No. Parsing happens locally, which matters because CI and Kubernetes configs often contain internal hostnames.",
      },
    ],
  },
  {
    id: "json-to-yaml",
    name: "JSON to YAML",
    short: "Convert JSON into readable YAML.",
    long: "Turns JSON into YAML, which is easier for humans to read and edit — the usual reason to convert a configuration file before checking it into a repository.",
    category: "developer",
    route: "/tools/json-to-yaml",
    keywords: ["json to yaml", "convert json to yaml", "json yml converter"],
    aliases: ["json to yml", "make yaml from json"],
    icon: "📃",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["yaml-to-json", "json-formatter", "json-to-xml", "json-minifier"],
    seoTitle: "JSON to YAML Converter — Free Online Tool | DO101",
    seoDescription: "Convert JSON into clean, readable YAML with adjustable indentation and optional quoting. Free, instant and entirely in your browser.",
    steps: [
      "Paste your JSON.",
      "Choose the indentation.",
      "Copy the YAML output.",
    ],
    features: [
      "2 or 4 space indentation",
      "Optional forced quoting for ambiguous values",
      "Handles deep nesting and arrays",
      "Validates the JSON first",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Why would I quote every string?",
        a: "Unquoted YAML values like yes, no, on and off are read as booleans, and 1.10 becomes a number. Forcing quotes avoids those surprises.",
      },
      {
        q: "Is YAML always shorter?",
        a: "Usually, because it drops braces and quotes. It is also far more sensitive to indentation mistakes.",
      },
    ],
  },
  {
    id: "html-encoder",
    name: "HTML Encoder",
    short: "Escape characters so markup displays as text.",
    long: "Converts &, <, >, quotes and optionally every non-ASCII character into HTML entities, so code samples and user text display literally instead of being interpreted as markup.",
    category: "developer",
    route: "/tools/html-encoder",
    keywords: ["html encoder", "escape html", "html entities", "encode html characters"],
    aliases: ["escape html", "html entity encoder"],
    icon: "🔏",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["html-decoder", "url-encoder", "base64", "json-escape"],
    seoTitle: "HTML Encoder — Escape HTML Entities Online Free | DO101",
    seoDescription: "Encode HTML special characters into entities so markup displays as text. Optional full non-ASCII encoding. Free and browser-based.",
    steps: [
      "Paste your text or markup.",
      "Choose whether to encode non-ASCII characters too.",
      "Copy the encoded output.",
    ],
    features: [
      "Escapes &, <, >, \" and '",
      "Optional numeric entities for every non-ASCII character",
      "Safe for code samples",
      "One-tap copy",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Is this enough to prevent XSS?",
        a: "No. Entity encoding is one part of output escaping, but safe rendering depends on context — attributes, URLs and script blocks all need different treatment. Use your framework's escaping, not a copy-paste tool.",
      },
      {
        q: "Why encode non-ASCII characters?",
        a: "Only for legacy systems that mishandle UTF-8. Modern pages should declare UTF-8 and leave the characters alone.",
      },
    ],
  },
  {
    id: "html-decoder",
    name: "HTML Decoder",
    short: "Turn HTML entities back into readable characters.",
    long: "Converts &amp;, &lt;, &#39; and numeric entities back into the characters they represent — the fix for text that arrived double-encoded from a CMS or an API.",
    category: "developer",
    route: "/tools/html-decoder",
    keywords: ["html decoder", "decode html entities", "unescape html", "html entity decoder"],
    aliases: ["unescape html", "decode entities"],
    icon: "🔓",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["html-encoder", "url-decoder", "base64", "text-cleaner"],
    seoTitle: "HTML Decoder — Decode HTML Entities Online Free | DO101",
    seoDescription: "Decode HTML entities back into plain characters, including named and numeric forms. Free online HTML entity decoder that runs in your browser.",
    steps: [
      "Paste the encoded text.",
      "Read the decoded output.",
      "Copy it.",
    ],
    features: [
      "Named entities such as &amp; and &mdash;",
      "Decimal and hexadecimal numeric entities",
      "Leaves unknown entities untouched rather than mangling them",
      "One-tap copy",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "What is double encoding?",
        a: "When already-encoded text is encoded again, &amp; becomes &amp;amp;. Run the decoder twice to get back to the original.",
      },
      {
        q: "Why is an entity left as-is?",
        a: "Unrecognised entities are preserved rather than guessed at, so nothing is silently corrupted.",
      },
    ],
  },
  {
    id: "css-minifier",
    name: "CSS Minifier",
    short: "Minify or beautify CSS.",
    long: "Strips comments and unnecessary whitespace to shrink a stylesheet, or reformats a minified one so you can read it. Deliberately conservative — selectors, values and rule order are never rewritten.",
    category: "developer",
    route: "/tools/css-minifier",
    keywords: ["css minifier", "minify css", "compress css", "beautify css", "css formatter"],
    aliases: ["compress css", "css beautifier"],
    icon: "🎨",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["html-minifier", "sql-formatter", "json-minifier", "color-converter"],
    seoTitle: "CSS Minifier & Beautifier — Free Online Tool | DO101",
    seoDescription: "Minify CSS to cut file size, or beautify minified CSS to read it. Conservative and safe — nothing is renamed or reordered. Free and private.",
    steps: [
      "Paste your CSS.",
      "Choose minify or beautify.",
      "Copy the result and check the size saving.",
    ],
    features: [
      "Removes comments and redundant whitespace",
      "Beautify mode for minified stylesheets",
      "Before and after sizes",
      "Never renames or reorders anything",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Is it safe on any stylesheet?",
        a: "It only changes whitespace and comments, so behaviour is preserved. It deliberately does not merge rules or shorten colours, because those transformations can change specificity or rendering.",
      },
      {
        q: "How much smaller will my CSS be?",
        a: "Typically 15–30% before gzip. Your server's compression then does most of the remaining work.",
      },
    ],
  },
  {
    id: "html-minifier",
    name: "HTML Minifier",
    short: "Shrink HTML by collapsing whitespace and comments.",
    long: "Removes comments and collapses whitespace between tags, while protecting the contents of pre, textarea, script and style blocks where whitespace is significant.",
    category: "developer",
    route: "/tools/html-minifier",
    keywords: ["html minifier", "minify html", "compress html", "reduce html size"],
    aliases: ["compress html", "shrink html"],
    icon: "📄",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["css-minifier", "html-encoder", "xml-formatter", "json-minifier"],
    seoTitle: "HTML Minifier — Compress HTML Online Free | DO101",
    seoDescription: "Minify HTML by removing comments and collapsing whitespace, while protecting pre, textarea, script and style blocks. Free and browser-based.",
    steps: [
      "Paste your HTML.",
      "Choose whether to strip comments.",
      "Copy the minified output.",
    ],
    features: [
      "Protects pre, textarea, script and style content",
      "Optional comment removal",
      "Keeps conditional comments intact",
      "Before and after sizes",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Will minifying break my layout?",
        a: "Whitespace between inline elements can be meaningful, so check the result if your layout depends on it. Block-level markup is safe.",
      },
      {
        q: "Are conditional comments preserved?",
        a: "Yes. Comments beginning with <!--[if are left alone.",
      },
    ],
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    short: "Format SQL into readable clauses, or minify it.",
    long: "Puts each clause on its own line, indents conditions and joins, and optionally uppercases keywords — turning a one-line query into something you can actually review.",
    category: "developer",
    route: "/tools/sql-formatter",
    keywords: ["sql formatter", "format sql", "beautify sql", "sql beautifier", "minify sql"],
    aliases: ["pretty print sql", "sql beautifier"],
    icon: "🗄️",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-formatter", "css-minifier", "csv-to-json", "regex-tester"],
    seoTitle: "SQL Formatter — Beautify & Minify SQL Online Free | DO101",
    seoDescription: "Format SQL queries into readable clauses with keyword uppercasing, or minify them to one line. Free and running entirely in your browser.",
    steps: [
      "Paste your SQL.",
      "Choose format or minify.",
      "Copy the result.",
    ],
    features: [
      "Clause-aware line breaks",
      "Indented AND, OR and ON conditions",
      "Optional keyword uppercasing",
      "Minify mode that strips comments",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Which SQL dialects work?",
        a: "The formatter is keyword-based, so standard SELECT, INSERT, UPDATE, DELETE and DDL statements format well across MySQL, PostgreSQL, SQLite and SQL Server. Very dialect-specific syntax may format less tidily.",
      },
      {
        q: "Does it validate my SQL?",
        a: "No. It reformats text and never executes or parses the query semantically, so it cannot tell you whether the statement is correct.",
      },
      {
        q: "Is my query sent anywhere?",
        a: "No. Queries often contain table and column names you would rather not share, so this runs entirely on your device.",
      },
    ],
  },
  {
    id: "color-converter",
    name: "Color Converter",
    short: "Convert between HEX, RGB, HSL and CMYK — with contrast checks.",
    long: "Type a colour in any notation and get every other format back, plus a live swatch and WCAG contrast ratios against black and white so you can tell immediately whether text will be readable on it.",
    category: "developer",
    route: "/tools/color-converter",
    keywords: ["color converter", "hex to rgb", "rgb to hex", "hsl converter", "cmyk converter", "color picker", "contrast checker"],
    aliases: ["hex to rgb", "rgb to hex", "convert colour", "colour converter"],
    icon: "🎨",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["css-minifier", "image-converter", "html-encoder", "json-formatter"],
    seoTitle: "Color Converter — HEX, RGB, HSL & CMYK + Contrast | DO101",
    seoDescription: "Convert colours between HEX, RGB, HSL and CMYK, with a live swatch and WCAG contrast ratios against black and white. Free and browser-based.",
    steps: [
      "Type a colour in any format, or use the picker.",
      "Read every other format below.",
      "Check the contrast ratios before using it for text.",
    ],
    features: [
      "HEX, RGB, RGBA, HSL, HSLA and CMYK",
      "Accepts 3, 4, 6 and 8-digit hex plus CSS colour names",
      "Live swatch preview",
      "WCAG AA contrast ratios on black and white",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Which formats can I paste in?",
        a: "Hex in 3, 4, 6 or 8 digits, rgb() and rgba(), hsl() and hsla(), and common CSS colour names like tomato or crimson.",
      },
      {
        q: "What do the contrast numbers mean?",
        a: "WCAG asks for at least 4.5:1 for normal text and 3:1 for large text. The tool marks each ratio so you can tell at a glance whether the colour is usable for text.",
      },
      {
        q: "Why is CMYK only approximate?",
        a: "CMYK is device-dependent — real print colour needs an ICC profile. The values here use the standard naive conversion, which is fine for rough guidance but not for print production.",
      },
    ],
  },
];
