import type { Tool } from "../types";

/**
 * Games. Scores are stored on the visitor's own device, never a leaderboard.
 */
export const GAMES_TOOLS: Tool[] = [
  {
    id: "typing-test",
    name: "Typing Speed Test",
    short: "Measure your WPM and accuracy in 15, 30 or 60 seconds.",
    long:
      "A clean, distraction-free typing test. Choose a duration, start typing, and watch your speed and accuracy update live. Your best score is saved on your device so you can chase it, and the result is easy to share.",
    category: "game",
    route: "/games/typing-test",
    keywords: ["typing test", "typing speed test", "wpm test", "words per minute", "how fast can i type", "typing practice"],
    aliases: ["wpm test", "test my typing speed", "speed typing"],
    icon: "⌨️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "keyboard",
    output: "numbers",
    related: ["typing-battle", "reaction-test", "memory-test", "word-counter"],
    seoTitle: "Free Typing Speed Test — Check Your WPM in 60 Seconds | DO101",
    seoDescription:
      "Test your typing speed and accuracy in 15, 30 or 60 seconds. Live WPM, accuracy and error counts, personal best saved locally, results easy to share.",
    steps: ["Pick 15, 30 or 60 seconds.", "Start typing the text — the timer starts on your first keystroke.", "Read your WPM, accuracy and errors, then share or retry."],
    features: [
      "15, 30 and 60 second modes",
      "Live WPM, CPM and accuracy",
      "Per-character correctness highlighting",
      "Personal best stored on your device",
      "Shareable result card",
    ],
    faqs: [
      { q: "How is WPM calculated?", a: "The standard formula: every five correct characters counts as one word, divided by the elapsed minutes. DO101 shows both net WPM (correct characters only) and raw CPM." },
      { q: "What is a good typing speed?", a: "Around 40 WPM is average for adults, 60–70 WPM is fast, and above 100 WPM is genuinely rare. Accuracy above 95% matters more than raw speed for real work." },
      { q: "Do I need an account?", a: "No. Your best score is saved in your own browser with localStorage and never sent to DO101." },
    ],
    featured: true,
  },
  {
    id: "typing-battle",
    name: "Typing Battle",
    short: "Race a friend on the same text, live, from a shared link.",
    long:
      "Create a room, send the link to a friend, and race through identical text with both progress bars moving in real time. The connection is peer-to-peer over WebRTC, so there is no server holding your keystrokes.",
    category: "game",
    route: "/games/typing-battle",
    keywords: ["typing battle", "typing race", "multiplayer typing test", "typing game with friends", "1v1 typing"],
    aliases: ["typing race", "type against friend", "typing 1v1"],
    icon: "⚔️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "keyboard",
    output: "numbers",
    related: ["typing-test", "reaction-test", "memory-test", "word-counter"],
    seoTitle: "Typing Battle — Free 1v1 Multiplayer Typing Race | DO101",
    seoDescription:
      "Challenge a friend to a live typing race. Share a room link, race the same text, and watch both progress bars in real time. Free, no sign-up.",
    steps: ["Create a room and copy the link.", "Send it to a friend and wait for them to join.", "Race the same text and see who finishes first."],
    features: [
      "Real peer-to-peer connection over WebRTC",
      "Live opponent progress and WPM",
      "Synchronised countdown and identical text",
      "Rematch without creating a new room",
      "Honest connection states — never a fake opponent",
    ],
    faqs: [
      { q: "Is this real multiplayer?", a: "Yes. Both browsers connect directly to each other over WebRTC using a public signalling broker to exchange addresses. DO101 never simulates an opponent — if nobody joins, the screen says so." },
      { q: "Why did the connection fail?", a: "Strict corporate firewalls and some mobile networks block peer-to-peer traffic. DO101 shows a clear failure state with a retry, rather than pretending you are connected." },
      { q: "How long does a room last?", a: "A room exists only while the host's tab is open. Close it and the room is gone — there is no database keeping it alive." },
    ],
    featured: true,
  },
  {
    id: "reaction-test",
    name: "Reaction Time Test",
    short: "How fast are your reflexes? Measure it in milliseconds.",
    long:
      "Wait for green, then click as fast as you can. DO101 measures your reaction time with high-resolution browser timing across five rounds and gives you an average you can compare and share.",
    category: "game",
    route: "/games/reaction-test",
    keywords: ["reaction time test", "reflex test", "reaction speed", "click speed test", "average reaction time"],
    aliases: ["reflex test", "how fast are my reflexes", "reaction speed test"],
    icon: "⚡",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["typing-test", "memory-test", "typing-battle", "age"],
    seoTitle: "Reaction Time Test — Measure Your Reflexes in ms | DO101",
    seoDescription:
      "Test your reaction time in milliseconds across five rounds using high-resolution browser timing. Free, no sign-up, share your average.",
    steps: ["Press start and wait for the screen to turn green.", "Click, tap or hit space the instant it changes.", "Repeat five times for your average."],
    features: ["Five rounds with a running average", "High-resolution performance timing", "Too-soon detection", "Personal best saved locally", "Works with mouse, touch or keyboard"],
    faqs: [
      { q: "What is a good reaction time?", a: "Around 250 ms is typical for a visual click reaction. Under 200 ms is fast. Anything below about 100 ms usually means you anticipated the change rather than reacted to it." },
      { q: "Does my screen affect the result?", a: "Yes. Display latency and refresh rate add a few milliseconds, so compare your scores against your own history rather than against other setups." },
    ],
  },
  {
    id: "memory-test",
    name: "Memory Test",
    short: "Repeat a growing sequence. How many can you hold?",
    long:
      "A progressive sequence-memory game. Watch the pattern light up, repeat it, and each round adds one more step. Simple to learn, surprisingly hard to beat.",
    category: "game",
    route: "/games/memory-test",
    keywords: ["memory test", "sequence memory", "memory game", "brain training", "short term memory test"],
    aliases: ["sequence game", "memory game", "brain test"],
    icon: "🧠",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["reaction-test", "typing-test", "typing-battle", "percentage"],
    seoTitle: "Memory Test — Free Sequence Memory Game | DO101",
    seoDescription:
      "Play a progressive sequence memory game in your browser. Each level adds one step — see how far you can get. Free, no sign-up, share your level.",
    steps: ["Press start and watch the sequence.", "Tap the tiles back in the same order.", "Each level adds one more step."],
    features: ["Progressive difficulty", "Keyboard and touch friendly", "Best level saved on your device", "Sound-free by design", "Shareable result"],
    faqs: [
      { q: "What is an average score?", a: "Most people manage between 7 and 9 steps, which matches the classic research on short-term memory span. Chunking the sequence helps you go further." },
      { q: "Is my score sent anywhere?", a: "No. Your best level lives in your browser's local storage only." },
    ],
  },
  {
    id: "aim-trainer",
    name: "Aim Trainer",
    short: "Hit 30 targets as fast as you can.",
    long: "A clean click-accuracy test: a target appears, you hit it, the next one appears instantly. Your score is the average milliseconds per target across thirty of them, with accuracy tracked separately so a wild click costs you something.",
    category: "game",
    route: "/games/aim-trainer",
    keywords: ["aim trainer", "click accuracy test", "mouse accuracy", "aim practice", "target click game", "fps aim trainer"],
    aliases: ["mouse aim test", "target practice game", "click accuracy"],
    icon: "🎯",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["reaction-test", "click-speed-test", "typing-test", "chimp-test"],
    seoTitle: "Aim Trainer — Free Mouse Accuracy Test | DO101",
    seoDescription: "Test your aim and mouse accuracy: hit 30 targets and see your average time per target. Free, no sign-up, works on mouse and touch.",
    steps: [
      "Press start — the first target appears immediately.",
      "Hit each target as fast as you can.",
      "Read your average time per target and share it.",
    ],
    features: [
      "30 targets per run",
      "Average and fastest time per target",
      "Accuracy tracked separately from speed",
      "Works with a mouse, trackpad or finger",
      "Personal best saved on your device",
    ],
    faqs: [
      {
        q: "What is a good time per target?",
        a: "Around 700 ms is typical with a mouse. Under 500 ms is quick, and consistently under 400 ms is very good. Trackpads are naturally slower than mice, so compare against your own history.",
      },
      {
        q: "Do misses affect my score?",
        a: "Not your time — only your accuracy percentage. The clock for each target runs from when it appears to when you hit it.",
      },
      {
        q: "Does it work on a phone?",
        a: "Yes. Tapping is measured the same way, though thumbs are generally slower than a mouse.",
      },
    ],
    featured: true,
  },
  {
    id: "click-speed-test",
    name: "Click Speed Test",
    short: "How many clicks per second can you manage?",
    long: "The classic CPS test in 5, 10 or 30 second rounds. The clock starts on your first click rather than when the page loads, so you can get comfortable before the timer runs.",
    category: "game",
    route: "/games/click-speed-test",
    keywords: ["click speed test", "cps test", "clicks per second", "click test", "how fast can i click", "jitter click test"],
    aliases: ["cps test", "clicks per second test", "click counter game"],
    icon: "🖱️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["aim-trainer", "reaction-test", "typing-test", "math-sprint"],
    seoTitle: "Click Speed Test — Free CPS Test in 5, 10 or 30s | DO101",
    seoDescription: "Measure your clicks per second with a free CPS test. Choose 5, 10 or 30 seconds; the timer starts on your first click. No sign-up.",
    steps: [
      "Choose a test length.",
      "Click or tap the panel as fast as you can.",
      "Your clicks per second appear when time runs out.",
    ],
    features: [
      "5, 10 and 30 second rounds",
      "Timer starts on your first click",
      "Live clicks-per-second readout",
      "Works with mouse, trackpad, touch and the space bar",
      "Personal best saved locally",
    ],
    faqs: [
      {
        q: "What is an average click speed?",
        a: "Most people manage 5 to 7 clicks per second. Above 8 is fast, and above 10 usually means a special technique such as jitter or butterfly clicking.",
      },
      {
        q: "Why does the timer not start immediately?",
        a: "Because a countdown you cannot control measures your reaction time, not your clicking. Starting on the first click means the whole window is yours.",
      },
      {
        q: "Does clicking faster damage my mouse?",
        a: "Sustained rapid clicking does wear a switch over time. It is a game — do not injure your hand or your hardware for a number.",
      },
    ],
    featured: true,
  },
  {
    id: "number-memory",
    name: "Number Memory",
    short: "A number flashes up. Type it back.",
    long: "Each level adds one more digit to remember. Most people stop somewhere around seven, which is the classic figure for how much short-term memory holds at once — chunking the digits into pairs is the trick that pushes you past it.",
    category: "game",
    route: "/games/number-memory",
    keywords: ["number memory test", "digit span test", "memory test numbers", "short term memory test", "remember numbers game"],
    aliases: ["digit span", "number recall test", "memory span test"],
    icon: "🔢",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["visual-memory", "memory-test", "chimp-test", "word-scramble"],
    seoTitle: "Number Memory Test — How Many Digits Can You Recall? | DO101",
    seoDescription: "Test your short-term memory: a number flashes up and you type it back, gaining a digit each level. Free, no sign-up, score saved locally.",
    steps: [
      "Watch the number while the bar runs down.",
      "Type it back exactly.",
      "Each correct answer adds another digit.",
    ],
    features: [
      "One extra digit per level",
      "Display time grows with the number",
      "Shows the number you missed",
      "Average person reaches about 7 digits",
      "Personal best saved on your device",
    ],
    faqs: [
      {
        q: "How many digits can most people remember?",
        a: "About seven, which matches the well-known research on short-term memory span. Anything above ten is genuinely unusual without a memorisation technique.",
      },
      {
        q: "Any tips for going further?",
        a: "Chunk. Reading 4 8 2 9 3 1 as \"48 29 31\" turns six items into three, and three is easy. Saying them aloud helps too.",
      },
      {
        q: "Is my score sent anywhere?",
        a: "No. Your best is stored in your own browser and never leaves the device.",
      },
    ],
    featured: true,
  },
  {
    id: "visual-memory",
    name: "Visual Memory",
    short: "Squares flash on a grid. Tap them all back.",
    long: "Every level adds another square to remember, and the grid itself grows every third level, so the difficulty climbs in two directions. You get three wrong taps before the run ends.",
    category: "game",
    route: "/games/visual-memory",
    keywords: ["visual memory test", "memory grid game", "pattern memory", "spatial memory test", "remember the squares"],
    aliases: ["grid memory game", "pattern recall test", "spatial memory"],
    icon: "🧩",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["memory-test", "number-memory", "chimp-test", "color-vision"],
    seoTitle: "Visual Memory Test — Free Pattern Memory Game | DO101",
    seoDescription: "Memorise a flashing grid pattern and tap it back. The grid grows as you progress. Free, no sign-up, personal best saved locally.",
    steps: [
      "Watch which squares light up.",
      "Tap every one of them back.",
      "Each level adds a square; three mistakes ends the run.",
    ],
    features: [
      "Pattern grows every level",
      "Grid grows every third level",
      "Three lives per run",
      "Large touch targets on mobile",
      "Personal best saved on your device",
    ],
    faqs: [
      {
        q: "What is a good level to reach?",
        a: "Most people get to around level 9. Reaching the mid-teens is strong, since by then the grid is large and the pattern is long.",
      },
      {
        q: "How is this different from the sequence Memory Test?",
        a: "This one shows every square at once and asks for the set, testing spatial memory. The Memory Test shows a sequence and asks for the order, testing serial recall. They are genuinely different skills.",
      },
      {
        q: "Does the order I tap matter?",
        a: "No. Only which squares you tap.",
      },
    ],
  },
  {
    id: "chimp-test",
    name: "Chimp Test",
    short: "Click the numbers in order — after they vanish.",
    long: "Numbers appear scattered on a grid. The moment you click the first one they all disappear, and you have to click the rest from memory. Based on the Kyoto University experiments in which young chimpanzees reliably outperformed human adults.",
    category: "game",
    route: "/games/chimp-test",
    keywords: ["chimp test", "chimpanzee memory test", "working memory game", "number sequence memory", "ayumu test"],
    aliases: ["chimpanzee test", "monkey memory game", "working memory test"],
    icon: "🐒",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["visual-memory", "number-memory", "memory-test", "aim-trainer"],
    seoTitle: "Chimp Test — Can You Beat a Chimpanzee's Memory? | DO101",
    seoDescription: "Click numbers in order after they vanish, in the working-memory test where chimpanzees beat humans. Free, no sign-up, best score saved locally.",
    steps: [
      "Look at where the numbers are.",
      "Click 1 — every number then disappears.",
      "Click the rest from memory, in order.",
    ],
    features: [
      "Starts at four numbers and grows",
      "Numbers hide the moment you start",
      "Three lives per run",
      "Based on a real published experiment",
      "Personal best saved on your device",
    ],
    faqs: [
      {
        q: "Do chimpanzees really beat humans at this?",
        a: "At this specific task, yes. Researchers at Kyoto University found young chimpanzees, particularly one named Ayumu, could recall briefly-shown numeral positions more accurately than human adults. It is a narrow result about rapid spatial working memory, not general intelligence.",
      },
      {
        q: "What score is good?",
        a: "Reaching 10 is respectable and 15 is strong. The jump gets steep fast because the numbers are scattered rather than in a line.",
      },
      {
        q: "Why do the numbers disappear?",
        a: "That is the test. Reading them off the screen would measure your clicking speed, not your memory.",
      },
    ],
  },
  {
    id: "color-match",
    name: "Colour Match",
    short: "Does the word match the colour it is printed in?",
    long: "A Stroop test in 45 seconds. Reading is automatic, so telling whether the word RED is printed in red means actively suppressing the word to see the ink — which is much harder at speed than it sounds.",
    category: "game",
    route: "/games/color-match",
    keywords: ["stroop test", "color match game", "brain test colors", "cognitive test online", "color word test"],
    aliases: ["stroop effect test", "colour word game", "brain training colors"],
    icon: "🎨",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["color-vision", "reaction-test", "math-sprint", "typing-test"],
    seoTitle: "Colour Match — Free Stroop Test Online | DO101",
    seoDescription: "Take a 45-second Stroop test: decide whether each word matches the colour it is printed in. Measures focus and processing speed. Free, no sign-up.",
    steps: [
      "Read the word and look at its colour.",
      "Answer match or no match as fast as you can.",
      "Arrow keys work: left for match, right for no match.",
    ],
    features: [
      "45 seconds of rapid rounds",
      "Half the rounds match, so guessing does not help",
      "Accuracy and average answer time",
      "Keyboard or touch",
      "Personal best saved locally",
    ],
    faqs: [
      {
        q: "What is the Stroop effect?",
        a: "Naming the ink colour of a mismatched colour word is measurably slower than a matching one, because reading is so automatic it interferes. It has been a standard measure of attention and cognitive control since 1935.",
      },
      {
        q: "Why exactly half the rounds match?",
        a: "So that always answering the same way scores no better than chance. Any score above about half reflects real performance.",
      },
      {
        q: "What is a good score?",
        a: "Around 30 correct is typical. Above 45 is quick, and beyond 60 means you are answering in well under a second every time.",
      },
    ],
  },
  {
    id: "color-vision",
    name: "Colour Vision Test",
    short: "Spot the tile that is a slightly different shade.",
    long: "One tile in the grid is a fractionally different shade. Each level shrinks the difference and grows the grid, ending near the limit of what a typical screen can even display. Three misses and the run is over.",
    category: "game",
    route: "/games/color-vision",
    keywords: ["color vision test", "find the different color", "color blindness game", "shade difference test", "color acuity"],
    aliases: ["odd colour out", "spot the different shade", "colour perception test"],
    icon: "👁️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["color-match", "visual-memory", "reaction-test", "memory-test"],
    seoTitle: "Colour Vision Test — Spot the Different Shade | DO101",
    seoDescription: "Find the tile with a slightly different shade as the grid grows and the difference shrinks. A fun test of colour discrimination. Free, no sign-up.",
    steps: [
      "Look for the tile that is not quite the same.",
      "Tap it to advance a level.",
      "Three misses ends the run.",
    ],
    features: [
      "Grid grows and difference shrinks each level",
      "Random hue every round",
      "Three lives per run",
      "Works on any screen",
      "Personal best saved on your device",
    ],
    faqs: [
      {
        q: "Is this a colour blindness test?",
        a: "No, and it should not be used as one. It measures how small a difference in lightness you can spot on your screen right now. A real colour vision assessment uses calibrated plates and belongs with an optometrist.",
      },
      {
        q: "Why do I score differently on different devices?",
        a: "Screen brightness, contrast settings, colour profile and ambient light all change how small a difference is visible. Compare against your own past scores, not someone else's.",
      },
      {
        q: "What is a good level?",
        a: "Reaching the high teens is strong. Beyond about level 25 the difference is a couple of steps of lightness, which many displays cannot render distinctly at all.",
      },
    ],
  },
  {
    id: "math-sprint",
    name: "Maths Sprint",
    short: "Solve as many problems as you can in 60 seconds.",
    long: "Starts with addition and subtraction, then brings in multiplication and division as your streak grows. Every division is built from a known product, so the answer is always a whole number.",
    category: "game",
    route: "/games/math-sprint",
    keywords: ["math game", "mental math practice", "quick maths test", "arithmetic game", "math sprint", "times tables practice"],
    aliases: ["mental arithmetic game", "quick maths", "math practice online"],
    icon: "➗",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["word-scramble", "color-match", "typing-test", "click-speed-test"],
    seoTitle: "Maths Sprint — Free Mental Arithmetic Game | DO101",
    seoDescription: "Solve as many arithmetic problems as you can in 60 seconds, with difficulty rising as your streak grows. Free mental maths practice, no sign-up.",
    steps: [
      "Press start and read the first problem.",
      "Type the answer and press Enter.",
      "Keep going for 60 seconds.",
    ],
    features: [
      "Difficulty rises with your streak",
      "Divisions always give a whole number",
      "Accuracy tracked alongside speed",
      "Numeric keypad on mobile",
      "Personal best saved locally",
    ],
    faqs: [
      {
        q: "How does the difficulty work?",
        a: "The first few problems are addition and subtraction with small numbers. Multiplication appears after about five correct answers and division after ten, with the numbers growing as you go.",
      },
      {
        q: "Are the divisions always exact?",
        a: "Yes. Each one is generated from a divisor and a quotient and then multiplied out, so there is never a remainder or a decimal.",
      },
      {
        q: "What is a good score?",
        a: "Above 20 is solid, above 32 is quick, and beyond 45 means you are answering in barely a second each.",
      },
    ],
  },
  {
    id: "word-scramble",
    name: "Word Scramble",
    short: "Unscramble as many words as you can in 90 seconds.",
    long: "Every word is six letters, shuffled so the result is never the original. Skipping is free and usually faster than staring at a hard one, but the count is shown at the end.",
    category: "game",
    route: "/games/word-scramble",
    keywords: ["word scramble", "anagram game", "unscramble words", "word game online", "vocabulary game"],
    aliases: ["anagram solver game", "jumbled words game", "unscramble game"],
    icon: "🔤",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["math-sprint", "typing-test", "word-counter", "color-match"],
    seoTitle: "Word Scramble — Free Anagram Game Online | DO101",
    seoDescription: "Unscramble as many six-letter words as you can in 90 seconds. Free word game with no sign-up, score saved on your device.",
    steps: [
      "Read the scrambled letters.",
      "Type the real word and press Enter.",
      "Skip anything that is taking too long.",
    ],
    features: [
      "90 seconds per round",
      "Every word is six letters",
      "Scrambles are guaranteed to differ from the answer",
      "Skips are free but counted",
      "Personal best saved locally",
    ],
    faqs: [
      {
        q: "Are the scrambles ever the same as the word?",
        a: "No. The shuffle is repeated until the result differs, so a puzzle is never accidentally already solved.",
      },
      {
        q: "Should I skip?",
        a: "Usually. Ten seconds on one word costs more than three quick ones, and the skip count is only shown for context — it does not reduce your score.",
      },
      {
        q: "How many words are there?",
        a: "Around seventy common six-letter words, drawn at random, so a round rarely repeats itself.",
      },
    ],
  },
  {
    id: "2048",
    name: "2048",
    short: "Slide the tiles, merge the numbers, reach 2048.",
    long: "The full sliding-tile puzzle: arrow keys, WASD, swipe or on-screen buttons. A tile that has just merged cannot merge again in the same move, which is the rule that makes the endgame genuinely hard.",
    category: "game",
    route: "/games/2048",
    keywords: ["2048 game", "2048 online", "play 2048 free", "sliding tile puzzle", "number puzzle game"],
    aliases: ["2048 puzzle", "tile merging game", "play 2048"],
    icon: "🔢",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["memory-test", "visual-memory", "math-sprint", "chimp-test"],
    seoTitle: "2048 — Play the Free Sliding Tile Puzzle Online | DO101",
    seoDescription: "Play 2048 free in your browser: arrow keys, WASD or swipe. Merge tiles to reach 2048 and beyond. No ads over the board, no sign-up.",
    steps: [
      "Slide with arrow keys, WASD or a swipe.",
      "Equal numbers merge when they collide.",
      "Keep going after 2048 for a higher score.",
    ],
    features: [
      "Keyboard, swipe and on-screen controls",
      "Score and highest tile tracked live",
      "Carry on playing after reaching 2048",
      "Correct merge rules — no double merges",
      "Personal best saved on your device",
    ],
    faqs: [
      {
        q: "Can a tile merge twice in one move?",
        a: "No, and that rule matters. A row of 2 2 4 slid left becomes 4 4, not 8. Implementations that get this wrong make the game far too easy.",
      },
      {
        q: "How do I actually reach 2048?",
        a: "Keep your largest tile in one corner and never move in the direction that would pull it out. Build your biggest row along that edge and work the rest around it.",
      },
      {
        q: "Does the game end at 2048?",
        a: "Only if you want it to. You are offered the choice to stop or keep merging for a higher score.",
      },
    ],
    featured: true,
  },
];
