import type { Tool } from "../types";

/**
 * Image tools. Everything runs through the browser canvas — there is no
 * upload endpoint behind any of them.
 */
export const IMAGE_TOOLS: Tool[] = [
  {
    id: "image-compressor",
    name: "Image Compressor",
    short: "Shrink JPG, PNG or WebP files without leaving your browser.",
    long:
      "Compress images down to a size that actually fits an upload limit. Pick a quality level or type a target size in kilobytes and DO101 searches for the best quality that still fits. Everything runs on your device using the browser's own canvas encoder, so the picture is never uploaded.",
    category: "image",
    route: "/tools/image-compressor",
    keywords: ["compress image", "image compressor", "reduce image size", "compress jpg", "compress png", "compress photo", "under 200kb", "shrink image"],
    aliases: ["compress photo", "make image smaller", "reduce photo size", "photo compressor"],
    icon: "🗜️",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["image-resizer", "jpg-to-png", "png-to-jpg", "qr-generator"],
    seoTitle: "Free Image Compressor — Compress JPG & PNG Online | DO101",
    seoDescription:
      "Compress JPG, PNG and WebP images in your browser. Choose a quality level or a target size in KB. No upload, no watermark, no sign-up.",
    steps: [
      "Drop an image onto the box, or tap it to pick a file.",
      "Choose a quality level, or switch to target size and type a limit in KB.",
      "Watch the before/after sizes update, then download the compressed image.",
    ],
    features: [
      "Quality slider with live before/after file sizes",
      "Target-size mode that searches for the best quality under your limit",
      "Batch mode: compress several images in one pass",
      "Keeps JPG, PNG and WebP output options",
      "100% in-browser — the file never leaves your device",
    ],
    faqs: [
      { q: "Are my images uploaded to a server?", a: "No. Compression happens with the browser's canvas encoder on your own device. DO101 has no upload endpoint for this tool, so the file never leaves your computer or phone." },
      { q: "How do I compress an image under 200 KB?", a: "Switch to target size mode, type 200 and press compress. DO101 repeatedly re-encodes at different quality levels and keeps the best-looking result that still fits under 200 KB." },
      { q: "Does compression reduce quality?", a: "JPG and WebP compression is lossy, so very low quality values will show artefacts. Most photos look identical at 70–80% quality while losing more than half their file size." },
      { q: "Which formats are supported?", a: "JPG/JPEG, PNG and WebP inputs. You can also export to a different format than the input, which is often the biggest saving of all." },
    ],
    featured: true,
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    short: "Resize pictures to exact pixel dimensions or a percentage.",
    long:
      "Set a width, a height, or a percentage and DO101 resizes the image on your device. Lock the aspect ratio to avoid stretching, or unlock it when you need an exact canvas size. Nothing is uploaded.",
    category: "image",
    route: "/tools/image-resizer",
    keywords: ["image resizer", "resize image", "resize photo", "change image dimensions", "scale image", "resize jpg", "resize png"],
    aliases: ["make image smaller dimensions", "scale photo", "change photo size"],
    icon: "📐",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["image-compressor", "jpg-to-png", "png-to-jpg", "qr-generator"],
    seoTitle: "Free Image Resizer — Resize JPG & PNG by Pixels | DO101",
    seoDescription:
      "Resize images online by width, height or percentage with aspect-ratio lock. Runs entirely in your browser — no upload and no sign-up.",
    steps: [
      "Add an image from your device.",
      "Type a new width or height, or drag the percentage scale.",
      "Keep the ratio locked to avoid distortion, then download.",
    ],
    features: [
      "Resize by pixels or percentage",
      "Aspect-ratio lock",
      "Shows original and output dimensions side by side",
      "Export as JPG, PNG or WebP",
      "Runs offline once the page has loaded",
    ],
    faqs: [
      { q: "Will resizing blur my image?", a: "Scaling down stays sharp. Scaling far above the original size cannot invent detail, so enlargements will look soft — that is true of every resizer." },
      { q: "Can I resize several images at once?", a: "Yes. Add multiple files and the same dimensions are applied to each, then download them one by one." },
      { q: "Is the file uploaded?", a: "No. The resize happens in a canvas element inside your browser tab." },
    ],
    featured: true,
  },
  {
    id: "jpg-to-png",
    name: "JPG to PNG",
    short: "Convert JPG photos to lossless PNG files.",
    long:
      "Turn JPG or JPEG images into PNG, the format editors and design tools prefer for lossless work. Conversion runs in your browser, so large batches stay fast and private.",
    category: "image",
    route: "/tools/jpg-to-png",
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png", "image converter", "png converter"],
    aliases: ["jpeg to png", "change jpg to png"],
    icon: "🔄",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["png-to-jpg", "image-compressor", "image-resizer", "qr-generator"],
    seoTitle: "JPG to PNG Converter — Free & In-Browser | DO101",
    seoDescription:
      "Convert JPG and JPEG images to PNG online for free. Batch friendly, no watermark, no upload — conversion happens in your browser.",
    steps: ["Add one or more JPG files.", "Press convert.", "Download the PNG results."],
    features: ["Batch conversion", "Lossless PNG output", "No watermark or sign-up", "Works on phones and tablets", "Files stay on your device"],
    faqs: [
      { q: "Does converting JPG to PNG restore lost quality?", a: "No. A JPG has already discarded detail; PNG simply stops any further loss. Converting is useful for editing, transparency workflows and crisp screenshots." },
      { q: "Why is the PNG bigger than the JPG?", a: "PNG is lossless, so photographs usually grow. If you need a smaller file, use the Image Compressor instead." },
    ],
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG",
    short: "Convert PNG images to smaller JPG files.",
    long:
      "PNG screenshots are often several times larger than they need to be. Convert them to JPG with a quality you control, and pick the background colour used where the PNG was transparent.",
    category: "image",
    route: "/tools/png-to-jpg",
    keywords: ["png to jpg", "png to jpeg", "convert png to jpg", "image converter"],
    aliases: ["png to jpeg", "change png to jpg"],
    icon: "🔃",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["jpg-to-png", "image-compressor", "image-resizer", "qr-generator"],
    seoTitle: "PNG to JPG Converter — Free & In-Browser | DO101",
    seoDescription:
      "Convert PNG images to JPG online with an adjustable quality and background colour. Free, no upload, no watermark.",
    steps: ["Add one or more PNG files.", "Choose JPG quality and a background colour for transparent areas.", "Convert and download."],
    features: ["Quality control", "Choose the matte colour for transparency", "Batch conversion", "Big size savings on screenshots", "Processed in your browser"],
    faqs: [
      { q: "What happens to transparency?", a: "JPG has no alpha channel, so transparent pixels are filled with the background colour you choose — white by default." },
      { q: "How much smaller will the JPG be?", a: "Screenshots and photographs typically shrink by 60–90%. Flat graphics and logos may not shrink much and often look better left as PNG." },
    ],
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG",
    short: "Convert iPhone HEIC photos into JPGs anything can open.",
    long: "iPhones save photos as HEIC, which Windows, older Android phones and most upload forms refuse to open. This converts them to ordinary JPG using a WebAssembly build of libheif that runs inside your browser — your photos are never uploaded.",
    category: "image",
    route: "/tools/heic-to-jpg",
    keywords: ["heic to jpg", "heic to jpeg", "iphone photo to jpg", "convert heic", "heic converter", "open heic on windows"],
    aliases: ["iphone photo to jpg", "convert heic photos", "heic converter"],
    icon: "📱",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["heic-to-png", "image-compressor", "jpg-to-pdf", "image-converter"],
    seoTitle: "HEIC to JPG Converter — Free iPhone Photo Converter | DO101",
    seoDescription: "Convert iPhone HEIC and HEIF photos to JPG in your browser. Batch conversion, adjustable quality, no watermark and nothing is uploaded.",
    steps: [
      "Add your HEIC files — drop them in or tap to browse.",
      "Adjust quality if the format supports it.",
      "Convert and download the JPG results.",
    ],
    features: [
      "Batch conversion in one pass",
      "Before and after file sizes shown",
      "No watermark and no sign-up",
      "Works on phones and tablets",
      "Converted in your browser — files are never uploaded",
    ],
    faqs: [
      {
        q: "Why can't I open HEIC files?",
        a: "HEIC is Apple's high-efficiency format. It saves space on your iPhone but is not supported by most websites, Windows apps or older Android phones. Converting to JPG makes the photo universally readable.",
      },
      {
        q: "Does converting lose quality?",
        a: "Both HEIC and JPG are lossy, so re-encoding costs a little quality. At 90% or above the difference is invisible on screen — and the default here is deliberately high.",
      },
      {
        q: "Are my photos uploaded?",
        a: "No. The libheif decoder runs as WebAssembly inside this page, so the photo never leaves your device. That matters more for camera-roll photos than almost anything else.",
      },
      {
        q: "Can I stop my iPhone making HEIC files?",
        a: "Yes — Settings › Camera › Formats › Most Compatible makes it shoot JPG instead, at the cost of larger files.",
      },
    ],
    featured: true,
  },
  {
    id: "heic-to-png",
    name: "HEIC to PNG",
    short: "Convert iPhone HEIC photos to lossless PNG.",
    long: "Turns HEIC and HEIF photos into PNG, which is lossless and supported everywhere. Best when the picture will be edited further; choose JPG instead if you mainly want a smaller file.",
    category: "image",
    route: "/tools/heic-to-png",
    keywords: ["heic to png", "convert heic to png", "iphone photo to png", "heif to png"],
    aliases: ["heif to png", "iphone image to png"],
    icon: "🖼️",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["heic-to-jpg", "png-to-jpg", "image-compressor", "image-converter"],
    seoTitle: "HEIC to PNG Converter — Free & In-Browser | DO101",
    seoDescription: "Convert HEIC and HEIF photos from an iPhone into lossless PNG images. Batch friendly, free, and processed entirely in your browser.",
    steps: [
      "Add your HEIC files — drop them in or tap to browse.",
      "Adjust quality if the format supports it.",
      "Convert and download the PNG results.",
    ],
    features: [
      "Batch conversion in one pass",
      "Before and after file sizes shown",
      "No watermark and no sign-up",
      "Works on phones and tablets",
      "Converted in your browser — files are never uploaded",
    ],
    faqs: [
      {
        q: "Should I choose PNG or JPG?",
        a: "PNG is lossless, so it is the right choice if you will edit the image again. It also produces much larger files for photographs — for sharing or uploading, JPG is usually better.",
      },
      {
        q: "Is anything uploaded?",
        a: "No. Decoding and re-encoding both happen on your device.",
      },
    ],
  },
  {
    id: "jpg-to-webp",
    name: "JPG to WebP",
    short: "Convert JPGs to WebP and cut page weight substantially.",
    long: "WebP typically produces files 25–35% smaller than JPG at the same visible quality, and every current browser supports it. This is one of the cheapest performance wins available to a website.",
    category: "image",
    route: "/tools/jpg-to-webp",
    keywords: ["jpg to webp", "jpeg to webp", "convert jpg to webp", "webp converter", "compress for web"],
    aliases: ["jpeg to webp", "make webp images"],
    icon: "🌐",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["png-to-webp", "webp-to-jpg", "image-compressor", "image-converter"],
    seoTitle: "JPG to WebP Converter — Shrink Images for the Web | DO101",
    seoDescription: "Convert JPG images to WebP and cut file size by roughly a third at the same visible quality. Free, batch friendly, and nothing is uploaded.",
    steps: [
      "Add your JPG files — drop them in or tap to browse.",
      "Adjust quality if the format supports it.",
      "Convert and download the WebP results.",
    ],
    features: [
      "Batch conversion in one pass",
      "Before and after file sizes shown",
      "No watermark and no sign-up",
      "Works on phones and tablets",
      "Converted in your browser — files are never uploaded",
    ],
    faqs: [
      {
        q: "Is WebP safe to use now?",
        a: "Yes. Chrome, Edge, Firefox, Safari and every current mobile browser support it. Only very old browsers do not, and those are far below the threshold most sites care about.",
      },
      {
        q: "How much smaller will my images be?",
        a: "Usually 25–35% at matched quality, and often more for photographs. The tool shows the exact before and after sizes for each file.",
      },
      {
        q: "Will it look worse?",
        a: "At 80% quality the difference is generally invisible. Compare the sizes shown and drop the quality only as far as still looks right to you.",
      },
    ],
  },
  {
    id: "png-to-webp",
    name: "PNG to WebP",
    short: "Convert PNGs to WebP for much smaller files.",
    long: "WebP handles both lossless and lossy compression, so it beats PNG on size for screenshots, graphics and illustrations alike — frequently by half or more.",
    category: "image",
    route: "/tools/png-to-webp",
    keywords: ["png to webp", "convert png to webp", "webp from png", "smaller png"],
    aliases: ["make png smaller webp", "png web format"],
    icon: "🪶",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["jpg-to-webp", "webp-to-png", "image-compressor", "png-to-jpg"],
    seoTitle: "PNG to WebP Converter — Free Image Optimiser | DO101",
    seoDescription: "Convert PNG images to WebP and often halve the file size. Free, batch friendly, no watermark, and processed entirely in your browser.",
    steps: [
      "Add your PNG files — drop them in or tap to browse.",
      "Adjust quality if the format supports it.",
      "Convert and download the WebP results.",
    ],
    features: [
      "Batch conversion in one pass",
      "Before and after file sizes shown",
      "No watermark and no sign-up",
      "Works on phones and tablets",
      "Converted in your browser — files are never uploaded",
    ],
    faqs: [
      {
        q: "Does WebP support transparency?",
        a: "Yes. Unlike JPG, WebP keeps the alpha channel, so transparent PNGs convert cleanly.",
      },
      {
        q: "How much smaller is WebP than PNG?",
        a: "Screenshots and flat graphics commonly drop by 50–80%. The saving is shown per file so you can see it rather than take it on trust.",
      },
    ],
  },
  {
    id: "webp-to-jpg",
    name: "WebP to JPG",
    short: "Convert WebP images into JPGs older software can open.",
    long: "You downloaded an image from a website and it arrived as WebP, which your photo editor or upload form refuses. This converts it back to plain JPG in one step.",
    category: "image",
    route: "/tools/webp-to-jpg",
    keywords: ["webp to jpg", "webp to jpeg", "convert webp", "open webp file", "webp converter"],
    aliases: ["convert webp to jpeg", "webp won't open"],
    icon: "🔁",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["webp-to-png", "jpg-to-webp", "image-compressor", "image-converter"],
    seoTitle: "WebP to JPG Converter — Free & In-Browser | DO101",
    seoDescription: "Convert WebP images to JPG so older apps and upload forms accept them. Free, batch friendly, no watermark, and nothing is uploaded.",
    steps: [
      "Add your WebP files — drop them in or tap to browse.",
      "Adjust quality if the format supports it.",
      "Convert and download the JPG results.",
    ],
    features: [
      "Batch conversion in one pass",
      "Before and after file sizes shown",
      "No watermark and no sign-up",
      "Works on phones and tablets",
      "Converted in your browser — files are never uploaded",
    ],
    faqs: [
      {
        q: "Why won't my software open WebP?",
        a: "WebP is well supported in browsers but still missing from plenty of desktop editors, document tools and upload forms. Converting to JPG sidesteps all of that.",
      },
      {
        q: "What happens to transparency?",
        a: "JPG has no alpha channel, so transparent areas are filled with the background colour you choose — white by default.",
      },
    ],
  },
  {
    id: "webp-to-png",
    name: "WebP to PNG",
    short: "Convert WebP images to PNG and keep transparency.",
    long: "PNG is the safe universal choice when the image has transparent areas you need to preserve. This converts WebP to PNG losslessly.",
    category: "image",
    route: "/tools/webp-to-png",
    keywords: ["webp to png", "convert webp to png", "webp transparent to png"],
    aliases: ["webp to png transparent", "convert webp file"],
    icon: "🧊",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["webp-to-jpg", "png-to-webp", "image-compressor", "image-converter"],
    seoTitle: "WebP to PNG Converter — Keep Transparency, Free | DO101",
    seoDescription: "Convert WebP images to PNG while preserving transparency. Free, batch friendly, and processed entirely inside your browser.",
    steps: [
      "Add your WebP files — drop them in or tap to browse.",
      "Adjust quality if the format supports it.",
      "Convert and download the PNG results.",
    ],
    features: [
      "Batch conversion in one pass",
      "Before and after file sizes shown",
      "No watermark and no sign-up",
      "Works on phones and tablets",
      "Converted in your browser — files are never uploaded",
    ],
    faqs: [
      {
        q: "Is transparency preserved?",
        a: "Yes. Both formats support an alpha channel, so transparent areas survive the conversion intact.",
      },
      {
        q: "Will the PNG be larger?",
        a: "Almost certainly — PNG is lossless. That is the trade for universal support and perfect fidelity.",
      },
    ],
  },
  {
    id: "image-converter",
    name: "Image Converter",
    short: "Convert between JPG, PNG and WebP — any direction.",
    long: "One tool for every combination: drop in a mix of JPG, PNG, WebP, HEIC, GIF or BMP files, pick the output format, and convert them all at once.",
    category: "image",
    route: "/tools/image-converter",
    keywords: ["image converter", "convert image format", "change image format", "jpg png webp converter", "photo format converter"],
    aliases: ["change picture format", "convert any image"],
    icon: "🔄",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["heic-to-jpg", "jpg-to-webp", "image-compressor", "image-resizer"],
    seoTitle: "Free Image Converter — JPG, PNG, WebP & HEIC | DO101",
    seoDescription: "Convert images between JPG, PNG and WebP, including HEIC input. Batch conversion with quality control, free and entirely in your browser.",
    steps: [
      "Add your any image files — drop them in or tap to browse.",
      "Adjust quality if the format supports it.",
      "Convert and download the your chosen format results.",
    ],
    features: [
      "Batch conversion in one pass",
      "Before and after file sizes shown",
      "No watermark and no sign-up",
      "Works on phones and tablets",
      "Converted in your browser — files are never uploaded",
    ],
    faqs: [
      {
        q: "Which formats can I convert from?",
        a: "Anything your browser can decode — JPG, PNG, WebP, GIF, BMP, usually AVIF — plus HEIC, which is decoded by a WebAssembly build of libheif.",
      },
      {
        q: "Which format should I choose?",
        a: "JPG for photos that need universal support, PNG when you need transparency or lossless quality, WebP when file size matters most and the audience is on the web.",
      },
      {
        q: "Can I convert several formats at once?",
        a: "Yes. Mix input formats freely; they all convert to the single output format you pick.",
      },
    ],
    featured: true,
  },
  {
    id: "image-to-text",
    name: "Image to Text (OCR)",
    short: "Pull the words out of a photo or screenshot.",
    long: "Point it at a photo of a page, a screenshot, a receipt or a whiteboard and get copyable text back. Recognition runs on your device with Tesseract compiled to WebAssembly, in seventeen languages, with a confidence score so you know how much to trust the result.",
    category: "image",
    route: "/tools/image-to-text",
    keywords: ["image to text", "ocr online", "picture to text", "photo to text", "extract text from image", "screenshot to text"],
    aliases: ["ocr an image", "read text from photo", "copy text from screenshot"],
    icon: "🔍",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "text",
    related: ["pdf-ocr", "text-cleaner", "word-counter", "image-compressor"],
    seoTitle: "Image to Text — Free OCR in Your Browser | DO101",
    seoDescription: "Extract text from photos and screenshots with free OCR in 17 languages. Runs on your device with a confidence score — no upload, no sign-up.",
    steps: [
      "Choose the language of the text.",
      "Add a photo or screenshot.",
      "Copy the recognised text or download it as a .txt file.",
    ],
    features: [
      "17 languages",
      "Confidence score with a warning when it is low",
      "Works on photos, screenshots and scans",
      "Copy or download the result",
      "Recognition runs on your device",
    ],
    faqs: [
      {
        q: "Why is the first run slow?",
        a: "The OCR engine and language model — about 12 to 15 MB — download from a public CDN the first time. Your browser caches them, so every later run starts immediately.",
      },
      {
        q: "How do I get better accuracy?",
        a: "Photograph the page straight on with even lighting, fill the frame, avoid shadows, and pick the correct language. Those four things matter far more than the resolution.",
      },
      {
        q: "Can it read handwriting?",
        a: "Not reliably. Tesseract is built for printed text; handwriting recognition is a different problem and results will be poor.",
      },
      {
        q: "Is my image uploaded?",
        a: "No. Only the engine and language model are downloaded — your picture stays on your device.",
      },
    ],
    featured: true,
  },
];
