import type { Tool } from "../types";

/**
 * PDF tools. Every one runs through pdf-lib or pdf.js inside the visitor's
 * browser — there is no upload endpoint behind any of them.
 */
export const PDF_TOOLS: Tool[] = [
  {
    id: "pdf-merge",
    name: "Merge PDF",
    short: "Combine several PDFs into one, in the order you choose.",
    long: "Drop in as many PDFs as you need, drag them into the right order, and download a single combined document. The merge happens with pdf-lib inside your browser, so even a confidential contract never leaves your device.",
    category: "pdf",
    route: "/tools/pdf-merge",
    keywords: ["merge pdf", "combine pdf", "join pdf files", "pdf merger", "merge pdf online free", "put pdfs together"],
    aliases: ["combine pdfs", "join pdfs", "pdf merger", "stick pdfs together"],
    icon: "🧩",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-split", "pdf-compress", "pdf-reorder-pages", "image-to-pdf"],
    seoTitle: "Merge PDF — Combine PDF Files Free, No Upload | DO101",
    seoDescription: "Merge multiple PDF files into one document in your browser. Reorder before merging, no watermark, no sign-up, and your files are never uploaded.",
    steps: [
      "Add two or more PDFs.",
      "Use the arrows to put them in the right order.",
      "Press merge and download the combined PDF.",
    ],
    features: [
      "Unlimited files, merged in your chosen order",
      "Page counts shown before you merge",
      "No watermark and no page limit",
      "Original quality — pages are copied, not re-rendered",
      "Runs entirely in your browser",
    ],
    faqs: [
      {
        q: "Are my PDFs uploaded anywhere?",
        a: "No. Merging is done by pdf-lib running inside this page. There is no upload endpoint behind this tool, so the files physically cannot reach a server.",
      },
      {
        q: "Is there a limit on how many files I can merge?",
        a: "There is no fixed limit. The practical ceiling is your device's memory — a few hundred megabytes of PDFs is comfortable on a laptop, less on an older phone.",
      },
      {
        q: "Does merging reduce quality?",
        a: "No. Pages are copied across intact, so text stays selectable and images keep their original resolution.",
      },
      {
        q: "Can I merge password-protected PDFs?",
        a: "No. Encrypted PDFs cannot be opened in the browser. Remove the password in the app that created the file first.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-split",
    name: "Split PDF",
    short: "Break one PDF into separate files by page count or range.",
    long: "Split a long document into single pages, into fixed-size chunks, or into exactly the ranges you specify. Every part is produced locally and you can grab them one by one or as a single zip.",
    category: "pdf",
    route: "/tools/pdf-split",
    keywords: ["split pdf", "separate pdf pages", "divide pdf", "pdf splitter", "split pdf into pages", "cut pdf"],
    aliases: ["divide pdf", "separate pdf", "break up pdf", "pdf splitter"],
    icon: "✂️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-merge", "pdf-extract-pages", "pdf-delete-pages", "pdf-compress"],
    seoTitle: "Split PDF — Separate Pages Free & In-Browser | DO101",
    seoDescription: "Split a PDF into single pages, fixed chunks or custom ranges. Download individually or as a zip. Free, no watermark, and nothing is uploaded.",
    steps: [
      "Add the PDF you want to split.",
      "Choose every N pages, or type custom ranges like 1-3, 4-8.",
      "Download the parts individually or all together as a zip.",
    ],
    features: [
      "Split every page, every N pages, or by custom ranges",
      "Overlapping ranges are allowed",
      "Download all parts as one zip",
      "Original page quality preserved",
      "No upload — the split happens on your device",
    ],
    faqs: [
      {
        q: "What is the difference between the two split modes?",
        a: "\"Every N pages\" chops the document into equal chunks — useful for splitting a 100-page report into 10-page sections. \"Custom ranges\" lets you pull out exactly the sections you want, and those ranges may overlap.",
      },
      {
        q: "How do I extract just one section instead?",
        a: "Use the PDF Page Extractor, which keeps a chosen set of pages as a single new document rather than producing several files.",
      },
      {
        q: "Why is the download a zip?",
        a: "Splitting a 40-page PDF into single pages produces 40 files. Browsers block that many separate downloads, so DO101 bundles them into one zip built locally with fflate.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-compress",
    name: "Compress PDF",
    short: "Make a PDF smaller, with an honest choice about the trade-off.",
    long: "Two strategies, both explained before you commit. The safe one rewrites the file structure and keeps text selectable, with modest savings. The aggressive one re-renders each page as an image, which shrinks scans dramatically but destroys the text layer. DO101 tells you which one you are choosing and what it costs.",
    category: "pdf",
    route: "/tools/pdf-compress",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf", "pdf compressor", "make pdf smaller", "compress pdf under 1mb"],
    aliases: ["reduce pdf size", "shrink pdf", "make pdf smaller", "pdf size reducer"],
    icon: "🗜️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-split", "pdf-merge", "pdf-to-jpg", "image-compressor"],
    seoTitle: "Compress PDF — Reduce PDF File Size Free | DO101",
    seoDescription: "Compress a PDF in your browser with a clear choice: keep the text layer, or shrink hard by rasterising pages. No upload, no watermark, no sign-up.",
    steps: [
      "Add the PDF you want smaller.",
      "Choose \"keep text\" for a safe pass, or \"shrink hard\" for scans.",
      "Compare the before and after sizes, then download.",
    ],
    features: [
      "Two clearly explained strategies",
      "Before/after size and percentage saved",
      "Adjustable image quality and resolution",
      "Warns you when a file did not get smaller",
      "Compressed on your device — no upload",
    ],
    faqs: [
      {
        q: "Why did my PDF barely shrink?",
        a: "The safe mode only rewrites the file structure. If the PDF was already well built — most PDFs exported from modern software are — there is very little slack to recover. Scanned documents full of large images are where the aggressive mode wins.",
      },
      {
        q: "What exactly does \"shrink hard\" do to my file?",
        a: "It renders every page to a JPEG and rebuilds the PDF around those images. The result looks the same but is a picture of your document: text can no longer be selected, searched or copied. Always keep your original.",
      },
      {
        q: "Why do other sites compress more?",
        a: "Server-based tools can re-encode the individual images inside a PDF while leaving the text alone. That needs a full PDF object rewriter, which is not something a browser can do reliably today — so DO101 offers the two approaches it can genuinely deliver, and says so.",
      },
      {
        q: "Is my document uploaded?",
        a: "No. Both strategies run on your device.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    short: "Turn every page of a PDF into a JPG image.",
    long: "Render a PDF's pages as JPG images at the resolution you choose, from screen size up to 300 DPI for print. Pages are rasterised with pdf.js in a Web Worker, so even a long document stays responsive.",
    category: "pdf",
    route: "/tools/pdf-to-jpg",
    keywords: ["pdf to jpg", "pdf to jpeg", "convert pdf to image", "pdf to picture", "export pdf pages as images"],
    aliases: ["pdf to jpeg", "pdf to image", "pdf page to jpg"],
    icon: "🖼️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-to-png", "jpg-to-pdf", "pdf-to-text", "image-compressor"],
    seoTitle: "PDF to JPG — Convert PDF Pages to Images Free | DO101",
    seoDescription: "Convert PDF pages to JPG images at up to 300 DPI, in your browser. Download pages individually or as a zip. Free, no watermark, no upload.",
    steps: [
      "Add your PDF.",
      "Pick a resolution and image quality.",
      "Download a single page, or every page as a zip.",
    ],
    features: [
      "72 to 300 DPI output",
      "Adjustable JPG quality",
      "Page-by-page previews before you download",
      "Download all pages as one zip",
      "Rendered on your device with pdf.js",
    ],
    faqs: [
      {
        q: "Which resolution should I choose?",
        a: "144 DPI is right for screens and email. Choose 300 DPI if the image will be printed — the files get large, but the text stays crisp.",
      },
      {
        q: "Why is JPG smaller than PNG here?",
        a: "JPG uses lossy compression that suits the photographic content of rendered pages. For pages that are mostly sharp text or line art, PNG often looks better — use the PDF to PNG tool for those.",
      },
      {
        q: "Can I convert just some pages?",
        a: "Extract the pages you want with the PDF Page Extractor first, then run the result through this tool.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    short: "Export PDF pages as lossless PNG images.",
    long: "Render each page as a PNG, which keeps text edges perfectly sharp and supports transparency. Ideal for slides, diagrams and anything you will crop or annotate afterwards.",
    category: "pdf",
    route: "/tools/pdf-to-png",
    keywords: ["pdf to png", "convert pdf to png", "pdf page to png", "pdf to transparent image", "pdf to lossless image"],
    aliases: ["pdf to png image", "export pdf as png"],
    icon: "🎨",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-to-jpg", "png-to-pdf", "pdf-to-text", "image-resizer"],
    seoTitle: "PDF to PNG — Convert PDF Pages to PNG Free | DO101",
    seoDescription: "Convert PDF pages to lossless PNG images at up to 300 DPI. Sharp text, no watermark, and the file never leaves your browser.",
    steps: [
      "Add your PDF.",
      "Choose the resolution.",
      "Download the PNG pages individually or as a zip.",
    ],
    features: [
      "Lossless PNG output",
      "72 to 300 DPI",
      "Sharp text with no compression artefacts",
      "Zip download for multi-page documents",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "PNG or JPG — which should I pick?",
        a: "PNG for slides, diagrams, screenshots and anything with crisp text or flat colour. JPG for pages dominated by photographs, where the files are far smaller for the same visible quality.",
      },
      {
        q: "Do the PNGs have transparent backgrounds?",
        a: "No. PDF pages have a white page behind them, so the exported PNG has a white background too. You can remove it in an image editor if you need transparency.",
      },
    ],
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    short: "Turn JPG photos into a single PDF document.",
    long: "Add your JPGs, put them in order, choose A4, Letter or a page that fits each image exactly, then download one tidy PDF. Perfect for submitting photographed documents where only a PDF is accepted.",
    category: "pdf",
    route: "/tools/jpg-to-pdf",
    keywords: ["jpg to pdf", "jpeg to pdf", "convert jpg to pdf", "photos to pdf", "images to pdf", "picture to pdf"],
    aliases: ["jpeg to pdf", "photo to pdf", "convert photos to pdf"],
    icon: "📎",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["png-to-pdf", "image-to-pdf", "pdf-to-jpg", "pdf-merge"],
    seoTitle: "JPG to PDF — Convert Photos to PDF Free Online | DO101",
    seoDescription: "Convert JPG and JPEG photos into a single PDF. Reorder pages, choose A4 or Letter, add margins. Free, no watermark, and nothing is uploaded.",
    steps: [
      "Add your JPG photos.",
      "Drag them into the order you want with the arrows.",
      "Choose a page size, then create and download the PDF.",
    ],
    features: [
      "Many photos into one PDF",
      "Reorder before converting",
      "A4, US Letter, or fit-to-image pages",
      "Adjustable margins",
      "Built in your browser — photos are never uploaded",
    ],
    faqs: [
      {
        q: "Will my photos lose quality?",
        a: "No. JPGs are embedded into the PDF exactly as they are, without re-encoding, so the pages look identical to the originals.",
      },
      {
        q: "How do I get a smaller PDF?",
        a: "Compress the photos first with the Image Compressor, then convert. Shrinking the images is far more effective than compressing the finished PDF.",
      },
      {
        q: "Can I mix JPG and PNG?",
        a: "Yes — use the Image to PDF tool, which accepts every format your browser can open.",
      },
    ],
    featured: true,
  },
  {
    id: "png-to-pdf",
    name: "PNG to PDF",
    short: "Combine PNG images into one PDF document.",
    long: "Turn screenshots, diagrams and exported graphics into a single PDF. Transparent areas are placed on a white page, and each image keeps its original resolution.",
    category: "pdf",
    route: "/tools/png-to-pdf",
    keywords: ["png to pdf", "convert png to pdf", "screenshots to pdf", "png images to pdf"],
    aliases: ["screenshot to pdf", "convert png files to pdf"],
    icon: "🖇️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["jpg-to-pdf", "image-to-pdf", "pdf-to-png", "pdf-merge"],
    seoTitle: "PNG to PDF — Convert PNG Images to PDF Free | DO101",
    seoDescription: "Convert PNG images and screenshots into a single PDF, in the order you choose. Free, no watermark, and processed entirely in your browser.",
    steps: [
      "Add your PNG images.",
      "Set the order and page size.",
      "Create the PDF and download it.",
    ],
    features: [
      "Multiple PNGs into one document",
      "Lossless embedding — no re-encoding",
      "Reorder before converting",
      "A4, Letter or fit-to-image",
      "No upload",
    ],
    faqs: [
      {
        q: "What happens to transparency?",
        a: "PDF pages are opaque, so transparent areas end up over the white page background.",
      },
      {
        q: "Why is my PDF large?",
        a: "PNG is lossless, so screenshots stay big. Converting them to JPG first with the PNG to JPG tool usually cuts the size by 80% or more.",
      },
    ],
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    short: "Any mix of image formats into one PDF.",
    long: "Accepts JPG, PNG, WebP, GIF, BMP and anything else your browser can decode, mixes them freely, and produces one PDF. Formats the PDF specification cannot embed directly are re-encoded to JPEG automatically.",
    category: "pdf",
    route: "/tools/image-to-pdf",
    keywords: ["image to pdf", "photos to pdf", "convert images to pdf", "webp to pdf", "multiple images to pdf"],
    aliases: ["pictures to pdf", "convert image to pdf", "make a pdf from images"],
    icon: "🗂️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["jpg-to-pdf", "png-to-pdf", "pdf-merge", "image-compressor"],
    seoTitle: "Image to PDF — Convert Any Images to PDF Free | DO101",
    seoDescription: "Convert JPG, PNG, WebP, GIF and BMP images into a single PDF. Mix formats freely, reorder pages, and keep everything in your browser.",
    steps: [
      "Add images in any mix of formats.",
      "Order them and choose a page size.",
      "Create and download the PDF.",
    ],
    features: [
      "Mixes any formats the browser can open",
      "WebP, GIF and BMP re-encoded automatically",
      "Reorder before converting",
      "Page size and margin control",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "Which formats can I use?",
        a: "Anything your browser can decode: JPG, PNG, WebP, GIF, BMP and usually AVIF. JPG and PNG are embedded untouched; the rest are converted to JPEG at high quality first.",
      },
      {
        q: "Does the order matter?",
        a: "Yes — images become pages in exactly the order shown, and you can rearrange them with the arrows before converting.",
      },
    ],
  },
  {
    id: "pdf-extract-pages",
    name: "PDF Page Extractor",
    short: "Keep only the pages you want as a new PDF.",
    long: "Type the pages or ranges you need — 1-3, 7, 12- — and get a new PDF containing exactly those, in that order. The original file is untouched.",
    category: "pdf",
    route: "/tools/pdf-extract-pages",
    keywords: ["extract pdf pages", "pdf page extractor", "take pages out of pdf", "save pdf pages", "get one page from pdf"],
    aliases: ["pull pages from pdf", "save specific pdf pages", "extract page"],
    icon: "📑",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-delete-pages", "pdf-split", "pdf-reorder-pages", "pdf-merge"],
    seoTitle: "Extract PDF Pages — Save Selected Pages Free | DO101",
    seoDescription: "Extract specific pages or ranges from a PDF into a new document. Supports 1-3, 7, 12- and the words odd, even and last. Free and in-browser.",
    steps: [
      "Add your PDF.",
      "Type the pages to keep, such as 1-3, 7.",
      "Check the summary, then download the new PDF.",
    ],
    features: [
      "Ranges, single pages and open-ended ranges",
      "Keywords: all, odd, even, last",
      "Live summary of what the result will contain",
      "Original quality preserved",
      "No upload",
    ],
    faqs: [
      {
        q: "What syntax does the page box accept?",
        a: "Single pages (7), ranges (2-5), open-ended ranges (8- for page 8 to the end), and any combination separated by commas. The words all, odd, even and last also work.",
      },
      {
        q: "Can I change the page order at the same time?",
        a: "Yes. Pages come out in the order you list them, so typing 3, 1, 2 gives you those three pages in that sequence.",
      },
    ],
  },
  {
    id: "pdf-delete-pages",
    name: "Delete PDF Pages",
    short: "Remove pages from a PDF and keep the rest.",
    long: "Say which pages to drop and DO101 rebuilds the document without them, keeping everything else in its original order and quality.",
    category: "pdf",
    route: "/tools/pdf-delete-pages",
    keywords: ["delete pdf pages", "remove pages from pdf", "pdf page remover", "erase pdf page", "cut pages from pdf"],
    aliases: ["remove pdf pages", "drop pages from pdf"],
    icon: "🗑️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-extract-pages", "pdf-split", "pdf-reorder-pages", "pdf-rotate"],
    seoTitle: "Delete PDF Pages — Remove Pages Free Online | DO101",
    seoDescription: "Delete unwanted pages from a PDF and keep the rest, in your browser. Supports ranges and keywords. Free, no watermark, nothing uploaded.",
    steps: [
      "Add your PDF.",
      "Type the pages to delete, such as 2, 5-6.",
      "Confirm what will remain and download.",
    ],
    features: [
      "Delete single pages or ranges",
      "Shows exactly which pages survive",
      "Refuses to leave you with an empty document",
      "Original quality preserved",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "Is my original file changed?",
        a: "Never. DO101 builds a new PDF and leaves the file on your disk exactly as it was.",
      },
      {
        q: "Can I delete every page?",
        a: "No — a PDF needs at least one page, so the tool stops you and explains why.",
      },
    ],
  },
  {
    id: "pdf-reorder-pages",
    name: "Reorder PDF Pages",
    short: "Put a PDF's pages into a different order.",
    long: "List the pages in the sequence you want and DO101 rebuilds the document to match. Useful for fixing a scan that came out backwards, or moving an appendix to the front.",
    category: "pdf",
    route: "/tools/pdf-reorder-pages",
    keywords: ["reorder pdf pages", "rearrange pdf", "move pdf pages", "sort pdf pages", "reverse pdf pages"],
    aliases: ["rearrange pdf pages", "change pdf page order", "move pages in pdf"],
    icon: "🔀",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-extract-pages", "pdf-delete-pages", "pdf-merge", "pdf-rotate"],
    seoTitle: "Reorder PDF Pages — Rearrange a PDF Free | DO101",
    seoDescription: "Rearrange the pages of a PDF by listing them in your preferred order. Free, no watermark, and the document never leaves your browser.",
    steps: [
      "Add your PDF.",
      "Type the new order, for example 3, 1, 2, 4-8.",
      "Download the rearranged document.",
    ],
    features: [
      "Full control over page sequence",
      "Ranges work inside the order list",
      "Pages you leave out are dropped, and it tells you",
      "Original quality preserved",
      "No upload",
    ],
    faqs: [
      {
        q: "How do I reverse a whole document?",
        a: "List the pages backwards, for example 10, 9, 8, 7, 6, 5, 4, 3, 2, 1 for a ten-page file.",
      },
      {
        q: "What if I forget a page?",
        a: "Any page not in your list is left out of the result. The summary above the button always shows how many pages the output will contain.",
      },
    ],
  },
  {
    id: "pdf-rotate",
    name: "Rotate PDF",
    short: "Turn pages the right way up, permanently.",
    long: "Rotate every page or just the sideways ones by 90, 180 or 270 degrees. The rotation is saved into the file, so it stays fixed everywhere the PDF is opened — not just in your viewer.",
    category: "pdf",
    route: "/tools/pdf-rotate",
    keywords: ["rotate pdf", "turn pdf pages", "fix sideways pdf", "rotate pdf and save", "flip pdf page"],
    aliases: ["turn pdf", "fix upside down pdf", "rotate pdf pages"],
    icon: "🔄",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-delete-pages", "pdf-extract-pages", "pdf-merge", "pdf-to-jpg"],
    seoTitle: "Rotate PDF — Fix Sideways Pages & Save Free | DO101",
    seoDescription: "Rotate PDF pages by 90, 180 or 270 degrees and save the change permanently. Rotate all pages or only the ones you name. Free and in-browser.",
    steps: [
      "Add your PDF.",
      "Choose which pages and how far to turn them.",
      "Download the corrected document.",
    ],
    features: [
      "90, 180 and 270 degree rotation",
      "All pages, or only the ones you list",
      "Rotation is written into the file, not just the view",
      "Existing rotation is respected and added to",
      "No upload",
    ],
    faqs: [
      {
        q: "Why does my viewer already show it the right way, but printing is wrong?",
        a: "Some viewers apply a temporary rotation that is never saved. This tool writes the rotation into the document itself, so every viewer and printer agrees.",
      },
      {
        q: "Can I rotate only the landscape pages?",
        a: "Yes — list those page numbers in the pages box instead of leaving it as \"all\".",
      },
    ],
  },
  {
    id: "pdf-watermark",
    name: "Add Watermark to PDF",
    short: "Stamp text like DRAFT or CONFIDENTIAL across every page.",
    long: "Add a text watermark with the colour, size, opacity and angle you choose. It is drawn into every page of a new copy of the document, so it travels with the file.",
    category: "pdf",
    route: "/tools/pdf-watermark",
    keywords: ["pdf watermark", "add watermark to pdf", "stamp pdf", "watermark pdf online", "draft stamp pdf"],
    aliases: ["stamp pdf", "add draft to pdf", "confidential stamp"],
    icon: "💧",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-page-numbers", "pdf-merge", "pdf-compress", "pdf-rotate"],
    seoTitle: "Add Watermark to PDF — Free Text Watermark Tool | DO101",
    seoDescription: "Add a text watermark to every page of a PDF with control over colour, size, opacity and angle. Free, no upload, no watermark from us.",
    steps: [
      "Add your PDF.",
      "Type the watermark text and adjust colour, size and opacity.",
      "Apply it and download the stamped PDF.",
    ],
    features: [
      "Any text up to 60 characters",
      "Colour, size and opacity control",
      "Diagonal or horizontal",
      "Applied to every page",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Can the watermark be removed?",
        a: "A determined person with the right software can remove any visual watermark. Treat it as a clear label of intent, not as security.",
      },
      {
        q: "Why are non-Latin characters not working?",
        a: "The watermark uses the standard Helvetica font built into every PDF reader, which only covers the Latin alphabet. Embedding a font for other scripts is on the roadmap.",
      },
      {
        q: "Can I use an image as the watermark?",
        a: "Not yet — this tool does text only. Image watermarks are planned.",
      },
    ],
  },
  {
    id: "pdf-page-numbers",
    name: "Add Page Numbers to PDF",
    short: "Number the pages of a PDF, your way.",
    long: "Add page numbers in the corner or centre, choose the format — 1, Page 1, or 1 of 20 — and pick which number to start from. Handy for documents assembled from several sources.",
    category: "pdf",
    route: "/tools/pdf-page-numbers",
    keywords: ["add page numbers to pdf", "pdf page numbering", "number pdf pages", "pdf pagination"],
    aliases: ["number pdf pages", "pdf page numbering tool"],
    icon: "🔢",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-watermark", "pdf-merge", "pdf-reorder-pages", "pdf-extract-pages"],
    seoTitle: "Add Page Numbers to PDF — Free Online Tool | DO101",
    seoDescription: "Number the pages of a PDF with a choice of position, format and starting number. Free, no watermark, and processed entirely in your browser.",
    steps: [
      "Add your PDF.",
      "Choose a position, format and starting number.",
      "Apply and download the numbered document.",
    ],
    features: [
      "Four positions",
      "Formats including \"Page 1 of 20\"",
      "Custom starting number",
      "Adjustable text size",
      "No upload",
    ],
    faqs: [
      {
        q: "Can I skip the cover page?",
        a: "Not yet directly. As a workaround, extract pages 2 onwards, number them, then merge the cover back on the front.",
      },
      {
        q: "Will numbers cover my content?",
        a: "They are placed in the page margin. If your document has unusually tight margins, reduce the text size.",
      },
    ],
  },
  {
    id: "pdf-to-text",
    name: "PDF to Text",
    short: "Pull the plain text out of a PDF.",
    long: "Extract every word from a PDF's text layer, with optional page markers, then copy it or download it as a .txt file. If the PDF is a scan with no text layer, DO101 says so and points you at OCR instead of returning an empty file.",
    category: "pdf",
    route: "/tools/pdf-to-text",
    keywords: ["pdf to text", "extract text from pdf", "pdf text extractor", "copy text from pdf", "pdf to txt"],
    aliases: ["get text from pdf", "pdf text extraction", "copy pdf text"],
    icon: "🔤",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "text",
    related: ["pdf-to-word", "pdf-ocr", "word-counter", "text-cleaner"],
    seoTitle: "PDF to Text — Extract Text from PDF Free | DO101",
    seoDescription: "Extract the text from a PDF in your browser, with page markers and word counts. Detects scanned PDFs and points you to OCR. Free, no upload.",
    steps: [
      "Add your PDF.",
      "Press extract.",
      "Copy the text or download it as a .txt file.",
    ],
    features: [
      "Whole-document extraction with page markers",
      "Word and character counts",
      "Detects scanned PDFs with no text layer",
      "Copy or download as .txt",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "Why did I get nothing back?",
        a: "Your PDF is almost certainly a scan — an image of a page rather than real text. The PDF OCR tool reads the words out of the image instead.",
      },
      {
        q: "Is the layout preserved?",
        a: "Line breaks are reconstructed from where the text sits on the page, so paragraphs come out sensibly. Columns and tables will read in the order the PDF stores them, which is not always the visual order.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    short: "Turn a PDF into an editable .docx document.",
    long: "Extracts the text from a PDF and builds a real Word document you can edit, keeping paragraphs and page breaks. This is a text conversion, not a layout clone — the page says exactly what survives and what does not, so nothing is a surprise.",
    category: "pdf",
    route: "/tools/pdf-to-word",
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "pdf to editable document", "pdf to word free"],
    aliases: ["pdf to docx", "convert pdf to word document", "make pdf editable"],
    icon: "📝",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["word-to-pdf", "pdf-to-text", "pdf-ocr", "pdf-merge"],
    seoTitle: "PDF to Word — Convert PDF to Editable DOCX Free | DO101",
    seoDescription: "Convert a PDF into an editable Word .docx document in your browser. Keeps paragraphs and page breaks. Free, no sign-up, and nothing is uploaded.",
    steps: [
      "Add your PDF.",
      "Press convert to read its text.",
      "Download the .docx and edit it in Word, Pages or Google Docs.",
    ],
    features: [
      "Produces a genuine .docx file",
      "Paragraphs and page breaks preserved",
      "Preview the text before downloading",
      "Detects scanned PDFs and redirects you to OCR",
      "Converted on your device",
    ],
    faqs: [
      {
        q: "Will my formatting be preserved?",
        a: "Paragraphs and page breaks are. Fonts, columns, tables, images and exact positioning are not — this converts the words, not the design. For a text-heavy report that is usually what you want; for a designed brochure it is not.",
      },
      {
        q: "Why is this different from paid converters?",
        a: "Commercial converters run heavy layout-analysis engines on a server to rebuild tables and columns. DO101 does everything in your browser for free, so it does the part it can do properly and tells you plainly what it leaves out.",
      },
      {
        q: "It produced nothing — why?",
        a: "The PDF is a scan with no text layer. Run it through PDF OCR first.",
      },
      {
        q: "Is my document uploaded?",
        a: "No. Both the text extraction and the .docx generation happen in this page.",
      },
    ],
    featured: true,
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    short: "Convert a .docx document into a PDF.",
    long: "Reads a Word document in your browser and lays it out as a real PDF with selectable text, keeping headings, paragraphs, lists, bold and italic. Images are embedded where possible and tables are flattened into readable lines.",
    category: "pdf",
    route: "/tools/word-to-pdf",
    keywords: ["word to pdf", "docx to pdf", "convert word to pdf", "doc to pdf", "word document to pdf"],
    aliases: ["docx to pdf", "convert word file to pdf", "save word as pdf"],
    icon: "📄",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-to-word", "markdown-to-pdf", "html-to-pdf", "pdf-merge"],
    seoTitle: "Word to PDF — Convert DOCX to PDF Free Online | DO101",
    seoDescription: "Convert Word .docx documents to PDF in your browser, keeping headings, lists and formatting. Free, no watermark, and nothing is uploaded.",
    steps: [
      "Add your .docx file.",
      "Choose A4 or US Letter.",
      "Convert and download the PDF.",
    ],
    features: [
      "Headings, paragraphs, lists, bold and italic",
      "Images embedded where the format allows",
      "Real selectable text, not a picture",
      "Reports exactly what changed in conversion",
      "Converted on your device",
    ],
    faqs: [
      {
        q: "Does it look exactly like Word?",
        a: "No, and the tool says so before you convert. It produces a clean, readable PDF with your text and structure intact. Exact fonts, columns, floated images and complex tables are not reproduced.",
      },
      {
        q: "Can I convert an old .doc file?",
        a: "No. The legacy binary .doc format cannot be read in a browser. Open it in Word or LibreOffice and save it as .docx first.",
      },
      {
        q: "What happens to non-Latin text?",
        a: "PDF's standard fonts only cover the Latin alphabet, so scripts like Devanagari, Arabic or Chinese are replaced with question marks — and the tool tells you exactly how many characters that affected.",
      },
    ],
  },
  {
    id: "pdf-ocr",
    name: "PDF OCR",
    short: "Read the text out of a scanned PDF.",
    long: "Runs optical character recognition over each page of a scanned PDF and gives you back copyable text, with a confidence score so you know how much to trust it. Seventeen languages, and the whole thing runs on your device.",
    category: "pdf",
    route: "/tools/pdf-ocr",
    keywords: ["pdf ocr", "scanned pdf to text", "ocr pdf online", "read scanned pdf", "extract text from scanned pdf"],
    aliases: ["scanned pdf to text", "ocr a pdf", "make scanned pdf searchable"],
    icon: "🔍",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "text",
    related: ["image-to-text", "pdf-to-text", "pdf-to-word", "pdf-to-jpg"],
    seoTitle: "PDF OCR — Extract Text from Scanned PDFs Free | DO101",
    seoDescription: "Run OCR on a scanned PDF in your browser and get copyable text back, in 17 languages, with a confidence score. Free, no upload, no sign-up.",
    steps: [
      "Choose the language of the document.",
      "Add the scanned PDF, up to 20 pages per run.",
      "Wait for recognition, then copy or download the text.",
    ],
    features: [
      "17 languages",
      "Per-run confidence score",
      "Pages rendered at high DPI for accuracy",
      "Copy or download as .txt",
      "Recognition runs on your device",
    ],
    faqs: [
      {
        q: "Why is the first run slow?",
        a: "The OCR engine and language model — about 12 to 15 MB — are downloaded from a public CDN the first time. Your browser caches them, so later runs start immediately.",
      },
      {
        q: "How accurate is it?",
        a: "On a clean, straight, high-contrast scan, very good. On a crooked phone photo of a faint receipt, poor. The confidence score tells you which situation you are in, and DO101 warns you when it drops below 70%.",
      },
      {
        q: "Why only 20 pages?",
        a: "OCR is heavy work. Capping the batch keeps the browser responsive and prevents the tab from running out of memory. Split a longer document first.",
      },
      {
        q: "Is my document uploaded?",
        a: "No. Only the engine and language model are downloaded; your PDF stays on your device.",
      },
    ],
    featured: true,
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    short: "Turn an HTML file or snippet into a PDF.",
    long: "Paste HTML or drop a .html file and get a clean PDF with real selectable text. Headings, paragraphs, lists, bold, italic, rules and images are rendered; CSS layout is deliberately not, so the output is predictable.",
    category: "pdf",
    route: "/tools/html-to-pdf",
    keywords: ["html to pdf", "convert html to pdf", "webpage to pdf", "html file to pdf"],
    aliases: ["convert html to pdf", "html file to pdf"],
    icon: "🌐",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "file",
    related: ["markdown-to-pdf", "word-to-pdf", "txt-to-pdf", "html-to-markdown"],
    seoTitle: "HTML to PDF — Convert HTML to PDF Free Online | DO101",
    seoDescription: "Convert HTML files or pasted markup into a clean PDF with selectable text, in your browser. Free, no watermark, and nothing is uploaded.",
    steps: [
      "Paste your HTML or drop a .html file.",
      "Choose a page size.",
      "Convert and download the PDF.",
    ],
    features: [
      "Paste markup or upload a file",
      "Headings, lists, bold, italic, rules and images",
      "Real selectable text",
      "Markup is parsed safely and never executed",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Does it apply my CSS?",
        a: "No. This converter reads the document structure, not the stylesheet, so the output is a clean, consistent document rather than an attempt at a screenshot. For a pixel-accurate capture, use your browser's own Print to PDF.",
      },
      {
        q: "Is pasted HTML safe?",
        a: "Yes. The markup is parsed in an inert document, never inserted into this page, so scripts in it cannot run.",
      },
    ],
  },
  {
    id: "markdown-to-pdf",
    name: "Markdown to PDF",
    short: "Turn Markdown into a formatted PDF.",
    long: "Write or paste Markdown and get a properly typeset PDF: headings scale, lists indent, bold and italic are respected, and horizontal rules are drawn. Ideal for READMEs, notes and documentation.",
    category: "pdf",
    route: "/tools/markdown-to-pdf",
    keywords: ["markdown to pdf", "md to pdf", "convert markdown to pdf", "readme to pdf"],
    aliases: ["md to pdf", "convert md file to pdf"],
    icon: "⬇️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "file",
    related: ["markdown-to-html", "html-to-pdf", "word-to-pdf", "txt-to-pdf"],
    seoTitle: "Markdown to PDF — Convert MD to PDF Free Online | DO101",
    seoDescription: "Convert Markdown files or pasted text into a formatted PDF with headings, lists and emphasis. Free, no sign-up, and processed in your browser.",
    steps: [
      "Paste Markdown or drop a .md file.",
      "Choose a page size.",
      "Convert and download the PDF.",
    ],
    features: [
      "Full CommonMark parsing",
      "Headings, lists, emphasis and rules",
      "Paste or upload",
      "Real selectable text",
      "No upload",
    ],
    faqs: [
      {
        q: "Are code blocks styled?",
        a: "They are rendered as plain paragraphs. Syntax highlighting in PDF output is on the roadmap.",
      },
      {
        q: "Do tables work?",
        a: "Markdown tables are flattened into readable lines rather than drawn as a grid, and the conversion report tells you when that happened.",
      },
    ],
  },
  {
    id: "txt-to-pdf",
    name: "Text to PDF",
    short: "Turn a plain text file into a tidy PDF.",
    long: "Drop a .txt file or paste text and get a properly paginated PDF with sensible margins and word wrapping. Useful for logs, notes and anything that needs to be handed over in PDF form.",
    category: "pdf",
    route: "/tools/txt-to-pdf",
    keywords: ["txt to pdf", "text to pdf", "convert text file to pdf", "notes to pdf"],
    aliases: ["text file to pdf", "convert txt to pdf"],
    icon: "🔤",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "file",
    related: ["markdown-to-pdf", "html-to-pdf", "word-to-pdf", "pdf-to-text"],
    seoTitle: "Text to PDF — Convert TXT Files to PDF Free | DO101",
    seoDescription: "Convert plain text files or pasted text into a paginated PDF with proper margins and wrapping. Free, no watermark, and entirely in your browser.",
    steps: [
      "Paste your text or drop a .txt file.",
      "Choose a page size.",
      "Convert and download the PDF.",
    ],
    features: [
      "Automatic word wrap and pagination",
      "Blank lines become paragraph breaks",
      "Paste or upload",
      "Selectable text in the output",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "How are line breaks handled?",
        a: "A blank line starts a new paragraph. Single line breaks inside a paragraph are treated as soft wraps, which is what plain text usually means.",
      },
      {
        q: "Is there a size limit?",
        a: "30 MB, which is far more plain text than any PDF should reasonably contain.",
      },
    ],
  },
  {
    id: "pdf-organize",
    name: "Organize PDF",
    short: "See every page and drag, rotate or delete it.",
    long: "Every page becomes a thumbnail you can drag into a new order, rotate, or delete — then rebuild the document. Far easier to get right than typing page ranges into a box, because you can see exactly what you are doing.",
    category: "pdf",
    route: "/tools/pdf-organize",
    keywords: ["organize pdf", "rearrange pdf pages", "pdf page organizer", "sort pdf pages visually", "edit pdf pages"],
    aliases: ["pdf page manager", "rearrange pdf visually", "move pdf pages"],
    icon: "🗂️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-reorder-pages", "pdf-delete-pages", "pdf-rotate", "pdf-merge"],
    seoTitle: "Organize PDF — Visual Page Manager, Free | DO101",
    seoDescription: "Reorder, rotate and delete PDF pages with visual thumbnails. Drag pages into place and rebuild the document. Free, no watermark, nothing uploaded.",
    steps: [
      "Add your PDF and wait for the page thumbnails.",
      "Drag pages into order, rotate or delete them.",
      "Apply the changes and download the rebuilt PDF.",
    ],
    features: [
      "Thumbnail preview of every page",
      "Drag and drop reordering",
      "Per-page rotation",
      "Delete and restore pages",
      "Rebuilt on your device — nothing uploaded",
    ],
    faqs: [
      {
        q: "How many pages can it show?",
        a: "Up to 200. Beyond that, rendering every thumbnail becomes slow, so split the document first or use the range-based page tools.",
      },
      {
        q: "Does rotating here change the file?",
        a: "Yes. The rotation is written into the rebuilt PDF, so it stays fixed in every viewer rather than being a temporary display setting.",
      },
      {
        q: "Can I undo a deletion?",
        a: "Yes — deleted pages stay visible but dimmed until you apply, and \"restore deleted\" brings them all back.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-redact",
    name: "Redact PDF",
    short: "Permanently remove sensitive text, not just cover it.",
    long: "Drag over anything that must disappear and DO101 flattens each page to an image with those areas painted out. The original text objects are genuinely gone — unlike a black rectangle drawn on top, which leaves the words underneath for anyone to select.",
    category: "pdf",
    route: "/tools/pdf-redact",
    keywords: ["redact pdf", "black out pdf text", "remove sensitive information pdf", "pdf redaction tool", "hide text in pdf"],
    aliases: ["black out pdf", "censor pdf", "remove text from pdf"],
    icon: "🖍️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-crop", "pdf-compress", "pdf-to-jpg", "pdf-watermark"],
    seoTitle: "Redact PDF — Permanently Remove Text, Free | DO101",
    seoDescription: "Redact a PDF so the text is genuinely removed, not just covered. Flattens pages to images with your areas blacked out. Free and entirely in your browser.",
    steps: [
      "Add the PDF and wait for the page previews.",
      "Drag a box over everything that must be removed.",
      "Apply the redaction and download the flattened PDF.",
    ],
    features: [
      "Drag to mark any area on any page",
      "Click a mark to remove it",
      "Genuine removal by flattening, not an overlay",
      "Works on mouse and touch",
      "Never uploaded — redaction runs on your device",
    ],
    faqs: [
      {
        q: "Why is drawing a black box not enough?",
        a: "Because a PDF stores text separately from graphics. A rectangle drawn on top hides the words visually, but they are still in the file and can be selected, copied or extracted. Several organisations have leaked documents exactly this way.",
      },
      {
        q: "What is the trade-off here?",
        a: "The redacted pages become images. The redacted content is genuinely gone, but text elsewhere on those pages is no longer selectable or searchable. That is the price of certainty.",
      },
      {
        q: "Is my document uploaded?",
        a: "No. Rendering, painting and rebuilding all happen on your device — which matters a great deal for the kind of document you would want to redact.",
      },
      {
        q: "How many pages can I redact at once?",
        a: "Up to 40 per run, so the previews stay responsive. Extract the pages you need first for longer documents.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-sign",
    name: "Sign PDF",
    short: "Draw your signature and place it on the page.",
    long: "Draw a signature with your mouse, trackpad or finger — or upload an image of one — then click anywhere on a page to place it. Everything happens on your device, including the signature itself.",
    category: "pdf",
    route: "/tools/pdf-sign",
    keywords: ["sign pdf", "pdf signature", "add signature to pdf", "electronic signature pdf", "sign document online"],
    aliases: ["add signature to pdf", "e-sign pdf", "signature on pdf"],
    icon: "✍️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-watermark", "pdf-page-numbers", "pdf-organize", "pdf-merge"],
    seoTitle: "Sign PDF — Add Your Signature Free & Privately | DO101",
    seoDescription: "Draw or upload a signature and place it on any PDF page. Free, no account, and your document and signature never leave your browser.",
    steps: [
      "Add the PDF you need to sign.",
      "Draw your signature, or upload an image of it.",
      "Click where it should go on the page, then download.",
    ],
    features: [
      "Draw with mouse, trackpad or finger",
      "Or upload a PNG with transparency",
      "Adjustable size, placeable on any page",
      "Click a placed signature to remove it",
      "Document and signature both stay on your device",
    ],
    faqs: [
      {
        q: "Is this a legally binding signature?",
        a: "It places a visual signature, which is what most everyday forms and agreements ask for. It is not a cryptographic digital signature and creates no certificate or audit trail. For a legally verifiable e-signature, use a dedicated e-signature service.",
      },
      {
        q: "Is my signature stored anywhere?",
        a: "No. It exists only in the page while you are using it, and is discarded when you close the tab.",
      },
      {
        q: "What image works best for an uploaded signature?",
        a: "A PNG with a transparent background. A JPG will carry a white box around the signature.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-crop",
    name: "Crop PDF",
    short: "Trim margins or scan borders from every page.",
    long: "Drag four sliders to trim whitespace, scanner edges or headers, watching a live preview of the first page. Cropping adjusts the page box rather than redrawing content, so text stays selectable and nothing is re-encoded.",
    category: "pdf",
    route: "/tools/pdf-crop",
    keywords: ["crop pdf", "trim pdf margins", "cut pdf edges", "remove pdf whitespace", "pdf margin remover"],
    aliases: ["trim pdf", "cut pdf margins", "remove pdf borders"],
    icon: "✂️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-redact", "pdf-rotate", "pdf-organize", "pdf-compress"],
    seoTitle: "Crop PDF — Trim Margins Online Free | DO101",
    seoDescription: "Crop PDF margins with a live preview and four simple sliders. Text stays selectable because nothing is re-encoded. Free and in your browser.",
    steps: [
      "Add your PDF and look at the first-page preview.",
      "Drag the sliders to set how much to trim from each edge.",
      "Apply and download the cropped document.",
    ],
    features: [
      "Live preview with the kept area highlighted",
      "Independent control of all four edges",
      "Before and after page dimensions",
      "Text stays selectable — no re-encoding",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "Is the cropped content deleted?",
        a: "No. Cropping changes the visible page box, so the trimmed content is hidden but still present in the file. If it must actually be gone, use the Redact tool instead.",
      },
      {
        q: "Does cropping reduce the file size?",
        a: "Barely. Nothing is removed or re-encoded, so the size stays roughly the same. Use Compress PDF for that.",
      },
      {
        q: "Can I crop only some pages?",
        a: "Not yet — the crop applies to every page. Extract the pages you want to treat differently, crop them, then merge them back.",
      },
    ],
  },
  {
    id: "pdf-compare",
    name: "Compare PDF",
    short: "Spot every wording change between two PDFs.",
    long: "Load two versions of a document and DO101 extracts the text from each and highlights exactly which words were added and removed. Ideal for contract revisions and reviewing what actually changed between drafts.",
    category: "pdf",
    route: "/tools/pdf-compare",
    keywords: ["compare pdf", "pdf diff", "find differences between pdfs", "compare two documents", "pdf comparison tool"],
    aliases: ["diff two pdfs", "pdf difference checker", "compare contracts"],
    icon: "🔍",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "text",
    related: ["text-diff", "pdf-to-text", "pdf-to-word", "pdf-organize"],
    seoTitle: "Compare PDF — Find Differences Between Two PDFs | DO101",
    seoDescription: "Compare two PDF documents and highlight every added and removed word. Free, no upload, and the comparison runs entirely in your browser.",
    steps: [
      "Add the original document.",
      "Add the revised document.",
      "Read the word-by-word highlighted differences.",
    ],
    features: [
      "Word-level highlighting, not line-level",
      "Added, removed and unchanged counts",
      "Ignores whitespace differences by default",
      "Detects scanned PDFs and tells you",
      "Both documents stay on your device",
    ],
    faqs: [
      {
        q: "Does it compare formatting and images?",
        a: "No — it compares the text. Layout, fonts and images are not analysed, which is usually what you want when checking what a contract revision actually changed.",
      },
      {
        q: "Why does it ignore whitespace by default?",
        a: "Two exports of the same document often wrap lines differently. Without that option, every paragraph would appear changed.",
      },
      {
        q: "One of my PDFs is a scan.",
        a: "Then it has no text layer to compare. Run it through PDF OCR first, then compare the results.",
      },
    ],
  },
  {
    id: "pdf-to-markdown",
    name: "PDF to Markdown",
    short: "Turn a PDF into Markdown for notes, docs and LLMs.",
    long: "Extracts the text and rebuilds it as Markdown, inferring headings from line shape and normalising bullet and numbered lists. The result is editable in the page before you copy it, so you can fix anything the heuristics got wrong.",
    category: "pdf",
    route: "/tools/pdf-to-markdown",
    keywords: ["pdf to markdown", "pdf to md", "convert pdf to markdown", "pdf for llm", "pdf to notes"],
    aliases: ["pdf to md", "markdown from pdf"],
    icon: "⬇️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "text",
    related: ["pdf-to-text", "markdown-to-pdf", "html-to-markdown", "pdf-to-word"],
    seoTitle: "PDF to Markdown — Convert PDF to MD Free | DO101",
    seoDescription: "Convert a PDF into Markdown with headings and lists detected automatically. Editable before you copy. Free and running entirely in your browser.",
    steps: [
      "Add your PDF.",
      "Choose whether to detect headings and lists.",
      "Edit anything that came out wrong, then copy or download the .md.",
    ],
    features: [
      "Heading detection from line shape",
      "Bullet and numbered list normalisation",
      "Optional rule between pages",
      "Editable output before you copy",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "How are headings detected?",
        a: "A PDF's text layer does not reliably expose font sizes, so DO101 infers headings from shape: short lines without terminal punctuation, numbered section headers and ALL-CAPS titles. It is a good first draft rather than a perfect conversion, which is why the output is editable.",
      },
      {
        q: "Why convert a PDF to Markdown?",
        a: "Markdown is plain text with structure, which makes it ideal for notes apps, documentation repositories and feeding documents to language models.",
      },
      {
        q: "Do tables convert?",
        a: "Not into Markdown tables. Try PDF to Excel for tabular data.",
      },
    ],
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    short: "Recover tables from a PDF into a spreadsheet.",
    long: "Finds tables by looking at where every word sits on the page — grouping words on the same baseline into rows, and clustering their horizontal positions into columns — then builds a real .xlsx workbook with one sheet per page. A confidence score tells you how much to trust each result.",
    category: "pdf",
    route: "/tools/pdf-to-excel",
    keywords: ["pdf to excel", "pdf table to excel", "extract tables from pdf", "pdf to xlsx", "pdf to spreadsheet"],
    aliases: ["pdf table extractor", "pdf to xlsx", "get tables out of pdf"],
    icon: "📈",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["excel-to-pdf", "pdf-to-text", "csv-to-json", "pdf-to-word"],
    seoTitle: "PDF to Excel — Extract Tables to XLSX Free | DO101",
    seoDescription: "Extract tables from a PDF into a real Excel workbook using position-based detection, with a confidence score. Free and entirely in your browser.",
    steps: [
      "Add a PDF that contains tables.",
      "Press find tables and check the preview.",
      "Download the .xlsx, one sheet per page.",
    ],
    features: [
      "Position-based row and column detection",
      "Confidence score per table",
      "Preview before you download",
      "One sheet per page in a real .xlsx",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "How accurate is it?",
        a: "Good on ordinary ruled or whitespace-aligned tables. Merged cells, nested tables and cells that wrap across several lines are where position-based detection struggles — which is why every table shows a confidence score and a preview.",
      },
      {
        q: "It found no tables.",
        a: "Either the PDF is a scan with no text layer (run PDF OCR first), or the data is not laid out in aligned columns. Position-based detection can only see what the text layer describes.",
      },
      {
        q: "Why do other tools do this better?",
        a: "Commercial converters run trained layout models on a server. DO101 does what can be done well in a browser, shows you the confidence, and lets you check before trusting it.",
      },
    ],
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    short: "Turn a spreadsheet into a readable PDF.",
    long: "Reads .xlsx, .xls, .csv and .ods files and lays their sheets out as paginated tables in a PDF, with a bold header row and your choice of orientation. Handy when a spreadsheet has to be sent somewhere that only accepts PDFs.",
    category: "pdf",
    route: "/tools/excel-to-pdf",
    keywords: ["excel to pdf", "xlsx to pdf", "spreadsheet to pdf", "convert excel to pdf", "csv to pdf"],
    aliases: ["xlsx to pdf", "convert spreadsheet to pdf"],
    icon: "📄",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-to-excel", "excel-to-csv", "csv-to-excel", "word-to-pdf"],
    seoTitle: "Excel to PDF — Convert Spreadsheets Free Online | DO101",
    seoDescription: "Convert Excel, CSV and ODS spreadsheets into a paginated PDF with a bold header row. Free, no watermark, and processed in your browser.",
    steps: [
      "Add your spreadsheet.",
      "Choose landscape or portrait.",
      "Convert and download the PDF.",
    ],
    features: [
      "Reads .xlsx, .xls, .csv and .ods",
      "Landscape or portrait pagination",
      "Bold header row with a rule beneath",
      "Multiple sheets in one PDF",
      "Parsed on your device — nothing uploaded",
    ],
    faqs: [
      {
        q: "Are my formulas preserved?",
        a: "No. A PDF shows values, not formulas, so the calculated results are what gets printed.",
      },
      {
        q: "What happens to very wide tables?",
        a: "Columns share the page width evenly, and text too wide for its column is shortened with an ellipsis. The tool tells you how many cells that affected — landscape orientation usually fixes it.",
      },
      {
        q: "Is my spreadsheet uploaded?",
        a: "No. It is parsed and rendered entirely on your device, which matters when it contains customer or financial data.",
      },
    ],
  },
  {
    id: "pdf-protect",
    name: "Protect PDF",
    short: "Add a password and lock down printing and copying.",
    long: "Encrypts a PDF with a password using real AES encryption, applied on your own device. You also choose what someone holding the password may do: print, copy text, edit or annotate. The password is never transmitted and never stored.",
    category: "pdf",
    route: "/tools/pdf-protect",
    keywords: ["protect pdf", "password protect pdf", "encrypt pdf", "add password to pdf", "lock pdf", "secure pdf"],
    aliases: ["password protect pdf", "lock a pdf", "encrypt pdf file"],
    icon: "🔐",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-unlock", "pdf-redact", "pdf-sign", "pdf-watermark"],
    seoTitle: "Protect PDF — Add a Password Free & Offline | DO101",
    seoDescription: "Password-protect a PDF with real AES encryption in your browser. Control printing, copying and editing. Free, no upload, and the password never leaves your device.",
    steps: [
      "Add the PDF you want to protect.",
      "Choose a password and confirm it.",
      "Pick what the password holder may do, then encrypt and download.",
    ],
    features: [
      "Genuine AES encryption, not a fake overlay",
      "Permission controls for printing, copying, editing and comments",
      "Password strength guidance",
      "Verifies the encryption applied before offering the download",
      "Runs entirely on your device",
    ],
    faqs: [
      {
        q: "Is this real encryption?",
        a: "Yes. The document is encrypted to the PDF standard, and DO101 checks the output actually carries an encryption dictionary before letting you download it. Opening the file afterwards genuinely requires the password.",
      },
      {
        q: "Can DO101 recover my password if I forget it?",
        a: "No — and neither can anyone else. The password is never sent anywhere and never stored, which is exactly what makes it safe. Write it down somewhere before you encrypt anything important.",
      },
      {
        q: "What do the permission switches actually do?",
        a: "They are recorded in the file and respected by mainstream PDF readers, so they stop honest mistakes like accidental printing. They are a policy signal rather than a hard guarantee — the password is what really protects the contents.",
      },
      {
        q: "Is my document uploaded?",
        a: "No. Encryption happens in this page, which matters rather a lot for the kind of document you would want to lock.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-unlock",
    name: "Unlock PDF",
    short: "Remove a password or restrictions from your own PDF.",
    long: "Strips the permission restrictions from a PDF that already opens on your machine, and removes the password entirely when you type the password yourself. It is not a cracker: a wrong password is rejected, so it will never open a document you do not have access to.",
    category: "pdf",
    route: "/tools/pdf-unlock",
    keywords: ["unlock pdf", "remove pdf password", "pdf password remover", "decrypt pdf", "remove pdf restrictions", "enable printing pdf"],
    aliases: ["remove password from pdf", "decrypt pdf", "pdf password remover"],
    icon: "🔓",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-protect", "pdf-repair", "pdf-merge", "pdf-compress"],
    seoTitle: "Unlock PDF — Remove Password & Restrictions Free | DO101",
    seoDescription: "Remove restrictions from a PDF that opens on your device, or remove a password you already know. Free, in-browser, and never a password cracker.",
    steps: [
      "Add the protected PDF.",
      "DO101 tells you which kind of protection it carries.",
      "Type the password if one is needed, then download the unlocked copy.",
    ],
    features: [
      "Detects restrictions versus a real password",
      "Removes printing and copying locks with no password needed",
      "Removes a password when you supply it",
      "Rejects a wrong password rather than producing a broken file",
      "Runs on your device — file and password stay put",
    ],
    faqs: [
      {
        q: "Can this open a PDF I do not have the password for?",
        a: "No. A wrong password is rejected by the underlying library. This tool removes protection you are already entitled to remove — it is not a password cracker and will not be turned into one.",
      },
      {
        q: "What is the difference between the two kinds of protection?",
        a: "Some PDFs open normally but block printing or copying — those restrictions come off with no password at all. Others demand a password before they will open, and for those you have to type the password you already use.",
      },
      {
        q: "Is it legal to do this?",
        a: "Only use it on documents you own or have permission to modify. Removing protection from someone else's document may breach copyright or contract terms where you live.",
      },
      {
        q: "Why did the text come out garbled on another site?",
        a: "A common shortcut is to skip the encryption check without actually decrypting the content, which produces a corrupted file. DO101 decrypts properly and verifies the result, so the text stays intact.",
      },
    ],
    featured: true,
  },
  {
    id: "pdf-repair",
    name: "Repair PDF",
    short: "Recover what can be read from a damaged PDF.",
    long: "Re-parses a broken file loosely and rebuilds a clean document from every page that survives. It fixes damaged cross-reference tables, stray bytes and malformed objects — and tells you honestly how many pages it managed to recover.",
    category: "pdf",
    route: "/tools/pdf-repair",
    keywords: ["repair pdf", "fix corrupted pdf", "pdf recovery", "damaged pdf", "pdf will not open", "restore pdf"],
    aliases: ["fix broken pdf", "recover pdf", "corrupted pdf repair"],
    icon: "🩹",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-unlock", "pdf-compress", "pdf-merge", "pdf-organize"],
    seoTitle: "Repair PDF — Fix a Corrupted PDF Free Online | DO101",
    seoDescription: "Recover a damaged PDF by rebuilding it from the pages that can still be read. Reports exactly how many survived. Free and entirely in your browser.",
    steps: [
      "Add the PDF that will not open.",
      "DO101 attempts to re-parse and rebuild it.",
      "Check every recovered page before relying on it.",
    ],
    features: [
      "Rebuilds a clean document from readable pages",
      "Reports how many of the original pages survived",
      "Fixes broken cross-reference tables and stray bytes",
      "Explains clearly when a file is beyond recovery",
      "Runs on your device",
    ],
    faqs: [
      {
        q: "Can it recover a page whose content is missing?",
        a: "No. If the data was lost before the file reached you — a truncated download is the usual cause — there is nothing to rebuild from. No tool can invent it, and this one says so rather than pretending.",
      },
      {
        q: "What kinds of damage can it fix?",
        a: "Broken cross-reference tables, stray bytes appended by a bad transfer, and malformed objects that make strict readers refuse the file. Those are the common causes of \"this PDF cannot be opened\".",
      },
      {
        q: "My PDF is password-protected and will not repair.",
        a: "Remove the password with the Unlock tool first, then repair the result. Repairing an encrypted file without decrypting it would produce unreadable output.",
      },
    ],
  },
  {
    id: "scan-to-pdf",
    name: "Scan to PDF",
    short: "Use your camera to turn paper into a PDF.",
    long: "Opens your device camera, captures page after page, and builds them into a single PDF. There is an optional grayscale mode that makes documents far more readable and much smaller. The camera stream never leaves your device.",
    category: "pdf",
    route: "/tools/scan-to-pdf",
    keywords: ["scan to pdf", "scan document with phone", "camera to pdf", "document scanner online", "photo to pdf scanner"],
    aliases: ["scan document to pdf", "phone scanner", "camera scanner pdf"],
    icon: "📷",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "file",
    related: ["image-to-pdf", "pdf-ocr", "jpg-to-pdf", "pdf-compress"],
    seoTitle: "Scan to PDF — Free Document Scanner in Your Browser | DO101",
    seoDescription: "Scan paper documents with your phone or laptop camera and save them as a PDF. No app to install, no upload, and the camera stream stays on your device.",
    steps: [
      "Open the camera and allow access when your browser asks.",
      "Line up each page and press capture.",
      "Choose a page size and build the PDF.",
    ],
    features: [
      "Uses the rear camera on phones automatically",
      "Grayscale mode for smaller, more readable scans",
      "Capture as many pages as you like, remove any of them",
      "A4, Letter or fit-to-photo pages",
      "No app to install and nothing uploaded",
    ],
    faqs: [
      {
        q: "Do I need to install an app?",
        a: "No. It uses the camera API built into your browser. Nothing is installed and nothing is uploaded.",
      },
      {
        q: "Why does it ask for camera permission?",
        a: "Because a web page cannot access a camera without your explicit consent. The stream is released the moment you close the camera, and only the frames you deliberately capture are kept.",
      },
      {
        q: "It says no camera was found.",
        a: "Either the device has no camera, the page is not on a secure connection, or another app is using it. You can build the same PDF from photos you have already taken with the Image to PDF tool.",
      },
      {
        q: "Can I make the scans searchable?",
        a: "Yes — run the finished PDF through PDF OCR, which adds recognised text you can copy.",
      },
    ],
  },
  {
    id: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    short: "Turn a PDF into a slide deck you can present.",
    long: "Renders every page and builds a real .pptx where each page fills one slide. The deck opens in PowerPoint, Keynote and Google Slides and is ideal for presenting from or annotating over. Pages become pictures, not editable text boxes — the page says so plainly.",
    category: "pdf",
    route: "/tools/pdf-to-powerpoint",
    keywords: ["pdf to powerpoint", "pdf to pptx", "pdf to slides", "convert pdf to presentation", "pdf to ppt"],
    aliases: ["pdf to ppt", "pdf to pptx", "pdf to slides"],
    icon: "📊",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["pdf-to-word", "pdf-to-jpg", "pdf-to-markdown", "pdf-organize"],
    seoTitle: "PDF to PowerPoint — Convert PDF to PPTX Free | DO101",
    seoDescription: "Convert a PDF into a real PowerPoint .pptx deck with one page per slide. Opens in PowerPoint, Keynote and Google Slides. Free and entirely in your browser.",
    steps: [
      "Add your PDF.",
      "Choose a slide resolution.",
      "Convert and download the .pptx.",
    ],
    features: [
      "Produces a genuine .pptx package",
      "One page per full-bleed slide",
      "Slide size follows your document's aspect ratio",
      "Opens in PowerPoint, Keynote and Google Slides",
      "Built on your device — nothing uploaded",
    ],
    faqs: [
      {
        q: "Will the text be editable in PowerPoint?",
        a: "No, and that is stated before you convert. Each page becomes a picture on a slide. Turning a PDF page back into editable shapes requires layout analysis that a browser cannot do reliably, and a converter that faked it would give you a mangled deck.",
      },
      {
        q: "What is it good for then?",
        a: "Presenting a document, annotating over it during a talk, or dropping PDF pages into an existing deck. Those are the things people actually want this for.",
      },
      {
        q: "Which slide size does it use?",
        a: "The deck matches your PDF's aspect ratio, so pages fill the slide with no letterboxing.",
      },
      {
        q: "Is there a page limit?",
        a: "100 slides per run, which keeps the browser responsive. Split longer documents first.",
      },
    ],
  },
];
