import type { Tool } from "../types";

/**
 * Text tools. Pure string work, so every one of them runs locally.
 */
export const TEXT_TOOLS: Tool[] = [
  {
    id: "word-counter",
    name: "Word Counter",
    short: "Live word, character, sentence and reading-time counts.",
    long:
      "Paste or type text and see the word count update as you go, along with characters, sentences, paragraphs, reading time and speaking time. Useful for essays, assignments, meta descriptions and social posts.",
    category: "text",
    route: "/tools/word-counter",
    keywords: ["word counter", "count words", "word count", "essay word count", "character count", "reading time"],
    aliases: ["count words", "how many words", "wordcount"],
    icon: "🔢",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["character-counter", "text-cleaner", "case-converter", "text-diff"],
    seoTitle: "Free Word Counter — Words, Characters & Reading Time | DO101",
    seoDescription:
      "Count words, characters, sentences and paragraphs instantly. Includes reading time, speaking time and keyword density. Free and browser-based.",
    steps: ["Paste or type your text.", "Read the live counts as you edit.", "Copy the cleaned text or the statistics if you need them."],
    features: [
      "Words, characters, sentences, paragraphs and lines",
      "Reading time and speaking time estimates",
      "Top keyword density",
      "Longest word and average word length",
      "Nothing is sent anywhere — the counter runs locally",
    ],
    faqs: [
      { q: "How is a word counted?", a: "Any run of characters separated by whitespace counts as one word. Hyphenated words such as \"well-known\" count as a single word, matching how most word processors behave." },
      { q: "How is reading time calculated?", a: "Reading time assumes 225 words per minute, a common average for adult silent reading. Speaking time assumes 130 words per minute." },
      { q: "Is my text stored?", a: "No. The text stays in the page. Nothing is uploaded and nothing is saved unless you copy it yourself." },
    ],
    featured: true,
  },
  {
    id: "character-counter",
    name: "Character Counter",
    short: "Count characters with live limits for tweets, SEO and SMS.",
    long:
      "Count characters with and without spaces, and watch progress bars for the limits that matter: X posts, SEO titles, meta descriptions and SMS segments. Perfect for anything with a hard character budget.",
    category: "text",
    route: "/tools/character-counter",
    keywords: ["character counter", "count characters", "letter count", "twitter character count", "meta description length", "sms character count"],
    aliases: ["count letters", "char count", "how many characters"],
    icon: "🅰️",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["word-counter", "text-cleaner", "case-converter", "text-diff"],
    seoTitle: "Free Character Counter — With & Without Spaces | DO101",
    seoDescription:
      "Count characters online with and without spaces, plus live limits for X posts, SEO titles, meta descriptions and SMS. Free, instant, private.",
    steps: ["Paste your text.", "Watch the counters and limit bars update.", "Trim until every bar is inside its limit."],
    features: [
      "Characters with and without spaces",
      "Live limit bars for X, SEO title, meta description and SMS",
      "Counts emoji correctly using grapheme-aware counting",
      "Byte size in UTF-8",
      "Runs entirely in your browser",
    ],
    faqs: [
      { q: "Why do emoji count as more than one character?", a: "Many emoji are built from several Unicode code points. DO101 shows both the visible character count (what a human sees) and the raw code-unit count that most APIs enforce." },
      { q: "What is the ideal meta description length?", a: "Google typically renders around 155–160 characters on desktop. DO101 warns you as you approach that range." },
    ],
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    short: "Strip double spaces, blank lines and messy formatting.",
    long:
      "Paste text copied from a PDF, an email or a website and tidy it with one click. Remove duplicate spaces, empty lines, line breaks inside paragraphs, smart quotes and invisible characters — you choose which fixes to apply.",
    category: "text",
    route: "/tools/text-cleaner",
    keywords: ["text cleaner", "remove extra spaces", "remove line breaks", "remove blank lines", "clean text", "remove formatting"],
    aliases: ["clean up text", "remove double spaces", "tidy text"],
    icon: "🧹",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["word-counter", "case-converter", "text-diff", "character-counter"],
    seoTitle: "Free Text Cleaner — Remove Extra Spaces & Line Breaks | DO101",
    seoDescription:
      "Clean messy text online: remove duplicate spaces, blank lines, line breaks, smart quotes and invisible characters. Free and browser-based.",
    steps: ["Paste the messy text.", "Toggle the fixes you want.", "Copy the cleaned result."],
    features: [
      "Collapse duplicate spaces and tabs",
      "Remove blank lines and trailing whitespace",
      "Join broken paragraph line breaks",
      "Convert smart quotes and dashes to plain ASCII",
      "Strip zero-width and invisible characters",
    ],
    faqs: [
      { q: "Why does text copied from a PDF have odd line breaks?", a: "PDFs store text line by line, so a copy carries a hard break at the end of every visual line. The \"join wrapped lines\" option rebuilds the paragraphs." },
      { q: "What are invisible characters?", a: "Zero-width spaces and joiners sometimes ride along with copied text and break search, code and form validation. The cleaner removes them." },
    ],
  },
  {
    id: "text-diff",
    name: "Text Diff Checker",
    short: "Compare two texts and highlight every change.",
    long:
      "Paste an original and a revised version to see exactly what was added, removed or left alone. DO101 shows a word-level diff so a single changed word does not light up the whole line.",
    category: "text",
    route: "/tools/text-diff",
    keywords: ["text diff", "compare text", "diff checker", "text comparison", "compare two documents", "find differences"],
    aliases: ["compare two texts", "difference checker", "text compare"],
    icon: "🔍",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["text-cleaner", "word-counter", "json-formatter", "case-converter"],
    seoTitle: "Free Text Diff Checker — Compare Two Texts Online | DO101",
    seoDescription:
      "Compare two blocks of text and highlight additions and deletions word by word. Free online diff checker that runs in your browser.",
    steps: ["Paste the original text on the left.", "Paste the changed text on the right.", "Read the highlighted diff underneath."],
    features: ["Word-level highlighting", "Added / removed / unchanged counts", "Ignore case and whitespace options", "Works with long documents", "Nothing leaves your browser"],
    faqs: [
      { q: "Can I compare code?", a: "Yes. Word-level diffing works well for code, though for very large files a dedicated Git diff will be faster." },
      { q: "Is there a size limit?", a: "The comparison is capped to keep the page responsive; extremely large documents are trimmed with a clear warning rather than freezing the tab." },
    ],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    short: "Switch text between UPPER, lower, Title, camel, snake and kebab.",
    long:
      "Convert text between every case you need: sentence case, lowercase, UPPERCASE, Title Case, camelCase, PascalCase, snake_case, kebab-case and CONSTANT_CASE. Handy for writing and for renaming variables.",
    category: "text",
    route: "/tools/case-converter",
    keywords: ["case converter", "uppercase", "lowercase", "title case", "camel case", "snake case", "kebab case", "change text case"],
    aliases: ["uppercase converter", "capitalize text", "change case"],
    icon: "🔤",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["text-cleaner", "word-counter", "character-counter", "uuid-generator"],
    seoTitle: "Free Case Converter — Upper, Lower, Title & camelCase | DO101",
    seoDescription:
      "Convert text to uppercase, lowercase, sentence case, Title Case, camelCase, snake_case or kebab-case instantly. Free and private.",
    steps: ["Paste your text.", "Tap the case you want.", "Copy the converted result."],
    features: ["Nine case styles", "One-tap copy", "Preserves acronyms in Title Case where sensible", "Works on long text", "In-browser only"],
    faqs: [
      { q: "What is the difference between Title Case and Capitalized Case?", a: "Title Case leaves short joining words such as \"of\" and \"and\" lowercase unless they start the title. Capitalized Case capitalises every word." },
      { q: "Which case should I use for code?", a: "camelCase for JavaScript variables, PascalCase for classes and React components, snake_case for Python, kebab-case for URLs and CSS classes." },
    ],
  },
  {
    id: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    short: "Strip repeated lines out of a list.",
    long: "Paste a list and every repeat disappears, keeping the first occurrence and the original order. Case and surrounding spaces can be ignored, which is what usually causes \"duplicates\" that other tools miss.",
    category: "text",
    route: "/tools/remove-duplicate-lines",
    keywords: ["remove duplicate lines", "delete duplicate lines", "unique lines", "dedupe list", "remove repeated lines"],
    aliases: ["dedupe lines", "unique list", "remove repeats"],
    icon: "🧾",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["remove-empty-lines", "text-sorter", "text-cleaner", "word-counter"],
    seoTitle: "Remove Duplicate Lines — Free Online Deduplicator | DO101",
    seoDescription: "Remove duplicate lines from any list, with options to ignore case and surrounding spaces. Free, instant, and runs entirely in your browser.",
    steps: [
      "Paste your list.",
      "Choose whether case and spacing should matter.",
      "Copy the deduplicated result.",
    ],
    features: [
      "Keeps the first occurrence and the original order",
      "Optional case-insensitive matching",
      "Optional whitespace-insensitive matching",
      "Counts exactly how many duplicates were removed",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Which copy is kept?",
        a: "The first one. Everything after it in the list is dropped, so the original order is preserved.",
      },
      {
        q: "Why are my \"identical\" lines not matching?",
        a: "Usually a trailing space or a capital letter. Turn on \"ignore surrounding spaces\" and turn off \"case sensitive\" and they will match.",
      },
      {
        q: "Is there a size limit?",
        a: "Only your browser's memory. Lists of tens of thousands of lines process instantly.",
      },
    ],
  },
  {
    id: "remove-empty-lines",
    name: "Remove Empty Lines",
    short: "Delete blank lines from any block of text.",
    long: "Removes every empty line — including lines that only contain spaces or tabs, which look empty but usually are not. Useful for tidying exported data, pasted text and generated lists.",
    category: "text",
    route: "/tools/remove-empty-lines",
    keywords: ["remove empty lines", "delete blank lines", "remove line breaks", "strip blank lines"],
    aliases: ["delete blank lines", "remove whitespace lines"],
    icon: "📉",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["remove-duplicate-lines", "remove-extra-spaces", "text-cleaner", "text-sorter"],
    seoTitle: "Remove Empty Lines — Free Blank Line Remover | DO101",
    seoDescription: "Delete blank and whitespace-only lines from text instantly. Free online tool with no sign-up, running entirely in your browser.",
    steps: [
      "Paste the text with gaps in it.",
      "Choose whether whitespace-only lines count as empty.",
      "Copy the tightened result.",
    ],
    features: [
      "Removes truly empty and whitespace-only lines",
      "Counts how many lines were removed",
      "Preserves the order of everything else",
      "One-tap copy and download",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "What is a whitespace-only line?",
        a: "A line containing just spaces or tabs. It looks blank but is not, which is why some tools leave it behind. DO101 removes it by default.",
      },
      {
        q: "Can I collapse runs of blank lines instead of deleting them all?",
        a: "Yes — use the Text Cleaner, which can reduce several blank lines to one rather than removing them entirely.",
      },
    ],
  },
  {
    id: "remove-extra-spaces",
    name: "Remove Extra Spaces",
    short: "Collapse double spaces and trim stray whitespace.",
    long: "Turns runs of spaces into one, trims the start and end of every line, and collapses long gaps between paragraphs. The classic fix for text pasted out of a PDF or an email.",
    category: "text",
    route: "/tools/remove-extra-spaces",
    keywords: ["remove extra spaces", "remove double spaces", "trim whitespace", "fix spacing in text"],
    aliases: ["fix double spaces", "trim spaces", "clean up spacing"],
    icon: "␣",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["text-cleaner", "remove-empty-lines", "word-counter", "find-and-replace"],
    seoTitle: "Remove Extra Spaces — Free Whitespace Cleaner | DO101",
    seoDescription: "Collapse double spaces, trim line ends and tidy paragraph gaps in one click. Free online whitespace cleaner that runs in your browser.",
    steps: [
      "Paste the messy text.",
      "Pick which whitespace fixes to apply.",
      "Copy the tidied result.",
    ],
    features: [
      "Collapses repeated spaces and tabs",
      "Trims the start and end of each line",
      "Collapses runs of blank lines",
      "Shows how many characters were removed",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Why does pasted text have double spaces?",
        a: "Old typing convention put two spaces after a full stop, and PDF and email clients often add their own. Modern typesetting uses one.",
      },
      {
        q: "Will it break my indentation?",
        a: "Turn off \"trim the start and end of each line\" if you are working with indented code or poetry.",
      },
    ],
  },
  {
    id: "text-sorter",
    name: "Text Sorter",
    short: "Sort lines alphabetically, numerically or by length.",
    long: "Sort a list eight different ways — A→Z, Z→A, by number, by line length, reversed or shuffled — with proper natural ordering so \"item 10\" comes after \"item 9\" rather than after \"item 1\".",
    category: "text",
    route: "/tools/text-sorter",
    keywords: ["sort lines", "alphabetical sorter", "sort list online", "sort text", "sort numbers"],
    aliases: ["alphabetise list", "sort a list", "order lines"],
    icon: "🔡",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["remove-duplicate-lines", "text-reverser", "remove-empty-lines", "text-extractor"],
    seoTitle: "Text Sorter — Sort Lines Alphabetically Online Free | DO101",
    seoDescription: "Sort lines A–Z, Z–A, numerically, by length, reversed or shuffled, with natural number ordering. Free and running entirely in your browser.",
    steps: [
      "Paste your list.",
      "Choose how to sort it.",
      "Copy the sorted result.",
    ],
    features: [
      "Eight sort modes including shuffle",
      "Natural ordering so item 10 follows item 9",
      "Optional case sensitivity",
      "Can remove duplicates while sorting",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "What is natural ordering?",
        a: "It treats digits inside text as numbers, so \"file2\" sorts before \"file10\". A plain character sort would put \"file10\" first, which is almost never what you want.",
      },
      {
        q: "Is the shuffle random?",
        a: "It uses a Fisher–Yates shuffle with the browser's random source, so every ordering is equally likely.",
      },
    ],
  },
  {
    id: "text-reverser",
    name: "Text Reverser",
    short: "Reverse characters, words, lines or letters in each word.",
    long: "Four different reversals in one tool: flip the whole string, reverse the order of the words, reverse the order of the lines, or flip the letters inside each word while leaving the words in place.",
    category: "text",
    route: "/tools/text-reverser",
    keywords: ["reverse text", "backwards text", "reverse words", "flip text", "mirror text"],
    aliases: ["backwards text generator", "flip text", "reverse string"],
    icon: "↩️",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["text-sorter", "case-converter", "text-cleaner", "find-and-replace"],
    seoTitle: "Reverse Text — Flip Characters, Words or Lines Free | DO101",
    seoDescription: "Reverse text four ways: every character, word order, line order, or the letters inside each word. Free, instant and entirely in your browser.",
    steps: [
      "Paste your text.",
      "Choose what to reverse.",
      "Copy the reversed result.",
    ],
    features: [
      "Four reversal modes",
      "Handles emoji and accented characters correctly",
      "Works on single lines or whole documents",
      "One-tap copy",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "Does it handle emoji correctly?",
        a: "Yes. Reversal iterates by code point rather than by UTF-16 unit, so emoji and accented characters do not break apart.",
      },
      {
        q: "What is this actually for?",
        a: "Puzzles and word games, testing how software handles right-to-left or unusual input, and occasionally reversing a log file so the newest entries come first.",
      },
    ],
  },
  {
    id: "find-and-replace",
    name: "Find and Replace",
    short: "Swap text across a whole document, with regex if you need it.",
    long: "Replace every occurrence of a word or pattern, with optional case sensitivity, whole-word matching and full regular expression support. It reports exactly how many replacements were made so nothing happens silently.",
    category: "text",
    route: "/tools/find-and-replace",
    keywords: ["find and replace", "replace text online", "bulk find replace", "regex replace", "search and replace"],
    aliases: ["search and replace", "swap text", "replace words"],
    icon: "🔁",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["regex-tester", "text-cleaner", "remove-extra-spaces", "text-extractor"],
    seoTitle: "Find and Replace Text Online — Free, With Regex | DO101",
    seoDescription: "Find and replace text with optional case sensitivity, whole-word matching and regular expressions. Shows the replacement count. Free and private.",
    steps: [
      "Paste your text.",
      "Type what to find and what to replace it with.",
      "Check the replacement count, then copy the result.",
    ],
    features: [
      "Plain text or regular expression matching",
      "Case-sensitive and whole-word options",
      "Live replacement count",
      "Leave the replacement blank to delete matches",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "How do I delete text instead of replacing it?",
        a: "Leave the \"replace with\" box empty. Every match is removed.",
      },
      {
        q: "Can I use capture groups?",
        a: "Yes. Turn on regular expressions and reference groups as $1, $2 and so on in the replacement.",
      },
      {
        q: "Why does my search match too much?",
        a: "Turn on \"whole words only\". Without it, searching for \"cat\" also matches \"category\".",
      },
    ],
  },
  {
    id: "text-extractor",
    name: "Text Extractor",
    short: "Pull emails, URLs, numbers or IPs out of any text.",
    long: "Point it at an email, a log file or a page of HTML and get back a clean list of just the emails, links, numbers, IP addresses, hashtags or mentions inside it — deduplicated and optionally sorted.",
    category: "text",
    route: "/tools/text-extractor",
    keywords: ["extract emails from text", "extract urls", "email extractor", "find links in text", "extract numbers"],
    aliases: ["email extractor", "url extractor", "pull emails out of text"],
    icon: "🎣",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["find-and-replace", "regex-tester", "text-cleaner", "remove-duplicate-lines"],
    seoTitle: "Text Extractor — Pull Emails, URLs & Numbers from Text | DO101",
    seoDescription: "Extract email addresses, URLs, numbers, IP addresses, hashtags and mentions from any text. Deduplicated, sortable, free and browser-based.",
    steps: [
      "Paste the text to search.",
      "Choose what to extract.",
      "Copy the clean list.",
    ],
    features: [
      "Seven extraction types",
      "Automatic deduplication",
      "Optional alphabetical sorting",
      "Counts what it found",
      "Runs in your browser — safe for private text",
    ],
    faqs: [
      {
        q: "Does it catch every email format?",
        a: "It matches the ordinary shapes people actually use. Exotic but technically legal addresses, such as those with quoted local parts, may be missed.",
      },
      {
        q: "Is this for scraping addresses?",
        a: "Please do not use it to build unsolicited mailing lists. It exists for tidying data you already hold — pulling links from your own notes, addresses from a document you own.",
      },
      {
        q: "Is my text sent anywhere?",
        a: "No. Extraction runs on your device, which is why it is safe to paste a private email into it.",
      },
    ],
  },
  {
    id: "markdown-to-html",
    name: "Markdown to HTML",
    short: "Convert Markdown into clean HTML.",
    long: "Parses Markdown with the CommonMark-compliant marked library, including GitHub extensions like tables, task lists and strikethrough, and returns the HTML it produces.",
    category: "text",
    route: "/tools/markdown-to-html",
    keywords: ["markdown to html", "md to html", "convert markdown", "markdown converter", "markdown parser"],
    aliases: ["md to html", "render markdown"],
    icon: "⬇️",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["html-to-markdown", "markdown-to-pdf", "html-encoder", "html-minifier"],
    seoTitle: "Markdown to HTML Converter — Free Online Tool | DO101",
    seoDescription: "Convert Markdown to HTML with GitHub-flavoured extensions including tables and task lists. Free, instant, and running in your browser.",
    steps: [
      "Paste your Markdown.",
      "Choose how single newlines are treated.",
      "Copy the HTML.",
    ],
    features: [
      "CommonMark plus GitHub extensions",
      "Tables, task lists and strikethrough",
      "Optional GitHub-style line breaks",
      "Copy or download as .html",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "What is the line break option for?",
        a: "CommonMark treats a single newline as a space, so a line break needs two trailing spaces. GitHub turns every newline into a <br>. Choose whichever matches where the Markdown came from.",
      },
      {
        q: "Is the HTML sanitised?",
        a: "No — the output is exactly what your Markdown produces, including any raw HTML you embedded. Sanitise it yourself before rendering untrusted content.",
      },
    ],
  },
  {
    id: "html-to-markdown",
    name: "HTML to Markdown",
    short: "Turn HTML back into clean Markdown.",
    long: "Converts HTML into readable Markdown with Turndown, handling headings, lists, links, images, code blocks and emphasis. Ideal for moving content out of a CMS and into a repository.",
    category: "text",
    route: "/tools/html-to-markdown",
    keywords: ["html to markdown", "convert html to markdown", "html md converter", "web page to markdown"],
    aliases: ["html to md", "turn html into markdown"],
    icon: "⬆️",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["markdown-to-html", "markdown-to-pdf", "html-decoder", "text-cleaner"],
    seoTitle: "HTML to Markdown Converter — Free Online Tool | DO101",
    seoDescription: "Convert HTML into clean Markdown with configurable heading and bullet styles. Free, instant and processed entirely in your browser.",
    steps: [
      "Paste your HTML.",
      "Choose heading and bullet styles.",
      "Copy the Markdown.",
    ],
    features: [
      "Headings, lists, links, images and code blocks",
      "ATX or Setext heading style",
      "Choice of bullet marker",
      "Fenced code blocks",
      "Runs in your browser",
    ],
    faqs: [
      {
        q: "What happens to elements Markdown cannot express?",
        a: "Things like styled divs or iframes are kept as inline HTML, which is valid inside Markdown, rather than being thrown away.",
      },
      {
        q: "Do tables convert?",
        a: "Simple tables convert to Markdown tables. Tables with merged cells cannot be represented in Markdown and stay as HTML.",
      },
    ],
  },
];
