import type { Tool } from "../types";

/**
 * Work tools: turning meetings, messages and notes into tasks, plans, reports
 * and replies.
 *
 * None of these calls an AI service or stores anything on a server. They are
 * rule-based and run in the visitor's browser, so they are free to offer and
 * private by construction — and their copy says so rather than borrowing the
 * word "AI" for something that is not.
 */
export const WORK_TOOLS: Tool[] = [
  {
    id: "meeting-action-items",
    name: "Meeting Notes to Action Items",
    short: "Turn meeting notes or a transcript into tasks, owners, deadlines and a follow-up email.",
    long:
      "Paste your meeting notes or a Zoom, Teams or Google Meet transcript and get back the action items — who is doing what, and by when — plus the decisions made and the questions still open. Owners are worked out from who spoke and who was asked, deadlines from phrases like \"by Friday\" or \"明日まで\", and every result shows the sentence it came from. Edit anything, then download an Excel tracker, Word minutes, a calendar file of the deadlines, or copy a ready-made follow-up email. It runs entirely in your browser with no AI service and nothing uploaded.",
    category: "productivity",
    route: "/tools/meeting-action-items",
    keywords: [
      "meeting action items", "meeting notes to tasks", "action item extractor", "meeting minutes template",
      "meeting follow up email", "zoom transcript action items", "teams transcript summary", "meeting notes organizer",
      "who does what by when", "meeting tasks and deadlines",
    ],
    aliases: ["meeting minutes", "action items", "meeting summary", "ai meeting notes", "meeting to do list", "議事録", "議事録 タスク"],
    icon: "🗒️",
    accent: "grass",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "file",
    related: ["task-extractor", "work-report-generator", "daily-planner", "what-did-i-miss"],
    seoTitle: "Meeting Notes to Action Items — Tasks, Owners & Deadlines | DO101",
    seoDescription:
      "Paste meeting notes or a Zoom or Teams transcript and get action items with owners and deadlines, decisions and a follow-up email. Export to Excel, Word or calendar.",
    steps: [
      "Paste your notes or transcript, or open a .txt, .docx or .vtt file.",
      "Add your name to see which tasks are yours.",
      "Check the action items, decisions and open questions — open \"why\" on any row to see the rule that found it.",
      "Fix an owner or date, or add a task the rules missed.",
      "Download an Excel tracker, Word minutes or a calendar file, or copy the follow-up email.",
    ],
    features: [
      "Finds commitments (\"I'll send…\"), requests (\"can you…\"), marked actions and checkboxes",
      "Works out owners from speakers, names and @mentions",
      "Reads deadlines like \"by Friday\", \"EOD\", \"next Tuesday\" and \"明日まで\"",
      "Separates decisions and open questions from tasks",
      "Reads Zoom, Teams and Meet transcripts, and English or Japanese notes",
      "Every result shows the sentence and the rule behind it",
      "Excel tracker, Word minutes, calendar (.ics) and CSV downloads",
      "A follow-up email grouped by owner, ready to paste",
      "No AI service, no account, nothing uploaded",
    ],
    faqs: [
      { q: "Is this an AI meeting assistant?", a: "No — deliberately. It uses clear rules to find tasks, owners and deadlines, which means it is instant, free, and your meeting notes never leave your browser. The trade-off is that unusual phrasing can be missed, so every result is editable and you can add tasks by hand before exporting." },
      { q: "Which transcript formats does it read?", a: "Plain \"Name: text\" notes, timestamped chat exports, Slack-style name-and-time lines, WebVTT files from Zoom, Teams and Google Meet, and Word documents. Speaker names help it assign owners, but it works without them too." },
      { q: "How does it decide who owns a task?", a: "If someone says \"I'll do it\", it is theirs. If someone is asked by name or @mentioned, it is the person asked. In a two-person conversation, \"can you…\" goes to the other person. Where nobody is named it is left unassigned rather than guessed." },
      { q: "Can I put the deadlines in my calendar?", a: "Yes. The calendar download is a standard .ics file with one entry per dated task, which imports into Google Calendar, Outlook and Apple Calendar." },
      { q: "Does it work with Japanese meeting notes?", a: "Yes. It recognises requests like 〜お願いします and 〜してください, commitments like 〜します and 〜いたします, and deadlines like 明日まで, 本日中 and 来週金曜日." },
      { q: "Where are my notes stored?", a: "Nowhere. They are processed in this page and forgotten when you leave. The files you download are the only record, and DO101 keeps no copy." },
    ],
  },
  {
    id: "task-extractor",
    name: "Email & Chat Task Extractor",
    short: "Find every request and commitment buried in emails or Slack, and list what is yours first.",
    long:
      "Paste an email thread, a Slack or Teams channel, or a chat export and get one prioritised list of every request and commitment in it — with the things asked of you at the top. Each task gets an owner, a deadline where one was mentioned, and a priority from words like \"urgent\" and how soon it is due. Quoted replies are skipped so nothing is counted twice. Edit the list, then download it as Excel, put the deadlines in your calendar, or send it straight into the Daily Work Planner. Nothing is uploaded and no AI service is used.",
    category: "productivity",
    route: "/tools/task-extractor",
    keywords: [
      "email task extractor", "slack task list", "extract tasks from email", "action items from email",
      "to do list from messages", "email follow up list", "prioritise tasks from email", "chat to task list",
      "commitments tracker", "requests from inbox",
    ],
    aliases: ["email to do list", "slack action items", "inbox tasks", "ai task extractor", "what do i need to do"],
    icon: "📥",
    accent: "sky",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "file",
    related: ["meeting-action-items", "daily-planner", "what-did-i-miss", "follow-up-tracker"],
    seoTitle: "Extract Tasks from Emails & Slack — Prioritised To-Do List | DO101",
    seoDescription:
      "Paste emails or Slack messages and get every request and commitment as a prioritised to-do list, with what is yours first. Export to Excel or calendar. Free, private.",
    steps: [
      "Enter your name so requests to you are flagged.",
      "Paste an email thread or chat, or open a saved file.",
      "Read the list, most urgent first, and switch to \"Only mine\" to focus.",
      "Correct anything, then download Excel or calendar deadlines — or copy the list into the Daily Planner.",
    ],
    features: [
      "Reads email headers (From, Date, Subject) and skips quoted replies",
      "Reads Slack, Teams and timestamped chat exports",
      "Requests to you are flagged and can be filtered",
      "Priority from urgency words and how soon a task is due",
      "Deadlines read from ordinary phrases in English and Japanese",
      "Excel, CSV and calendar downloads",
      "One click to plan the tasks into your day",
      "Nothing leaves your browser",
    ],
    faqs: [
      { q: "Does it connect to my Gmail, Outlook or Slack?", a: "No. You paste the messages you want checked. That is what lets it run with no account, no permissions and no server — and nothing you paste is sent anywhere." },
      { q: "How does it know a task is for me?", a: "Enter your name. Requests that name you, @mention you, or — in a two-person thread — are addressed to you are flagged, and \"Only mine\" shows just those." },
      { q: "How is priority decided?", a: "Words like urgent, ASAP, critical or 至急 make it high. Otherwise, a deadline within a day is high and within five days is medium. You can change any priority by hand." },
      { q: "Why was something missed?", a: "The rules look for requests (\"could you…\", \"please…\"), commitments (\"I'll…\") and instructions. A task hidden in an unusual sentence can slip through, so skim the messages once and add anything missing." },
      { q: "Can I use it in Japanese?", a: "Yes — Japanese requests, commitments and deadlines are recognised alongside English ones." },
    ],
  },
  {
    id: "daily-planner",
    name: "Daily Work Planner",
    short: "Fit your tasks around today's meetings into a plan you can actually follow.",
    long:
      "List your tasks with rough time estimates, add the meetings you already have — or import them from a calendar file — and get a realistic, time-blocked plan for the day. Urgent and due-today work goes first, long focused tasks go into the morning if you want, breaks are built in, and a share of the day is kept free for the interruptions that always come. Whatever does not fit is listed plainly instead of being squeezed in. Download the plan to your calendar, Excel or a printable Word page. It runs in your browser with no account.",
    category: "productivity",
    route: "/tools/daily-planner",
    keywords: [
      "daily planner", "time blocking planner", "daily schedule maker", "plan my day", "work day planner",
      "time block schedule", "daily task planner", "prioritize tasks", "realistic to do list", "calendar planner",
    ],
    aliases: ["plan my day", "time blocking", "schedule my tasks", "day plan", "ai daily planner", "1日の計画"],
    icon: "🗓️",
    accent: "sun",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "file",
    related: ["task-extractor", "meeting-action-items", "calendar", "notes"],
    seoTitle: "Daily Work Planner — Time-Block Your Day Around Meetings | DO101",
    seoDescription:
      "Free daily planner that time-blocks your tasks around your meetings, adds breaks, keeps time for interruptions and shows what will not fit. Export to your calendar.",
    steps: [
      "List tasks, one per line, with a time like (1h) or 30m. Add !! for urgent or \"by Friday\" for a deadline.",
      "Type today's meetings, or import a .ics file exported from your calendar.",
      "Adjust your hours, lunch, breaks and how much of the day to keep free.",
      "Read the plan and the list of what does not fit.",
      "Download it to your calendar, Excel or Word, or copy it as text.",
    ],
    features: [
      "Time-blocks tasks around fixed meetings and lunch",
      "Due-today and urgent tasks first, then by deadline",
      "Long, focused work in the morning if you choose",
      "Breaks after long stretches of focus",
      "Keeps a share of the day unplanned for interruptions",
      "Splits long tasks around meetings",
      "Honest list of what does not fit",
      "Imports meetings from a calendar .ics file",
      "Calendar, Excel and printable Word exports",
    ],
    faqs: [
      { q: "Why does it leave part of my day empty?", a: "Because every working day has interruptions — messages, quick questions, things taking longer. Planning every minute guarantees falling behind by mid-morning. The share kept free is adjustable, and set to 0% if you really want a full plan." },
      { q: "What happens when my tasks do not fit?", a: "They are listed separately with how much time is left on each. That is the most useful part of a plan: it tells you now, not at 5pm, what to move, hand on or drop." },
      { q: "How do I get my meetings in?", a: "Type them as \"10:00-10:30 Standup\", or export a .ics file from Google Calendar, Outlook or Apple Calendar and import it. The file is read in your browser and never uploaded." },
      { q: "Will importing the plan duplicate my meetings?", a: "No. The calendar download contains only your task blocks, so your existing meetings are not added twice." },
      { q: "How does it decide the order?", a: "Anything due today first, then urgent tasks, then by deadline, with hour-plus tasks placed early if you turn on \"long, focused tasks first\"." },
    ],
  },
  {
    id: "sop-generator",
    name: "SOP Generator",
    short: "Turn rough notes on how something is done into a numbered, formatted SOP in Word.",
    long:
      "Describe a process the way you would explain it to a new colleague — \"log in to the portal, then export last month, make sure it's in yen, and if it's empty ask finance\" — and get a proper standard operating procedure: numbered steps, warnings and decision points attached to the right step, prerequisites, roles and the systems involved. Edit and reorder the steps, add a purpose and scope, then download a formatted Word document with an owner, version and revision history, or copy it as Markdown for Notion or Confluence. Runs in your browser, with nothing uploaded.",
    category: "productivity",
    route: "/tools/sop-generator",
    keywords: [
      "sop generator", "standard operating procedure template", "sop template word", "process documentation",
      "how to write an sop", "work instructions template", "procedure writer", "step by step guide maker",
      "business process documentation", "sop example",
    ],
    aliases: ["sop", "standard operating procedure", "process document", "work instructions", "ai sop generator", "手順書", "業務マニュアル"],
    icon: "📘",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "file",
    related: ["work-report-generator", "meeting-action-items", "canvas", "notes"],
    seoTitle: "SOP Generator — Turn Notes into a Standard Operating Procedure | DO101",
    seoDescription:
      "Free SOP generator: describe a process in plain words and get numbered steps, warnings, decisions, roles and systems, downloaded as a formatted Word document.",
    steps: [
      "Give the procedure a name, an owner and a version.",
      "Describe the process in your own words, or open a document with the notes.",
      "Check the steps — warnings and \"if…\" conditions are attached to the step they belong to.",
      "Edit, reorder, add or remove steps, and add a purpose and scope.",
      "Download the Word document or copy it as Markdown.",
    ],
    features: [
      "Splits notes into steps at \"then\", \"next\", \"after that\", \"次に\" and new lines",
      "Attaches warnings (\"make sure\", \"never\", \"必ず\") to the right step",
      "Turns \"if…\" sentences into decision points",
      "Lists prerequisites, roles and systems",
      "Editable, reorderable steps",
      "Word document with owner, version, procedure table and revision history",
      "Markdown for Notion, Confluence or GitHub",
      "Nothing uploaded",
    ],
    faqs: [
      { q: "What is an SOP?", a: "A standard operating procedure: the written, step-by-step way a recurring task is done, so it is done the same way whoever does it. Good SOPs are numbered, name who does each step, and call out the checks and decisions along the way." },
      { q: "Can it watch a screen recording and write the SOP?", a: "No. That needs an AI service, and this tool uses none. It works from text — so the quickest route is to talk through the process while someone types, or paste notes you already have." },
      { q: "How are warnings and decisions detected?", a: "Sentences with words like \"make sure\", \"never\", \"always\" or \"必ず\" become warnings on the step before them. Sentences starting \"if\", \"when\" or \"otherwise\" become decision points. You can edit or add both." },
      { q: "What does the Word document contain?", a: "A title, an owner/version/date block, purpose and scope if you add them, roles, systems, prerequisites, a numbered procedure table with who and checks, and a revision history table." },
      { q: "Does it work in Japanese?", a: "Yes — Japanese sequence words like 次に, その後 and 最後に split steps, and 必ず and 注意 mark warnings." },
    ],
  },
  {
    id: "customer-inquiry-replies",
    name: "Customer Inquiry Reply Helper",
    short: "Answer repeat customer questions from your own FAQ, in English or Japanese.",
    long:
      "Keep your answers to the questions customers ask again and again — opening hours, prices, bookings, parking, cancellations — in an FAQ you own, saved as an Excel file. Paste an incoming email or message and each question in it is matched to your answers, with synonyms, and a reply is drafted in a friendly or formal tone. Questions without a good answer are not guessed at: the reply says you will check, and the question can be added to your FAQ in one click. Starter templates for hotels, clinics, restaurants, agencies and shops, and Japanese replies in business register. No AI service, nothing uploaded.",
    category: "productivity",
    route: "/tools/customer-inquiry-replies",
    keywords: [
      "customer inquiry reply", "faq reply generator", "customer service reply templates", "email reply templates",
      "hotel inquiry response", "restaurant reservation reply", "clinic faq", "canned responses",
      "customer support templates", "reply to customer email",
    ],
    aliases: ["customer replies", "faq answers", "canned responses", "ai customer service reply", "問い合わせ 返信", "よくある質問"],
    icon: "💬",
    accent: "sky",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "text",
    related: ["follow-up-tracker", "japanese-workplace", "meeting-action-items", "document-search"],
    seoTitle: "Customer Inquiry Reply Helper — Answer FAQs Fast, Free | DO101",
    seoDescription:
      "Answer repeat customer questions from your own FAQ. Paste an inquiry, get a drafted reply in English or Japanese, and never guess where you have no answer.",
    steps: [
      "Load a starter template for your type of business, or open your saved FAQ file.",
      "Replace the [placeholders] with your real details and save the FAQ as Excel.",
      "Paste a customer's message.",
      "Check which answer each question matched, and add any unanswered question to your FAQ.",
      "Edit the drafted reply and copy it.",
    ],
    features: [
      "Your own answers, kept in an Excel file you own",
      "Starter templates for hotels, clinics, restaurants, agencies and shops",
      "Splits a message into its separate questions",
      "Matches with synonyms — \"car\" finds your parking answer",
      "Never guesses: unmatched questions get \"we'll check\"",
      "One-click \"add to FAQ\" for new questions",
      "Friendly or formal tone, and Japanese business replies",
      "Warns when a [placeholder] is still in the reply",
      "Exports your FAQ as a Word page for your website",
    ],
    faqs: [
      { q: "Does it make up answers?", a: "No. It only uses the answers you write. When a question has no good match it does not guess — the reply says you will check and get back to them, which is what a careful person would do." },
      { q: "Where are my answers saved?", a: "In the Excel file you download, which you open here next time. A working copy is kept in your browser for convenience. Nothing is sent to DO101." },
      { q: "What are the square brackets in the templates?", a: "Placeholders for your real details — hours, prices, policies. The templates are a starting structure, not facts about your business, and the reply warns you if one is still there." },
      { q: "Can it reply in Japanese?", a: "Yes. A Japanese inquiry gets a Japanese reply in business register (〇〇様, お問い合わせいただき誠にありがとうございます…), using your answers." },
      { q: "How does matching work without AI?", a: "Each question is compared with your FAQ by the words they share, using a standard search ranking, plus common synonyms. The percentage shown is how much of the question the answer covers." },
    ],
  },
  {
    id: "work-report-generator",
    name: "Daily & Weekly Report Generator",
    short: "Turn your work notes into a stand-up update or weekly report, grouped by project.",
    long:
      "Paste the notes you already keep — \"fixed the login bug #web (2h)\", \"waiting on legal for the contract\", \"tomorrow: finish the deck\" — and get a clean daily stand-up or weekly report. Every line is sorted into done, in progress, blocked or next, grouped by project, with the hours you logged added up. Nothing is invented: a line that cannot be classified stays a note, and you can correct any line before exporting. Copy it for Slack, Teams or email, or download it as Word or an Excel log. Works with English and Japanese notes, in your browser.",
    category: "productivity",
    route: "/tools/work-report-generator",
    keywords: [
      "weekly report generator", "daily stand up update", "status report template", "work log to report",
      "weekly status report", "daily report template", "progress report generator", "what i did this week",
      "standup notes", "timesheet summary",
    ],
    aliases: ["weekly report", "status report", "standup", "daily report", "ai report generator", "週報", "日報"],
    icon: "📈",
    accent: "grass",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "file",
    related: ["meeting-action-items", "sop-generator", "daily-planner", "task-extractor"],
    seoTitle: "Weekly Report & Daily Stand-up Generator from Work Notes | DO101",
    seoDescription:
      "Turn your work notes into a daily stand-up or weekly status report: done, in progress, blocked and next, grouped by project with hours. Copy or download as Word.",
    steps: [
      "Enter your name and team, and choose a daily stand-up or a weekly report.",
      "Paste your notes — tag projects with #name and add hours like (2h) if you track them.",
      "Check how each line was read, and change any status that is wrong.",
      "Copy the report for Slack, Teams or email, or download Word or Excel.",
    ],
    features: [
      "Sorts notes into done, in progress, blocked and next",
      "Groups by project from #tags, [brackets] or \"Project — …\"",
      "Adds up hours written as (2h), 1.5h or 45m",
      "Day headings date the lines under them",
      "Daily stand-up or weekly report layouts",
      "Never invents work — unclear lines stay notes",
      "Reads Japanese notes (完了, 対応中, 待ち)",
      "Word report and Excel log downloads",
    ],
    faqs: [
      { q: "Does it write the report for me?", a: "It organises what you wrote — sorting, grouping, totalling and formatting — rather than writing new sentences. That is deliberate: a status report must be accurate, and nothing is added that you did not say." },
      { q: "How does it know what is done or blocked?", a: "From the words used: fixed, sent, shipped or 完了 mean done; working on or 対応中, in progress; waiting on, blocked or 待ち, blocked; tomorrow, next or TODO, next. You can change any line." },
      { q: "How do I get projects?", a: "Tag a line with #project, start it with [Project], or write \"Project — what you did\". Untagged lines are grouped under General." },
      { q: "Can it total my hours?", a: "Yes. Write times like (2h), 1.5h or 45m anywhere on a line and they are added up per project and overall." },
      { q: "Is my work log stored?", a: "No. It is processed in your browser, and the only copies are the ones you copy or download." },
    ],
  },
  {
    id: "document-search",
    name: "Private Document Search",
    short: "Search across your own PDFs, Word files and spreadsheets without uploading them.",
    long:
      "Drop in the files you need to search — PDFs, Word documents, Excel sheets, notes, exports — and search across all of them at once. Results are ranked with the same method most search engines use, point to the exact passage that matched with the words highlighted, and the best-matching sentences are quoted at the top with their source. It understands different forms of a word and searches Japanese too. Everything is read and indexed inside this browser tab: nothing is uploaded, nothing is stored, and closing the tab forgets it all. No AI service, so it quotes your documents rather than paraphrasing them.",
    category: "productivity",
    route: "/tools/document-search",
    keywords: [
      "search multiple pdfs", "search inside documents", "search word documents", "private document search",
      "full text search files", "find text in pdf and word", "local file search", "search company documents",
      "knowledge base search", "search across files",
    ],
    aliases: ["search my files", "find in documents", "pdf search", "ai document search", "ask my documents", "文書検索"],
    icon: "🔎",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "text",
    related: ["pdf-to-text", "pdf-ocr", "customer-inquiry-replies", "what-did-i-miss"],
    seoTitle: "Search Inside PDFs, Word & Excel Files — Private, No Upload | DO101",
    seoDescription:
      "Search across many PDFs, Word documents and spreadsheets at once, in your browser. Ranked passages, highlighted matches and quoted answers. Nothing is uploaded.",
    steps: [
      "Drop in PDFs, Word documents, spreadsheets or text files.",
      "Type a question or keywords. Use \"quotes\" for a phrase and -word to exclude.",
      "Read the quoted best match, then the ranked passages below it.",
      "Filter to one file, or copy an answer with its source.",
    ],
    features: [
      "Searches PDF, Word, Excel, CSV, text, Markdown and HTML together",
      "Ranked by BM25, the method behind most search engines",
      "Points to the exact passage, with matches highlighted",
      "Quotes the best-matching sentences with their source",
      "Matches other forms of a word (invoice, invoicing)",
      "Searches Japanese text",
      "Exact phrases and excluded words",
      "Nothing uploaded; closing the tab forgets everything",
    ],
    faqs: [
      { q: "Are my files uploaded?", a: "No. They are opened and indexed inside this browser tab. There is no server receiving them, and closing the tab discards the index." },
      { q: "Can I ask it questions like a chatbot?", a: "You can type a question, and it will find and quote the passages that best match it. It does not write a new answer in its own words — that needs an AI service. The upside is it cannot invent anything: every answer is a quote from your file." },
      { q: "Why is a PDF not searchable?", a: "Scanned PDFs are images with no text in them. Run them through the PDF OCR tool first, then search the result." },
      { q: "How many files can I search?", a: "As many as your browser can hold in memory — typically hundreds of ordinary documents. Very large files take a few seconds to read." },
      { q: "Does it search Japanese?", a: "Yes. Japanese has no spaces between words, so it is indexed by overlapping character pairs, the way search engines handle it without a dictionary." },
    ],
  },
  {
    id: "follow-up-tracker",
    name: "Sales Follow-up Tracker",
    short: "See which leads are overdue for a follow-up, with the message drafted — kept in your own Excel.",
    long:
      "Keep your leads in an Excel file and open it here: each lead's stage and last-contact date decide when the next follow-up is due, overdue ones rise to the top, and a follow-up message is drafted to suit the stage — a first touch, a proposal check-in, a gentle nudge, or after five unanswered attempts a polite \"should I close your file?\". Log that you sent it and the dates move on. Save the file again and next time you continue where you stopped. No CRM subscription, no database, and nothing uploaded.",
    category: "productivity",
    route: "/tools/follow-up-tracker",
    keywords: [
      "sales follow up tracker", "lead follow up template", "follow up email template", "free crm spreadsheet",
      "sales pipeline excel", "lead tracker excel", "when to follow up with a lead", "sales cadence",
      "follow up reminder", "prospect tracker",
    ],
    aliases: ["follow up", "lead tracker", "sales tracker", "crm", "ai sales follow up", "営業 フォロー"],
    icon: "📇",
    accent: "fire",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["customer-inquiry-replies", "task-extractor", "daily-planner", "compound-interest"],
    seoTitle: "Sales Follow-up Tracker — Free Lead Follow-ups in Excel | DO101",
    seoDescription:
      "Free sales follow-up tracker: see overdue leads, get a follow-up email drafted for each stage, and keep everything in your own Excel file. No CRM, no sign-up.",
    steps: [
      "Open your leads spreadsheet, or start with the example or a blank lead.",
      "Check each lead's stage and last-contact date — overdue follow-ups are at the top.",
      "Open a lead's message, copy it or open it in your email app, and send it.",
      "Press \"I sent it\" to log today's date and the attempt.",
      "Save as Excel — open that file here next time to carry on.",
    ],
    features: [
      "Follow-up dates from each lead's stage and last contact",
      "Gaps widen after unanswered attempts, so you persist without pestering",
      "Messages drafted for each stage, personalised with name and next step",
      "A polite break-up message after five unanswered attempts",
      "Open the draft straight in your email app",
      "Reads and writes Excel with English or Japanese headings",
      "Your file is the database — no CRM, no subscription",
      "Nothing uploaded",
    ],
    faqs: [
      { q: "How often should I follow up with a lead?", a: "It depends on the stage. This uses a common rhythm: a new lead the next day, a first contact after three days, a sent proposal after four, a nurture lead monthly — with the gap widening after each unanswered attempt. You can see and change each lead's stage." },
      { q: "Where are my leads stored?", a: "In your own Excel file. Load it, work through your follow-ups, and save it again. A working draft is kept in this browser until you clear it, but DO101 never receives your leads." },
      { q: "What columns does my spreadsheet need?", a: "A heading row with columns such as Name, Company, Email, Stage, Last contact, Attempts and Next step. Headings are matched loosely, in English or Japanese; missing columns are simply left blank." },
      { q: "Can it tell if a lead replied?", a: "It cannot see your inbox. Logging \"I sent it\" is what moves a lead on — and if they reply, update their stage." },
      { q: "Why a \"should I close your file\" message?", a: "After several unanswered attempts, another nudge rarely works, but a polite message saying you will stop often gets a reply — and if not, you can move on with a clear conscience." },
    ],
  },
  {
    id: "what-did-i-miss",
    name: "What Did I Miss? Catch-up Digest",
    short: "Back from time off? See the messages that matter to you first, and why.",
    long:
      "Paste the channel, chat export or emails from while you were away, set the day you left, and get the messages that matter ranked to the top: the ones that name you or ask you something, decisions made, new deadlines, and changes like postponements, new policies or outages. Each message shows the reasons it ranked where it did, and the tasks for you are pulled into a list. Everything below the line is one click away rather than hidden. Download the digest as Word, the tasks as Excel, or the deadlines to your calendar. No AI service — it quotes the messages instead of paraphrasing them — and nothing is uploaded.",
    category: "productivity",
    route: "/tools/what-did-i-miss",
    keywords: [
      "catch up after vacation", "what did i miss at work", "back from leave summary", "slack catch up",
      "email catch up after holiday", "summarize messages", "important messages filter", "return to work checklist",
      "missed messages digest", "channel summary",
    ],
    aliases: ["what did i miss", "catch up", "back from holiday", "ai catch up summary", "vacation catch up", "休暇明け"],
    icon: "🏖️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "file",
    related: ["task-extractor", "meeting-action-items", "document-search", "daily-planner"],
    seoTitle: "What Did I Miss? Catch Up on Messages After Time Off | DO101",
    seoDescription:
      "Back from vacation? Paste your channel or emails and see the messages that need you first — mentions, questions, decisions, deadlines and changes. Free and private.",
    steps: [
      "Enter your name and the date you left.",
      "Paste the channel, chat export or emails from while you were away.",
      "Read \"Needs you\" and \"Decided while you were away\" first.",
      "Work down the ranked messages; each shows why it matters.",
      "Download the digest, the tasks or the deadlines.",
    ],
    features: [
      "Ranks messages by what matters when you return",
      "Shows the reasons behind every ranking",
      "Pulls out tasks addressed to you",
      "Lists decisions made while you were away",
      "Spots changes: postponements, outages, new policies, people moving",
      "Filters by the date you left",
      "Word digest, Excel tasks and calendar deadlines",
      "Quotes messages, never paraphrases them",
    ],
    faqs: [
      { q: "Does it summarise the messages?", a: "It selects and ranks them rather than rewriting them, because a paraphrase needs an AI service and can get things wrong. You read the important messages themselves, in order of importance, with the reasons shown." },
      { q: "How are messages ranked?", a: "By signals: it names you, asks you something, records a decision, sets a deadline, announces a change, is marked urgent, or goes to everyone. Each signal adds to a score, and the score and signals are shown on every message." },
      { q: "Why is the date filter leaving messages out?", a: "Messages without a timestamp cannot be placed before or after the day you left. The tool says how many were left out; clear the date to include them." },
      { q: "Does it connect to Slack or my email?", a: "No. You paste the messages. That keeps everything private and means there is nothing to authorise." },
      { q: "Is anything stored?", a: "No. The messages are processed in this page and forgotten when you leave; the only copies are what you download." },
    ],
  },
  {
    id: "japanese-workplace",
    name: "Japanese Workplace Message Helper",
    short: "Understand Japanese work messages — what they really mean — and reply politely.",
    long:
      "For anyone working in Japanese as a second language. Paste a work email or chat message and see the business phrases in it explained — not just what the words say but what they mean in practice, like 前向きに検討します often being a polite no — along with what the sender expects back, any deadline, and whether it is written to a client or a colleague. Then build a reply in the right register for a client, your boss or a colleague: acknowledge, accept with a deadline, ask for detail, ask for more time, decline, report completion and more, with every line in Japanese, romaji and English. Includes a searchable guide to the most common business phrases. No translation service is used, so what you paste stays on your device.",
    category: "productivity",
    route: "/tools/japanese-workplace",
    keywords: [
      "business japanese email", "japanese email reply template", "keigo email", "japanese workplace phrases",
      "how to reply in japanese business", "japanese business email phrases", "お世話になっております meaning",
      "前向きに検討します meaning", "polite japanese reply", "working in japan foreigner",
    ],
    aliases: ["business japanese", "keigo", "japanese email", "ビジネスメール", "敬語 メール", "ai japanese email helper"],
    icon: "🏢",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "text",
    output: "text",
    related: ["japanese-translator", "romaji-converter", "customer-inquiry-replies", "meeting-action-items"],
    seoTitle: "Business Japanese Email Helper — Understand & Reply in Keigo | DO101",
    seoDescription:
      "Understand Japanese work messages and what set phrases really mean, then write a polite reply for a client, boss or colleague — with romaji and English. Free.",
    steps: [
      "Paste a Japanese work message into \"Understand a message\".",
      "Read what it wants, and what each business phrase in it really means.",
      "Choose one of the suggested replies, or go to \"Write a reply\".",
      "Pick who you are writing to, fill in names, the topic and a date.",
      "Copy the Japanese email, or download it as Word with romaji and English.",
    ],
    features: [
      "Explains business phrases by what they really mean, not word for word",
      "Flags indirect refusals like 前向きに検討します and 難しいです",
      "Picks out deadlines such as 明日まで, 本日中 and 来週金曜日",
      "Tells a client-facing message from an internal one",
      "Reply templates for ten situations in three registers",
      "Every line in Japanese, romaji and English",
      "Searchable guide to common business phrases",
      "No translation service — nothing leaves your device",
    ],
    faqs: [
      { q: "What does お世話になっております mean?", a: "Literally \"I am being taken care of by you\", but in practice it is simply the standard opening line of any business email to someone outside your company. It is not thanking you for anything specific — start your reply with it too." },
      { q: "Does 前向きに検討します mean yes?", a: "Not necessarily. \"We will consider it positively\" often means the sender is not committing, and without a date attached it can be a polite no. The helper suggests asking, politely, when to expect a decision." },
      { q: "What is the difference between the client, boss and colleague replies?", a: "Register. Client replies use honorific and humble forms (謙譲語, 尊敬語), 様 and お世話になっております. Boss replies stay formal but in-house, with お疲れ様です and 承知いたしました. Colleague replies are polite but plainer, like 了解です." },
      { q: "Can it translate the whole message?", a: "No — full translation needs a translation service, and this tool uses none so your messages stay private. It explains the phrases that carry the meaning in business Japanese. For a full translation, the separate Japanese translator tool uses a free external service." },
      { q: "Is 了解しました rude?", a: "It is fine between colleagues, but many people consider it too casual for a boss or a client. 承知いたしました or かしこまりました are the safe choices when writing upward or outward." },
      { q: "How do I sign off a Japanese business email?", a: "With よろしくお願いいたします, or 引き続きよろしくお願いいたします for an ongoing relationship. For an important request, 何卒よろしくお願い申し上げます is more formal still." },
    ],
  },
];
