import type { Tool } from "./types";

/**
 * Single source of truth for every DO101 tool.
 * Powers: homepage, /tools directory, command palette, related links,
 * AI tool routing, sitemap.xml and structured data.
 */
export const TOOLS: Tool[] = [
  /* ------------------------------- IMAGE ------------------------------- */
  {
    id: "image-compressor",
    name: "Image Compressor",
    short: "Shrink JPG, PNG or WebP files without leaving your browser.",
    long:
      "Compress images down to a size that actually fits an upload limit. Pick a quality level or type a target size in kilobytes and DO101 searches for the best quality that still fits. Everything runs on your device using the browser's own canvas encoder, so the picture is never uploaded.",
    category: "image",
    route: "/tools/image-compressor",
    keywords: ["compress image", "image compressor", "reduce image size", "compress jpg", "compress png", "compress photo", "under 200kb", "shrink image"],
    aliases: ["compress photo", "make image smaller", "reduce photo size", "photo compressor"],
    icon: "🗜️",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["image-resizer", "jpg-to-png", "png-to-jpg", "qr-generator"],
    seoTitle: "Free Image Compressor — Compress JPG & PNG Online | DO101",
    seoDescription:
      "Compress JPG, PNG and WebP images in your browser. Choose a quality level or a target size in KB. No upload, no watermark, no sign-up.",
    steps: [
      "Drop an image onto the box, or tap it to pick a file.",
      "Choose a quality level, or switch to target size and type a limit in KB.",
      "Watch the before/after sizes update, then download the compressed image.",
    ],
    features: [
      "Quality slider with live before/after file sizes",
      "Target-size mode that searches for the best quality under your limit",
      "Batch mode: compress several images in one pass",
      "Keeps JPG, PNG and WebP output options",
      "100% in-browser — the file never leaves your device",
    ],
    faqs: [
      { q: "Are my images uploaded to a server?", a: "No. Compression happens with the browser's canvas encoder on your own device. DO101 has no upload endpoint for this tool, so the file never leaves your computer or phone." },
      { q: "How do I compress an image under 200 KB?", a: "Switch to target size mode, type 200 and press compress. DO101 repeatedly re-encodes at different quality levels and keeps the best-looking result that still fits under 200 KB." },
      { q: "Does compression reduce quality?", a: "JPG and WebP compression is lossy, so very low quality values will show artefacts. Most photos look identical at 70–80% quality while losing more than half their file size." },
      { q: "Which formats are supported?", a: "JPG/JPEG, PNG and WebP inputs. You can also export to a different format than the input, which is often the biggest saving of all." },
    ],
    featured: true,
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    short: "Resize pictures to exact pixel dimensions or a percentage.",
    long:
      "Set a width, a height, or a percentage and DO101 resizes the image on your device. Lock the aspect ratio to avoid stretching, or unlock it when you need an exact canvas size. Nothing is uploaded.",
    category: "image",
    route: "/tools/image-resizer",
    keywords: ["image resizer", "resize image", "resize photo", "change image dimensions", "scale image", "resize jpg", "resize png"],
    aliases: ["make image smaller dimensions", "scale photo", "change photo size"],
    icon: "📐",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["image-compressor", "jpg-to-png", "png-to-jpg", "qr-generator"],
    seoTitle: "Free Image Resizer — Resize JPG & PNG by Pixels | DO101",
    seoDescription:
      "Resize images online by width, height or percentage with aspect-ratio lock. Runs entirely in your browser — no upload and no sign-up.",
    steps: [
      "Add an image from your device.",
      "Type a new width or height, or drag the percentage scale.",
      "Keep the ratio locked to avoid distortion, then download.",
    ],
    features: [
      "Resize by pixels or percentage",
      "Aspect-ratio lock",
      "Shows original and output dimensions side by side",
      "Export as JPG, PNG or WebP",
      "Runs offline once the page has loaded",
    ],
    faqs: [
      { q: "Will resizing blur my image?", a: "Scaling down stays sharp. Scaling far above the original size cannot invent detail, so enlargements will look soft — that is true of every resizer." },
      { q: "Can I resize several images at once?", a: "Yes. Add multiple files and the same dimensions are applied to each, then download them one by one." },
      { q: "Is the file uploaded?", a: "No. The resize happens in a canvas element inside your browser tab." },
    ],
    featured: true,
  },
  {
    id: "jpg-to-png",
    name: "JPG to PNG",
    short: "Convert JPG photos to lossless PNG files.",
    long:
      "Turn JPG or JPEG images into PNG, the format editors and design tools prefer for lossless work. Conversion runs in your browser, so large batches stay fast and private.",
    category: "image",
    route: "/tools/jpg-to-png",
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png", "image converter", "png converter"],
    aliases: ["jpeg to png", "change jpg to png"],
    icon: "🔄",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["png-to-jpg", "image-compressor", "image-resizer", "qr-generator"],
    seoTitle: "JPG to PNG Converter — Free & In-Browser | DO101",
    seoDescription:
      "Convert JPG and JPEG images to PNG online for free. Batch friendly, no watermark, no upload — conversion happens in your browser.",
    steps: ["Add one or more JPG files.", "Press convert.", "Download the PNG results."],
    features: ["Batch conversion", "Lossless PNG output", "No watermark or sign-up", "Works on phones and tablets", "Files stay on your device"],
    faqs: [
      { q: "Does converting JPG to PNG restore lost quality?", a: "No. A JPG has already discarded detail; PNG simply stops any further loss. Converting is useful for editing, transparency workflows and crisp screenshots." },
      { q: "Why is the PNG bigger than the JPG?", a: "PNG is lossless, so photographs usually grow. If you need a smaller file, use the Image Compressor instead." },
    ],
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG",
    short: "Convert PNG images to smaller JPG files.",
    long:
      "PNG screenshots are often several times larger than they need to be. Convert them to JPG with a quality you control, and pick the background colour used where the PNG was transparent.",
    category: "image",
    route: "/tools/png-to-jpg",
    keywords: ["png to jpg", "png to jpeg", "convert png to jpg", "image converter"],
    aliases: ["png to jpeg", "change png to jpg"],
    icon: "🔃",
    accent: "grape",
    browserOnly: true,
    aiInvocable: false,
    input: "file",
    output: "file",
    related: ["jpg-to-png", "image-compressor", "image-resizer", "qr-generator"],
    seoTitle: "PNG to JPG Converter — Free & In-Browser | DO101",
    seoDescription:
      "Convert PNG images to JPG online with an adjustable quality and background colour. Free, no upload, no watermark.",
    steps: ["Add one or more PNG files.", "Choose JPG quality and a background colour for transparent areas.", "Convert and download."],
    features: ["Quality control", "Choose the matte colour for transparency", "Batch conversion", "Big size savings on screenshots", "Processed in your browser"],
    faqs: [
      { q: "What happens to transparency?", a: "JPG has no alpha channel, so transparent pixels are filled with the background colour you choose — white by default." },
      { q: "How much smaller will the JPG be?", a: "Screenshots and photographs typically shrink by 60–90%. Flat graphics and logos may not shrink much and often look better left as PNG." },
    ],
  },

  /* ---------------------------- PRODUCTIVITY ---------------------------- */
  {
    id: "qr-generator",
    name: "QR Code Generator",
    short: "Make a QR code for a link, text, email, phone or Wi-Fi.",
    long:
      "Generate a crisp QR code and download it as a PNG or SVG. Choose the size and the error-correction level, and switch between link, plain text, email, phone and Wi-Fi payloads. The code is rendered locally in your browser.",
    category: "productivity",
    route: "/tools/qr-generator",
    keywords: ["qr code generator", "generate qr code", "make qr code", "wifi qr code", "free qr code", "qr png"],
    aliases: ["make qr", "create qr code", "qr maker"],
    icon: "📱",
    accent: "sun",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "file",
    related: ["url-encoder", "image-compressor", "base64", "text-cleaner"],
    seoTitle: "Free QR Code Generator — URL, Wi-Fi & Text QR | DO101",
    seoDescription:
      "Create free QR codes for links, text, email, phone numbers and Wi-Fi. Adjustable size and error correction, PNG or SVG download, no sign-up.",
    steps: [
      "Pick what the code should contain: link, text, email, phone or Wi-Fi.",
      "Fill in the fields and adjust size or error correction if you need to.",
      "Download the PNG or SVG and test it with your phone camera.",
    ],
    features: [
      "Link, text, email, phone and Wi-Fi payloads",
      "Adjustable size and error-correction level",
      "PNG and SVG download",
      "No tracking redirect — the code points straight at your data",
      "Never expires, because there is no server involved",
    ],
    faqs: [
      { q: "Do these QR codes expire?", a: "No. The code encodes your data directly, so there is no DO101 redirect that could ever be switched off." },
      { q: "What error-correction level should I pick?", a: "Medium is a good default. Use High (H) if the code will be printed small, placed on a curved surface, or covered by a logo." },
      { q: "Is a Wi-Fi QR code safe to print?", a: "It contains your network password in plain text, so anyone who scans the printed code can join. Only display it where you are happy for guests to connect." },
    ],
    featured: true,
  },

  /* -------------------------------- TEXT -------------------------------- */
  {
    id: "word-counter",
    name: "Word Counter",
    short: "Live word, character, sentence and reading-time counts.",
    long:
      "Paste or type text and see the word count update as you go, along with characters, sentences, paragraphs, reading time and speaking time. Useful for essays, assignments, meta descriptions and social posts.",
    category: "text",
    route: "/tools/word-counter",
    keywords: ["word counter", "count words", "word count", "essay word count", "character count", "reading time"],
    aliases: ["count words", "how many words", "wordcount"],
    icon: "🔢",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["character-counter", "text-cleaner", "case-converter", "text-diff"],
    seoTitle: "Free Word Counter — Words, Characters & Reading Time | DO101",
    seoDescription:
      "Count words, characters, sentences and paragraphs instantly. Includes reading time, speaking time and keyword density. Free and browser-based.",
    steps: ["Paste or type your text.", "Read the live counts as you edit.", "Copy the cleaned text or the statistics if you need them."],
    features: [
      "Words, characters, sentences, paragraphs and lines",
      "Reading time and speaking time estimates",
      "Top keyword density",
      "Longest word and average word length",
      "Nothing is sent anywhere — the counter runs locally",
    ],
    faqs: [
      { q: "How is a word counted?", a: "Any run of characters separated by whitespace counts as one word. Hyphenated words such as \"well-known\" count as a single word, matching how most word processors behave." },
      { q: "How is reading time calculated?", a: "Reading time assumes 225 words per minute, a common average for adult silent reading. Speaking time assumes 130 words per minute." },
      { q: "Is my text stored?", a: "No. The text stays in the page. Nothing is uploaded and nothing is saved unless you copy it yourself." },
    ],
    featured: true,
  },
  {
    id: "character-counter",
    name: "Character Counter",
    short: "Count characters with live limits for tweets, SEO and SMS.",
    long:
      "Count characters with and without spaces, and watch progress bars for the limits that matter: X posts, SEO titles, meta descriptions and SMS segments. Perfect for anything with a hard character budget.",
    category: "text",
    route: "/tools/character-counter",
    keywords: ["character counter", "count characters", "letter count", "twitter character count", "meta description length", "sms character count"],
    aliases: ["count letters", "char count", "how many characters"],
    icon: "🅰️",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["word-counter", "text-cleaner", "case-converter", "text-diff"],
    seoTitle: "Free Character Counter — With & Without Spaces | DO101",
    seoDescription:
      "Count characters online with and without spaces, plus live limits for X posts, SEO titles, meta descriptions and SMS. Free, instant, private.",
    steps: ["Paste your text.", "Watch the counters and limit bars update.", "Trim until every bar is inside its limit."],
    features: [
      "Characters with and without spaces",
      "Live limit bars for X, SEO title, meta description and SMS",
      "Counts emoji correctly using grapheme-aware counting",
      "Byte size in UTF-8",
      "Runs entirely in your browser",
    ],
    faqs: [
      { q: "Why do emoji count as more than one character?", a: "Many emoji are built from several Unicode code points. DO101 shows both the visible character count (what a human sees) and the raw code-unit count that most APIs enforce." },
      { q: "What is the ideal meta description length?", a: "Google typically renders around 155–160 characters on desktop. DO101 warns you as you approach that range." },
    ],
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    short: "Strip double spaces, blank lines and messy formatting.",
    long:
      "Paste text copied from a PDF, an email or a website and tidy it with one click. Remove duplicate spaces, empty lines, line breaks inside paragraphs, smart quotes and invisible characters — you choose which fixes to apply.",
    category: "text",
    route: "/tools/text-cleaner",
    keywords: ["text cleaner", "remove extra spaces", "remove line breaks", "remove blank lines", "clean text", "remove formatting"],
    aliases: ["clean up text", "remove double spaces", "tidy text"],
    icon: "🧹",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["word-counter", "case-converter", "text-diff", "character-counter"],
    seoTitle: "Free Text Cleaner — Remove Extra Spaces & Line Breaks | DO101",
    seoDescription:
      "Clean messy text online: remove duplicate spaces, blank lines, line breaks, smart quotes and invisible characters. Free and browser-based.",
    steps: ["Paste the messy text.", "Toggle the fixes you want.", "Copy the cleaned result."],
    features: [
      "Collapse duplicate spaces and tabs",
      "Remove blank lines and trailing whitespace",
      "Join broken paragraph line breaks",
      "Convert smart quotes and dashes to plain ASCII",
      "Strip zero-width and invisible characters",
    ],
    faqs: [
      { q: "Why does text copied from a PDF have odd line breaks?", a: "PDFs store text line by line, so a copy carries a hard break at the end of every visual line. The \"join wrapped lines\" option rebuilds the paragraphs." },
      { q: "What are invisible characters?", a: "Zero-width spaces and joiners sometimes ride along with copied text and break search, code and form validation. The cleaner removes them." },
    ],
  },
  {
    id: "text-diff",
    name: "Text Diff Checker",
    short: "Compare two texts and highlight every change.",
    long:
      "Paste an original and a revised version to see exactly what was added, removed or left alone. DO101 shows a word-level diff so a single changed word does not light up the whole line.",
    category: "text",
    route: "/tools/text-diff",
    keywords: ["text diff", "compare text", "diff checker", "text comparison", "compare two documents", "find differences"],
    aliases: ["compare two texts", "difference checker", "text compare"],
    icon: "🔍",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["text-cleaner", "word-counter", "json-formatter", "case-converter"],
    seoTitle: "Free Text Diff Checker — Compare Two Texts Online | DO101",
    seoDescription:
      "Compare two blocks of text and highlight additions and deletions word by word. Free online diff checker that runs in your browser.",
    steps: ["Paste the original text on the left.", "Paste the changed text on the right.", "Read the highlighted diff underneath."],
    features: ["Word-level highlighting", "Added / removed / unchanged counts", "Ignore case and whitespace options", "Works with long documents", "Nothing leaves your browser"],
    faqs: [
      { q: "Can I compare code?", a: "Yes. Word-level diffing works well for code, though for very large files a dedicated Git diff will be faster." },
      { q: "Is there a size limit?", a: "The comparison is capped to keep the page responsive; extremely large documents are trimmed with a clear warning rather than freezing the tab." },
    ],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    short: "Switch text between UPPER, lower, Title, camel, snake and kebab.",
    long:
      "Convert text between every case you need: sentence case, lowercase, UPPERCASE, Title Case, camelCase, PascalCase, snake_case, kebab-case and CONSTANT_CASE. Handy for writing and for renaming variables.",
    category: "text",
    route: "/tools/case-converter",
    keywords: ["case converter", "uppercase", "lowercase", "title case", "camel case", "snake case", "kebab case", "change text case"],
    aliases: ["uppercase converter", "capitalize text", "change case"],
    icon: "🔤",
    accent: "sky",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["text-cleaner", "word-counter", "character-counter", "uuid-generator"],
    seoTitle: "Free Case Converter — Upper, Lower, Title & camelCase | DO101",
    seoDescription:
      "Convert text to uppercase, lowercase, sentence case, Title Case, camelCase, snake_case or kebab-case instantly. Free and private.",
    steps: ["Paste your text.", "Tap the case you want.", "Copy the converted result."],
    features: ["Nine case styles", "One-tap copy", "Preserves acronyms in Title Case where sensible", "Works on long text", "In-browser only"],
    faqs: [
      { q: "What is the difference between Title Case and Capitalized Case?", a: "Title Case leaves short joining words such as \"of\" and \"and\" lowercase unless they start the title. Capitalized Case capitalises every word." },
      { q: "Which case should I use for code?", a: "camelCase for JavaScript variables, PascalCase for classes and React components, snake_case for Python, kebab-case for URLs and CSS classes." },
    ],
  },

  /* ----------------------------- DEVELOPER ----------------------------- */
  {
    id: "json-formatter",
    name: "JSON Formatter",
    short: "Beautify, minify and validate JSON with error positions.",
    long:
      "Paste raw JSON and get readable, indented output — or minify it back down for shipping. Invalid JSON is reported with the line and column of the problem instead of a vague parse error.",
    category: "developer",
    route: "/tools/json-formatter",
    keywords: ["json formatter", "format json", "beautify json", "json pretty print", "minify json", "json parser"],
    aliases: ["pretty print json", "beautify json", "make json readable"],
    icon: "{ }",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-validator", "base64", "uuid-generator", "regex-tester"],
    seoTitle: "Free JSON Formatter & Beautifier — Online JSON Viewer | DO101",
    seoDescription:
      "Format, beautify, minify and validate JSON online. Clear error messages with line and column numbers. Free, fast and runs in your browser.",
    steps: ["Paste your JSON.", "Choose an indent size, or press minify.", "Copy or download the formatted result."],
    features: [
      "2, 4 and tab indentation",
      "Minify to the smallest valid JSON",
      "Precise error line and column",
      "Sort keys alphabetically",
      "Copy or download in one tap",
    ],
    faqs: [
      { q: "Why does my JSON fail to parse?", a: "The usual culprits are trailing commas, single quotes instead of double quotes, unquoted keys and comments. JSON allows none of those — DO101 points at the exact character that broke the parse." },
      { q: "Is my JSON sent to a server?", a: "No. Parsing uses the browser's built-in JSON engine, so payloads with API keys or customer data never leave your machine." },
      { q: "Can it handle large files?", a: "Files up to a few megabytes format instantly. Enormous documents may be slow to render because of the browser, not the parser." },
    ],
    featured: true,
  },
  {
    id: "json-validator",
    name: "JSON Validator",
    short: "Check whether JSON is valid and see exactly what broke.",
    long:
      "A focused pass/fail check for JSON. Valid documents report their type, key count and nesting depth. Invalid documents get the line, column and the offending snippet highlighted.",
    category: "developer",
    route: "/tools/json-validator",
    keywords: ["json validator", "validate json", "json checker", "is my json valid", "json syntax check"],
    aliases: ["check json", "json lint"],
    icon: "✅",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-formatter", "base64", "jwt-decoder", "regex-tester"],
    seoTitle: "Free JSON Validator — Check JSON Syntax Online | DO101",
    seoDescription:
      "Validate JSON online and get the exact line and column of any syntax error, plus structure statistics. Free and browser-based.",
    steps: ["Paste the JSON you want to check.", "Read the pass or fail banner.", "Jump to the reported line to fix an error."],
    features: ["Instant valid / invalid verdict", "Line and column of the first error", "Key count, depth and root type", "Duplicate key warning", "No upload"],
    faqs: [
      { q: "Does it validate against a JSON Schema?", a: "Not yet. This tool checks syntax — whether the document is parseable JSON. Schema validation is on the roadmap." },
      { q: "Are duplicate keys invalid?", a: "Strictly they are allowed by the spec, but almost every parser silently keeps only the last one, so DO101 warns you when it spots them." },
    ],
  },
  {
    id: "base64",
    name: "Base64 Encoder & Decoder",
    short: "Encode or decode Base64 text and files, Unicode-safe.",
    long:
      "Convert text to Base64 and back, including full Unicode and emoji, which naive implementations mangle. You can also encode a file into a Base64 data URI for embedding in CSS or HTML.",
    category: "developer",
    route: "/tools/base64",
    keywords: ["base64 encoder", "base64 decoder", "encode base64", "decode base64", "base64 to text", "data uri"],
    aliases: ["b64", "base 64", "encode to base64"],
    icon: "🔐",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["url-encoder", "json-formatter", "hash-generator", "jwt-decoder"],
    seoTitle: "Base64 Encoder & Decoder — Unicode Safe & Free | DO101",
    seoDescription:
      "Encode and decode Base64 online, with full Unicode and emoji support plus file to data-URI conversion. Free, instant and private.",
    steps: ["Choose encode or decode.", "Paste your text, or drop a file to get a data URI.", "Copy the result."],
    features: ["Unicode and emoji safe", "URL-safe Base64 variant", "File to data URI", "Instant swap between encode and decode", "Runs offline in your browser"],
    faqs: [
      { q: "Is Base64 encryption?", a: "No. Base64 is an encoding, not encryption — anyone can decode it. Never use it to protect passwords or secrets." },
      { q: "What is URL-safe Base64?", a: "A variant that replaces + and / with - and _ so the string can sit inside a URL without escaping. JWTs use it." },
      { q: "Why do emoji break in other tools?", a: "The classic btoa() function only accepts Latin-1. DO101 encodes to UTF-8 bytes first, so every character survives the round trip." },
    ],
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    short: "Percent-encode text so it is safe inside a URL.",
    long:
      "Turn spaces, ampersands, accents and emoji into percent-encoded escapes so a URL or query string survives being passed around. Choose between component encoding and full-URI encoding.",
    category: "developer",
    route: "/tools/url-encoder",
    keywords: ["url encoder", "percent encoding", "encode url", "urlencode", "query string encoder", "escape url"],
    aliases: ["urlencode", "escape url", "encode query string"],
    icon: "🔗",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["url-decoder", "base64", "json-formatter", "qr-generator"],
    seoTitle: "Free URL Encoder — Percent-Encode Text Online | DO101",
    seoDescription:
      "Encode text for safe use in URLs and query strings, with component and full-URI modes. Free online URL encoder that runs in your browser.",
    steps: ["Paste the text or URL.", "Pick component or full-URI encoding.", "Copy the encoded string."],
    features: ["encodeURIComponent and encodeURI modes", "Handles Unicode and emoji", "Query-string builder view", "One-tap copy", "No upload"],
    faqs: [
      { q: "What is the difference between the two modes?", a: "Component mode escapes everything including &, = and /, which is right for a single value. Full-URI mode leaves the characters that give a URL its structure intact." },
      { q: "Why does a space become %20 sometimes and + at others?", a: "%20 is correct everywhere. The + form only applies inside application/x-www-form-urlencoded form bodies." },
    ],
  },
  {
    id: "url-decoder",
    name: "URL Decoder",
    short: "Turn percent-encoded escapes back into readable text.",
    long:
      "Paste an encoded URL and read it in plain language, with the query parameters broken out into a table so you can see exactly what a link is carrying.",
    category: "developer",
    route: "/tools/url-decoder",
    keywords: ["url decoder", "decode url", "urldecode", "percent decode", "decode query string"],
    aliases: ["urldecode", "unescape url", "read encoded url"],
    icon: "🔓",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["url-encoder", "base64", "jwt-decoder", "json-formatter"],
    seoTitle: "Free URL Decoder — Decode Percent-Encoded URLs | DO101",
    seoDescription:
      "Decode percent-encoded URLs and query strings online, with a parameter breakdown table. Free, instant and browser-based.",
    steps: ["Paste the encoded URL.", "Read the decoded text.", "Inspect the parsed query parameters below."],
    features: ["Handles double-encoded strings", "Query parameter table", "Clear error when the input is malformed", "Unicode safe", "Nothing is uploaded"],
    faqs: [
      { q: "Why do I get a malformed URI error?", a: "A stray % that is not followed by two hex digits makes the string undecodable. DO101 tells you where it is instead of throwing a raw exception." },
      { q: "What is double encoding?", a: "When an already-encoded string is encoded again, %20 becomes %2520. Decode twice to get back to the original." },
    ],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    short: "Generate v4 UUIDs in bulk with a cryptographic source.",
    long:
      "Create random version-4 UUIDs using the browser's cryptographic random number generator. Generate one, or a thousand, and copy or download the list.",
    category: "developer",
    route: "/tools/uuid-generator",
    keywords: ["uuid generator", "guid generator", "random uuid", "uuid v4", "bulk uuid"],
    aliases: ["guid", "generate uuid", "random id"],
    icon: "🎲",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "text",
    related: ["hash-generator", "json-formatter", "base64", "timestamp-converter"],
    seoTitle: "Free UUID Generator — Bulk UUID v4 Online | DO101",
    seoDescription:
      "Generate cryptographically random UUID v4 values in bulk, with uppercase, no-dash and braces options. Free and generated in your browser.",
    steps: ["Choose how many UUIDs you need.", "Press generate.", "Copy the list or download it as a text file."],
    features: ["Up to 1,000 at a time", "Uses crypto.getRandomValues", "Uppercase, no-dash and braces formats", "Copy all or copy one", "Generated locally — never on a server"],
    faqs: [
      { q: "Are these UUIDs really unique?", a: "A v4 UUID has 122 random bits. The chance of a collision is negligible for any realistic number of IDs, which is why they are safe to generate client side." },
      { q: "Do you log the generated values?", a: "No. They are produced in your browser and never sent anywhere." },
    ],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    short: "Read the header and payload of a JSON Web Token.",
    long:
      "Paste a JWT to see its decoded header and payload, with timestamps rendered as readable dates and expiry highlighted. Decoding does not verify the signature — DO101 says so plainly rather than implying the token is trustworthy.",
    category: "developer",
    route: "/tools/jwt-decoder",
    keywords: ["jwt decoder", "decode jwt", "json web token", "jwt parser", "read jwt payload"],
    aliases: ["decode token", "jwt viewer", "read jwt"],
    icon: "🎫",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["base64", "json-formatter", "timestamp-converter", "hash-generator"],
    seoTitle: "Free JWT Decoder — Decode JSON Web Tokens Online | DO101",
    seoDescription:
      "Decode the header and payload of a JSON Web Token in your browser, with human-readable timestamps. Decoding does not verify the signature.",
    steps: ["Paste the JWT.", "Read the decoded header and payload.", "Check the expiry banner for iat, nbf and exp."],
    features: [
      "Header and payload decoded as formatted JSON",
      "iat, nbf and exp shown as local dates",
      "Expiry warning when the token is stale",
      "Standard claim explanations",
      "Decoded in your browser — tokens are never transmitted",
    ],
    faqs: [
      { q: "Does this verify the token?", a: "No. Decoding a JWT does not verify its signature. Anyone can read or forge the payload of an unverified token — only your server, holding the secret or public key, can confirm it is authentic." },
      { q: "Is it safe to paste a real token here?", a: "The decoding happens locally and nothing is sent to DO101. Even so, treat live tokens like passwords and avoid pasting production credentials into any website." },
    ],
  },
  {
    id: "timestamp-converter",
    name: "Unix Timestamp Converter",
    short: "Convert between Unix timestamps and human dates.",
    long:
      "Turn a Unix timestamp into a readable date, or a date into a timestamp. Seconds and milliseconds are both supported and auto-detected, with UTC and local time shown side by side.",
    category: "developer",
    route: "/tools/timestamp-converter",
    keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "date to timestamp", "epoch time", "milliseconds to date"],
    aliases: ["epoch converter", "unix time", "convert timestamp"],
    icon: "⏱️",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["jwt-decoder", "json-formatter", "age", "uuid-generator"],
    seoTitle: "Unix Timestamp Converter — Epoch to Date Online | DO101",
    seoDescription:
      "Convert Unix timestamps to dates and dates to timestamps, in seconds or milliseconds, with UTC and local time. Free online epoch converter.",
    steps: ["Paste a timestamp, or pick a date.", "Seconds versus milliseconds is detected automatically.", "Copy the format you need."],
    features: ["Auto-detects seconds or milliseconds", "UTC, local time and ISO 8601 output", "Relative time (\"3 hours ago\")", "Live current timestamp", "Runs offline"],
    faqs: [
      { q: "How do I tell seconds from milliseconds?", a: "A current timestamp in seconds has 10 digits; in milliseconds it has 13. DO101 checks the magnitude and tells you which it assumed." },
      { q: "What is the Unix epoch?", a: "00:00:00 UTC on 1 January 1970. A Unix timestamp counts the seconds elapsed since that moment, ignoring leap seconds." },
    ],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    short: "Test regular expressions with live matches and groups.",
    long:
      "Write a pattern, set the flags, and see every match highlighted in your test string along with the capture groups. Invalid patterns get a plain-English explanation rather than a cryptic engine error.",
    category: "developer",
    route: "/tools/regex-tester",
    keywords: ["regex tester", "regular expression tester", "test regex", "regex online", "regex match", "regex101 alternative"],
    aliases: ["regexp tester", "test regular expression", "regex checker"],
    icon: "🧪",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["json-formatter", "text-diff", "text-cleaner", "base64"],
    seoTitle: "Free Regex Tester — Test Regular Expressions Online | DO101",
    seoDescription:
      "Test JavaScript regular expressions with live match highlighting, capture groups, flags and a cheat sheet. Free and runs in your browser.",
    steps: ["Type your pattern and pick flags.", "Paste a test string.", "Read the highlighted matches and the capture group table."],
    features: [
      "Live match highlighting",
      "Numbered and named capture groups",
      "All JavaScript flags: g, i, m, s, u, y",
      "Catastrophic-backtracking guard with a timeout",
      "Built-in cheat sheet",
    ],
    faqs: [
      { q: "Which regex flavour is this?", a: "JavaScript (ECMAScript). Most patterns are portable, but lookbehind and named groups behave differently in older engines such as PCRE or Python." },
      { q: "Is my pattern executed safely?", a: "Patterns run as regular expressions only — DO101 never evaluates your input as JavaScript code, and a timeout stops runaway backtracking from freezing the tab." },
    ],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    short: "Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes.",
    long:
      "Hash text or a file with the browser's native Web Crypto implementation. Useful for checksums, cache keys and verifying that a download matches its published digest.",
    category: "developer",
    route: "/tools/hash-generator",
    keywords: ["hash generator", "sha256 generator", "sha1", "sha512", "checksum", "file hash", "hash text"],
    aliases: ["sha256", "checksum calculator", "generate hash"],
    icon: "#️⃣",
    accent: "grass",
    browserOnly: true,
    aiInvocable: true,
    input: "text",
    output: "text",
    related: ["base64", "uuid-generator", "jwt-decoder", "json-formatter"],
    seoTitle: "Free Hash Generator — SHA-256, SHA-1 & SHA-512 | DO101",
    seoDescription:
      "Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes from text or files using Web Crypto. Free, instant and entirely in your browser.",
    steps: ["Paste text, or drop a file.", "Pick the algorithms you want.", "Copy the hex digest."],
    features: ["SHA-1, SHA-256, SHA-384 and SHA-512", "Text and file hashing", "Hex and Base64 output", "Compare against an expected digest", "Uses the browser's Web Crypto API"],
    faqs: [
      { q: "Why is MD5 not offered?", a: "Browsers do not ship MD5 in Web Crypto, and it is cryptographically broken. Adding it would mean shipping a third-party implementation for an algorithm nobody should choose today." },
      { q: "Can I verify a downloaded file?", a: "Yes. Drop the file in, pick SHA-256, and paste the publisher's digest into the compare box. The file is read locally and never uploaded." },
      { q: "Is SHA-256 safe for passwords?", a: "No. Passwords need a slow, salted algorithm such as bcrypt, scrypt or Argon2. A plain SHA hash is far too fast to be safe for that job." },
    ],
  },

  /* ---------------------------- CALCULATORS ---------------------------- */
  {
    id: "age",
    name: "Age Calculator",
    short: "Work out an exact age in years, months and days.",
    long:
      "Enter a date of birth and DO101 works out the exact age today, or on any date you choose, down to the day. It also shows total months, weeks, days and the countdown to the next birthday.",
    category: "calculator",
    route: "/calculators/age",
    keywords: ["age calculator", "calculate age", "how old am i", "date of birth calculator", "age in days", "birthday countdown"],
    aliases: ["how old am i", "calculate my age", "birthday calculator"],
    icon: "🎂",
    accent: "fire",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "numbers",
    related: ["percentage", "discount", "bmi", "timestamp-converter"],
    seoTitle: "Free Age Calculator — Exact Age in Years, Months & Days | DO101",
    seoDescription:
      "Calculate your exact age in years, months and days from a date of birth, plus total weeks, days, hours and a countdown to your next birthday.",
    steps: ["Enter the date of birth.", "Leave the second date as today, or pick another date.", "Read the exact age and the extra breakdowns."],
    features: ["Exact years, months and days", "Totals in months, weeks, days, hours and minutes", "Days until the next birthday", "Day of the week you were born", "Calculated locally"],
    faqs: [
      { q: "How is an exact age calculated?", a: "DO101 counts whole years first, then whole months from that anniversary, then the remaining days — the same way you would say it out loud. Calendar month lengths and leap years are handled properly." },
      { q: "Why does the day count differ from other calculators?", a: "Some tools approximate a month as 30 days. DO101 uses the real calendar, so February and 31-day months are counted correctly." },
    ],
    featured: true,
  },
  {
    id: "percentage",
    name: "Percentage Calculator",
    short: "Every percentage question in one place, with the formula shown.",
    long:
      "Work out what X% of a number is, what percentage one number is of another, and percentage increase or decrease between two values. Each answer shows the formula so you can check the working.",
    category: "calculator",
    route: "/calculators/percentage",
    keywords: ["percentage calculator", "calculate percentage", "percent of a number", "percentage increase", "percentage decrease", "percent change"],
    aliases: ["percent calculator", "work out percentage", "what percent is"],
    icon: "％",
    accent: "fire",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "numbers",
    related: ["discount", "age", "bmi", "word-counter"],
    seoTitle: "Free Percentage Calculator — Percent Of, Change & Increase | DO101",
    seoDescription:
      "Calculate a percentage of a number, what percent one number is of another, and percentage increase or decrease. Formula shown with every answer.",
    steps: ["Pick the kind of percentage question you have.", "Type the two numbers.", "Read the answer and the formula underneath."],
    features: ["What is X% of Y", "X is what percent of Y", "Percentage increase and decrease", "Formula displayed with every result", "Instant, no page reload"],
    faqs: [
      { q: "How do I calculate a percentage increase?", a: "Subtract the old value from the new value, divide by the old value, then multiply by 100. Going from 80 to 100 is (100 − 80) / 80 × 100 = 25% increase." },
      { q: "Why is a 50% rise followed by a 50% fall not back to the start?", a: "Because each percentage applies to a different base. 100 rises to 150, then 50% of 150 is 75 — so you land at 75, not 100." },
    ],
    featured: true,
  },
  {
    id: "discount",
    name: "Discount Calculator",
    short: "See the sale price, the amount saved and the real discount.",
    long:
      "Enter an original price and a discount to see what you pay and what you save. It also works backwards: enter the original and sale prices to find the true percentage off, and stack a second discount or add tax.",
    category: "calculator",
    route: "/calculators/discount",
    keywords: ["discount calculator", "sale price calculator", "percent off calculator", "how much do i save", "double discount"],
    aliases: ["percent off", "sale price", "calculate discount"],
    icon: "🏷️",
    accent: "fire",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "numbers",
    related: ["percentage", "age", "bmi", "qr-generator"],
    seoTitle: "Free Discount Calculator — Sale Price & Percent Off | DO101",
    seoDescription:
      "Calculate a sale price, the amount saved, stacked discounts and the true percentage off. Free discount calculator with the maths shown.",
    steps: ["Enter the original price.", "Enter the discount percentage, or the price you were quoted.", "Read the final price and your saving."],
    features: ["Discount to final price", "Final price back to true percentage off", "Stack a second discount correctly", "Optional tax on top", "Formula shown"],
    faqs: [
      { q: "How do stacked discounts work?", a: "They multiply rather than add. 20% off then a further 10% off is 0.8 × 0.9 = 0.72, so 28% off in total — not 30%." },
      { q: "Is tax applied before or after the discount?", a: "In most places the discount comes first and tax is charged on the reduced price. DO101 follows that order and shows both lines." },
    ],
  },
  {
    id: "bmi",
    name: "BMI Calculator",
    short: "Body Mass Index in metric or imperial, with the range explained.",
    long:
      "Calculate Body Mass Index from height and weight in either metric or imperial units, and see where the result sits on the standard adult scale. BMI is a rough screening number, not a diagnosis — the page explains what it does and does not tell you.",
    category: "calculator",
    route: "/calculators/bmi",
    keywords: ["bmi calculator", "body mass index", "calculate bmi", "bmi chart", "healthy weight calculator"],
    aliases: ["body mass index", "am i overweight calculator"],
    icon: "⚖️",
    accent: "fire",
    browserOnly: true,
    aiInvocable: true,
    input: "numbers",
    output: "numbers",
    related: ["percentage", "age", "discount", "timestamp-converter"],
    seoTitle: "Free BMI Calculator — Metric & Imperial Body Mass Index | DO101",
    seoDescription:
      "Calculate Body Mass Index in metric or imperial units and see the standard adult categories explained, with a clear note on BMI's limits.",
    steps: ["Choose metric or imperial.", "Enter your height and weight.", "Read your BMI and the category scale beneath it."],
    features: ["Metric (cm / kg) and imperial (ft, in / lb)", "Category scale with your position marked", "Healthy weight range for your height", "Plain-English limitations section", "Calculated on your device"],
    faqs: [
      { q: "Is BMI accurate?", a: "BMI is a population-level screening tool. It does not distinguish muscle from fat, and it can misclassify athletes, older adults, pregnant people and children. Treat it as one rough signal, not a verdict on your health." },
      { q: "What is the formula?", a: "Metric: weight in kilograms divided by height in metres squared. Imperial: 703 × weight in pounds ÷ height in inches squared." },
      { q: "Does DO101 store my measurements?", a: "No. The calculation runs in the page and nothing is transmitted or saved." },
    ],
  },

  /* -------------------------------- GAMES -------------------------------- */
  {
    id: "typing-test",
    name: "Typing Speed Test",
    short: "Measure your WPM and accuracy in 15, 30 or 60 seconds.",
    long:
      "A clean, distraction-free typing test. Choose a duration, start typing, and watch your speed and accuracy update live. Your best score is saved on your device so you can chase it, and the result is easy to share.",
    category: "game",
    route: "/games/typing-test",
    keywords: ["typing test", "typing speed test", "wpm test", "words per minute", "how fast can i type", "typing practice"],
    aliases: ["wpm test", "test my typing speed", "speed typing"],
    icon: "⌨️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "keyboard",
    output: "numbers",
    related: ["typing-battle", "reaction-test", "memory-test", "word-counter"],
    seoTitle: "Free Typing Speed Test — Check Your WPM in 60 Seconds | DO101",
    seoDescription:
      "Test your typing speed and accuracy in 15, 30 or 60 seconds. Live WPM, accuracy and error counts, personal best saved locally, results easy to share.",
    steps: ["Pick 15, 30 or 60 seconds.", "Start typing the text — the timer starts on your first keystroke.", "Read your WPM, accuracy and errors, then share or retry."],
    features: [
      "15, 30 and 60 second modes",
      "Live WPM, CPM and accuracy",
      "Per-character correctness highlighting",
      "Personal best stored on your device",
      "Shareable result card",
    ],
    faqs: [
      { q: "How is WPM calculated?", a: "The standard formula: every five correct characters counts as one word, divided by the elapsed minutes. DO101 shows both net WPM (correct characters only) and raw CPM." },
      { q: "What is a good typing speed?", a: "Around 40 WPM is average for adults, 60–70 WPM is fast, and above 100 WPM is genuinely rare. Accuracy above 95% matters more than raw speed for real work." },
      { q: "Do I need an account?", a: "No. Your best score is saved in your own browser with localStorage and never sent to DO101." },
    ],
    featured: true,
  },
  {
    id: "typing-battle",
    name: "Typing Battle",
    short: "Race a friend on the same text, live, from a shared link.",
    long:
      "Create a room, send the link to a friend, and race through identical text with both progress bars moving in real time. The connection is peer-to-peer over WebRTC, so there is no server holding your keystrokes.",
    category: "game",
    route: "/games/typing-battle",
    keywords: ["typing battle", "typing race", "multiplayer typing test", "typing game with friends", "1v1 typing"],
    aliases: ["typing race", "type against friend", "typing 1v1"],
    icon: "⚔️",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "keyboard",
    output: "numbers",
    related: ["typing-test", "reaction-test", "memory-test", "word-counter"],
    seoTitle: "Typing Battle — Free 1v1 Multiplayer Typing Race | DO101",
    seoDescription:
      "Challenge a friend to a live typing race. Share a room link, race the same text, and watch both progress bars in real time. Free, no sign-up.",
    steps: ["Create a room and copy the link.", "Send it to a friend and wait for them to join.", "Race the same text and see who finishes first."],
    features: [
      "Real peer-to-peer connection over WebRTC",
      "Live opponent progress and WPM",
      "Synchronised countdown and identical text",
      "Rematch without creating a new room",
      "Honest connection states — never a fake opponent",
    ],
    faqs: [
      { q: "Is this real multiplayer?", a: "Yes. Both browsers connect directly to each other over WebRTC using a public signalling broker to exchange addresses. DO101 never simulates an opponent — if nobody joins, the screen says so." },
      { q: "Why did the connection fail?", a: "Strict corporate firewalls and some mobile networks block peer-to-peer traffic. DO101 shows a clear failure state with a retry, rather than pretending you are connected." },
      { q: "How long does a room last?", a: "A room exists only while the host's tab is open. Close it and the room is gone — there is no database keeping it alive." },
    ],
    featured: true,
  },
  {
    id: "reaction-test",
    name: "Reaction Time Test",
    short: "How fast are your reflexes? Measure it in milliseconds.",
    long:
      "Wait for green, then click as fast as you can. DO101 measures your reaction time with high-resolution browser timing across five rounds and gives you an average you can compare and share.",
    category: "game",
    route: "/games/reaction-test",
    keywords: ["reaction time test", "reflex test", "reaction speed", "click speed test", "average reaction time"],
    aliases: ["reflex test", "how fast are my reflexes", "reaction speed test"],
    icon: "⚡",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["typing-test", "memory-test", "typing-battle", "age"],
    seoTitle: "Reaction Time Test — Measure Your Reflexes in ms | DO101",
    seoDescription:
      "Test your reaction time in milliseconds across five rounds using high-resolution browser timing. Free, no sign-up, share your average.",
    steps: ["Press start and wait for the screen to turn green.", "Click, tap or hit space the instant it changes.", "Repeat five times for your average."],
    features: ["Five rounds with a running average", "High-resolution performance timing", "Too-soon detection", "Personal best saved locally", "Works with mouse, touch or keyboard"],
    faqs: [
      { q: "What is a good reaction time?", a: "Around 250 ms is typical for a visual click reaction. Under 200 ms is fast. Anything below about 100 ms usually means you anticipated the change rather than reacted to it." },
      { q: "Does my screen affect the result?", a: "Yes. Display latency and refresh rate add a few milliseconds, so compare your scores against your own history rather than against other setups." },
    ],
  },
  {
    id: "memory-test",
    name: "Memory Test",
    short: "Repeat a growing sequence. How many can you hold?",
    long:
      "A progressive sequence-memory game. Watch the pattern light up, repeat it, and each round adds one more step. Simple to learn, surprisingly hard to beat.",
    category: "game",
    route: "/games/memory-test",
    keywords: ["memory test", "sequence memory", "memory game", "brain training", "short term memory test"],
    aliases: ["sequence game", "memory game", "brain test"],
    icon: "🧠",
    accent: "cherry",
    browserOnly: true,
    aiInvocable: false,
    input: "none",
    output: "numbers",
    related: ["reaction-test", "typing-test", "typing-battle", "percentage"],
    seoTitle: "Memory Test — Free Sequence Memory Game | DO101",
    seoDescription:
      "Play a progressive sequence memory game in your browser. Each level adds one step — see how far you can get. Free, no sign-up, share your level.",
    steps: ["Press start and watch the sequence.", "Tap the tiles back in the same order.", "Each level adds one more step."],
    features: ["Progressive difficulty", "Keyboard and touch friendly", "Best level saved on your device", "Sound-free by design", "Shareable result"],
    faqs: [
      { q: "What is an average score?", a: "Most people manage between 7 and 9 steps, which matches the classic research on short-term memory span. Chunking the sequence helps you go further." },
      { q: "Is my score sent anywhere?", a: "No. Your best level lives in your browser's local storage only." },
    ],
  },
];

/* ----------------------------- lookups ----------------------------- */

export const TOOL_MAP: Record<string, Tool> = Object.fromEntries(
  TOOLS.map((t) => [t.id, t]),
);

export function getTool(id: string): Tool | undefined {
  return TOOL_MAP[id];
}

export function getToolByRoute(route: string): Tool | undefined {
  return TOOLS.find((t) => t.route === route);
}

export function toolsByCategory(category: Tool["category"]): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function relatedTools(id: string, limit = 4): Tool[] {
  const tool = getTool(id);
  if (!tool) return [];
  return tool.related
    .map((r) => TOOL_MAP[r])
    .filter((t): t is Tool => Boolean(t))
    .slice(0, limit);
}

export const FEATURED_TOOLS = TOOLS.filter((t) => t.featured);
