/**
 * The full-page translation dictionary.
 *
 * messages.ts holds the handful of strings the interface refers to by key.
 * This holds everything else — the tool descriptions, the "How to use it"
 * steps, the FAQs, the labels inside each tool — keyed by the English text
 * itself rather than by an invented key. Keying by the source means a hundred
 * components did not have to be rewritten to look their strings up, and a
 * string with no entry simply stays in English instead of rendering blank.
 *
 * The dictionaries are generated by scripts/i18n-harvest.mjs and
 * scripts/i18n-translate.mjs and checked in as JSON. They are loaded lazily,
 * one language at a time, so an English visitor downloads none of them.
 */
import { DEFAULT_LOCALE } from "./locales";

export type Dictionary = Record<string, string>;

/**
 * Whitespace is collapsed on both sides of the lookup. JSX indents its text,
 * so the same sentence reaches the DOM with different runs of spaces
 * depending on how the source happened to be formatted.
 */
export function normalizeKey(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

/**
 * One import per language, written out rather than built from a template.
 *
 * A dynamic `import(\`./dictionaries/${locale}.json\`)` asks the bundler to
 * resolve a directory it cannot see the contents of, and Turbopack refuses it.
 * Listing them also means each language is still its own chunk, fetched only
 * when somebody picks it. Every code in LOCALES needs a row here, and a file
 * on disk — an empty `{}` is fine for a language nothing has been translated
 * into yet. The i18n test enforces both.
 */
const DICTIONARIES: Record<string, () => Promise<{ default: Dictionary }>> = {
  ja: () => import("./dictionaries/ja.json"),
  es: () => import("./dictionaries/es.json"),
  fr: () => import("./dictionaries/fr.json"),
  de: () => import("./dictionaries/de.json"),
  pt: () => import("./dictionaries/pt.json"),
  hi: () => import("./dictionaries/hi.json"),
  ne: () => import("./dictionaries/ne.json"),
  zh: () => import("./dictionaries/zh.json"),
  ko: () => import("./dictionaries/ko.json"),
  id: () => import("./dictionaries/id.json"),
  ar: () => import("./dictionaries/ar.json"),
};

const loaded = new Map<string, Dictionary>();
const loading = new Map<string, Promise<Dictionary>>();

/**
 * Fetches a language's dictionary, once. English resolves to an empty
 * dictionary without a network request: it is the source language.
 */
export function loadDictionary(locale: string): Promise<Dictionary> {
  if (locale === DEFAULT_LOCALE) return Promise.resolve({});

  const cached = loaded.get(locale);
  if (cached) return Promise.resolve(cached);

  const inFlight = loading.get(locale);
  if (inFlight) return inFlight;

  const load = DICTIONARIES[locale];
  if (!load) {
    loaded.set(locale, {});
    return Promise.resolve({});
  }

  const promise = load()
    .then((module: { default: Dictionary }) => {
      const dict = module.default;
      loaded.set(locale, dict);
      return dict;
    })
    .catch(() => {
      // A language with no dictionary yet is not an error — the site stays in
      // English for it, which is what it did before any of this existed.
      loaded.set(locale, {});
      return {};
    })
    .finally(() => {
      loading.delete(locale);
    });

  loading.set(locale, promise);
  return promise;
}

/** The dictionary for a language if it has already been loaded, else null. */
export function peekDictionary(locale: string): Dictionary | null {
  if (locale === DEFAULT_LOCALE) return {};
  return loaded.get(locale) ?? null;
}

/**
 * Looks a string up, preserving the whitespace that surrounded it.
 *
 * A text node is often padded — `<span>{count} items</span>` puts " items" in
 * the DOM — and that padding has to survive, or words weld together.
 */
export function translateText(dict: Dictionary, raw: string): string | null {
  const key = normalizeKey(raw);
  if (!key) return null;

  const translated = dict[key];
  if (translated === undefined || translated === raw) return null;

  const leading = /^\s*/.exec(raw)![0];
  const trailing = /\s*$/.exec(raw)![0];
  return leading + translated + trailing;
}
