"use client";

import * as React from "react";
import { Card } from "@/components/ui/Card";
import { Textarea, Select, Label } from "@/components/ui/Field";
import { Button } from "@/components/ui/Button";
import { CopyButton } from "@/components/ui/CopyButton";
import { EmptyState, ErrorState, InfoNote } from "@/components/ui/Feedback";
import {
  NICHE_OPTIONS,
  SHORTS_SEO_LIMITS,
  generateShortsSeo,
  type NicheId,
  type ShortsSeoResult,
} from "@/lib/youtube/shorts-seo";
import { track } from "@/lib/analytics";
import { recordCompletion } from "@/lib/gamify";
import { cn } from "@/lib/utils/cn";

const PLACEHOLDER = `Video ka topic, title ya keywords paste karo. For example:

How to lose belly fat at home
SIP me 5000 rupees har mahine, 10 saal baad kitna
iPhone 17 ka hidden camera setting`;

/** A measured fact about one section: green when it meets the rule, amber when not. */
function Meter({ label, ok }: { label: string; ok: boolean }) {
  return (
    <span
      className={cn(
        "rounded-full border-2 px-2.5 py-1 text-[11px] font-extrabold tabular-nums",
        ok
          ? "border-[var(--grass)] bg-[var(--grass-soft)] text-[var(--grass-dark)] dark:text-[var(--grass)]"
          : "border-[var(--fire)] bg-[var(--fire-soft)] text-[var(--fire-dark)] dark:text-[var(--fire)]",
      )}
    >
      {ok ? "✓" : "!"} {label}
    </span>
  );
}

/** One result block: heading, its measurements, the text, and a Copy button. */
function Section({
  step,
  icon,
  title,
  hint,
  meters,
  value,
  children,
  mono = false,
}: {
  step: number;
  icon: string;
  title: string;
  hint?: string;
  meters?: React.ReactNode;
  value: string;
  children?: React.ReactNode;
  mono?: boolean;
}) {
  return (
    <Card className="p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <h3 className="flex items-center gap-2 text-base font-extrabold">
            <span
              aria-hidden
              className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[var(--panel-2)] text-xs font-black tabular-nums"
            >
              {step}
            </span>
            <span aria-hidden>{icon}</span>
            {title}
          </h3>
          {hint ? (
            <p className="mt-1 text-xs font-semibold text-[var(--muted)]">{hint}</p>
          ) : null}
        </div>
        <CopyButton value={value} label="Copy" tone="panel" size="sm" />
      </div>

      {meters ? <div className="mt-3 flex flex-wrap gap-2">{meters}</div> : null}

      <div
        className={cn(
          "do-scroll mt-3 max-h-[420px] overflow-auto whitespace-pre-wrap break-words rounded-2xl bg-[var(--panel)] p-4 text-sm font-semibold leading-relaxed",
          mono && "font-mono text-[13px]",
        )}
      >
        {children ?? value}
      </div>
    </Card>
  );
}

/**
 * The Shorts SEO tool. Everything is generated by the pure functions in
 * `lib/youtube/shorts-seo` — no request leaves the page, and the copy says so
 * rather than implying a model is involved.
 */
export function ShortsSeoGenerator() {
  const [input, setInput] = React.useState("");
  const [niche, setNiche] = React.useState<NicheId | "auto">("auto");
  const [result, setResult] = React.useState<ShortsSeoResult | null>(null);
  const [failed, setFailed] = React.useState(false);
  /** Ticked off by the visitor. Local component state only — nothing stored. */
  const [ticked, setTicked] = React.useState<Set<number>>(new Set());
  const resultsRef = React.useRef<HTMLDivElement>(null);
  const counted = React.useRef(false);

  const run = (variation: number) => {
    const next = generateShortsSeo(input, { niche, variation });
    if (!next) {
      setResult(null);
      setFailed(true);
      return;
    }
    setFailed(false);
    setTicked(new Set());
    setResult(next);
    if (!counted.current) {
      counted.current = true;
      track("tool_complete", { tool: "youtube-shorts-seo" });
      recordCompletion(5);
    }
  };

  const generate = () => {
    run(0);
    // Small screens: the form fills the viewport, so bring the results into view.
    requestAnimationFrame(() =>
      resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }),
    );
  };

  const clear = () => {
    setInput("");
    setResult(null);
    setFailed(false);
  };

  const toggle = (index: number) =>
    setTicked((prev) => {
      const next = new Set(prev);
      if (next.has(index)) next.delete(index);
      else next.add(index);
      return next;
    });

  const {
    titleMinChars,
    titleMaxChars,
    titleHashtags,
    descMinWords,
    descMaxWords,
    descHashtags,
    descKeywordMin,
    descKeywordMax,
    tagsMinChars,
    tagsMaxChars,
  } = SHORTS_SEO_LIMITS;

  return (
    <div className="space-y-4">
      <Card className="p-5">
        <Label htmlFor="ss-topic" hint={input.trim() ? `${input.trim().length} characters` : undefined}>
          Video topic, title or keywords
        </Label>
        <Textarea
          id="ss-topic"
          value={input}
          onChange={(event) => setInput(event.target.value)}
          placeholder={PLACEHOLDER}
          className="min-h-[140px]"
          onKeyDown={(event) => {
            if ((event.metaKey || event.ctrlKey) && event.key === "Enter") generate();
          }}
        />

        <div className="mt-4 grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end">
          <div>
            <Label htmlFor="ss-niche">Niche</Label>
            <Select
              id="ss-niche"
              value={niche}
              onChange={(event) => setNiche(event.target.value as NicheId | "auto")}
            >
              <option value="auto">Auto-detect from my topic</option>
              {NICHE_OPTIONS.map((option) => (
                <option key={option.id} value={option.id}>
                  {option.label}
                </option>
              ))}
            </Select>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button tone="cherry" size="md" onClick={generate} disabled={!input.trim()}>
              Generate SEO
            </Button>
            <Button tone="ghost" onClick={clear} disabled={!input && !result}>
              Clear
            </Button>
          </div>
        </div>
      </Card>

      {failed ? (
        <ErrorState message="Us text me koi word nahi mila jise keyword banaya ja sake. Topic ya title likh ke dobara try karo." />
      ) : null}

      <div ref={resultsRef}>
        {!result ? (
          <EmptyState
            icon="🎬"
            title="Topic likho, phir Generate SEO dabao"
            description="Title, description, tags, pinned comment, hook aur checklist — sab ek saath, aapke browser me hi."
          />
        ) : (
          <div className="space-y-4">
            <Card className="flex flex-wrap items-center justify-between gap-3 p-5">
              <div className="min-w-0">
                <p className="text-xs font-extrabold uppercase tracking-wider text-[var(--muted)]">
                  Main keyword
                </p>
                <p className="truncate text-lg font-extrabold">{result.keyword.main}</p>
                <p className="mt-0.5 text-xs font-semibold text-[var(--muted)]">
                  Niche: {result.nicheLabel}
                  {niche === "auto"
                    ? result.nicheDetected
                      ? " (topic se detect hua)"
                      : " (topic se pata nahi chala — niche khud choose kar sakte ho)"
                    : " (aapne choose kiya)"}
                  {" · "}
                  Variation {result.variation + 1}
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <Button tone="sky" size="sm" onClick={() => run(result.variation + 1)}>
                  New variation
                </Button>
                <CopyButton value={result.copyAll} label="Copy all" tone="grass" size="sm" />
              </div>
            </Card>

            <Section
              step={1}
              icon="🔥"
              title="Viral Hinglish SEO title"
              hint={`${titleMinChars}–${titleMaxChars} characters, 1–2 emoji, exactly ${titleHashtags} hashtags.`}
              meters={
                <>
                  <Meter label={`${result.title.chars} characters`} ok={result.title.inRange} />
                  <Meter
                    label={`${result.title.hashtags} hashtags`}
                    ok={result.title.hashtags === titleHashtags}
                  />
                  <Meter
                    label={`${result.title.emoji} emoji`}
                    ok={result.title.emoji >= 1 && result.title.emoji <= 2}
                  />
                </>
              }
              value={result.title.text}
            />

            <Section
              step={2}
              icon="📝"
              title="SEO description"
              hint={`${descMinWords}–${descMaxWords} words, keyword ${descKeywordMin}–${descKeywordMax} baar, CTA, exactly ${descHashtags} hashtags.`}
              meters={
                <>
                  <Meter
                    label={`${result.description.words} words`}
                    ok={
                      result.description.words >= descMinWords &&
                      result.description.words <= descMaxWords
                    }
                  />
                  <Meter
                    label={`keyword ${result.description.keywordCount}×`}
                    ok={
                      result.description.keywordCount >= descKeywordMin &&
                      result.description.keywordCount <= descKeywordMax
                    }
                  />
                  <Meter
                    label={`${result.description.hashtags} hashtags`}
                    ok={result.description.hashtags === descHashtags}
                  />
                </>
              }
              value={result.description.text}
            />

            <Section
              step={3}
              icon="🏷️"
              title="SEO tags"
              hint={`${tagsMinChars}–${tagsMaxChars} characters, comma separated — YouTube Studio me paste karo.`}
              meters={
                <>
                  <Meter label={`${result.tags.chars} characters`} ok={result.tags.inRange} />
                  <Meter label={`${result.tags.list.length} tags`} ok={result.tags.list.length >= 10} />
                </>
              }
              value={result.tags.text}
              mono
            />

            <Section
              step={4}
              icon="📌"
              title="Best pinned comment"
              hint="Upload ke 10 minute ke andar pin kar do — pehle comments hi thread banate hain."
              value={result.pinnedComment}
            />

            <Section
              step={5}
              icon="⚡"
              title="Viral hook — first 3 seconds"
              hint="Jo bolna hai, jo screen par likhna hai, aur pehla frame kaisa ho."
              value={result.hook.text}
            >
              <ul className="space-y-3">
                {[
                  { label: "Bolna (0–3 sec)", value: result.hook.spoken },
                  { label: "Screen par text", value: result.hook.onScreen },
                  { label: "Pehla frame", value: result.hook.firstFrame },
                ].map((row) => (
                  <li key={row.label}>
                    <p className="text-[11px] font-extrabold uppercase tracking-wider text-[var(--muted)]">
                      {row.label}
                    </p>
                    <p className="font-semibold">{row.value}</p>
                  </li>
                ))}
              </ul>
            </Section>

            <Card className="p-5">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="min-w-0">
                  <h3 className="flex items-center gap-2 text-base font-extrabold">
                    <span
                      aria-hidden
                      className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[var(--panel-2)] text-xs font-black tabular-nums"
                    >
                      6
                    </span>
                    <span aria-hidden>✅</span>
                    Short SEO checklist
                  </h3>
                  <p className="mt-1 text-xs font-semibold text-[var(--muted)]">
                    Pehle chhe rows DO101 ne aapke output se naap kar likhe hain. Baaki upload ke
                    waqt aapko karne hain.
                  </p>
                </div>
                <CopyButton
                  value={result.checklist
                    .map(
                      (item, index) =>
                        `${item.measured ? (item.ok ? "[x]" : "[!]") : ticked.has(index) ? "[x]" : "[ ]"} ${item.text}`,
                    )
                    .join("\n")}
                  label="Copy"
                  tone="panel"
                  size="sm"
                />
              </div>

              <ul className="mt-3 space-y-2">
                {result.checklist.map((item, index) => {
                  if (item.measured) {
                    return (
                      <li
                        key={item.text}
                        className={cn(
                          "flex items-start gap-2 rounded-2xl px-3 py-2 text-sm font-semibold",
                          item.ok ? "bg-[var(--grass-soft)]" : "bg-[var(--fire-soft)]",
                        )}
                      >
                        <span aria-hidden>{item.ok ? "✓" : "!"}</span>
                        <span>{item.text}</span>
                      </li>
                    );
                  }
                  const done = ticked.has(index);
                  return (
                    <li key={item.text}>
                      <button
                        type="button"
                        aria-pressed={done}
                        onClick={() => toggle(index)}
                        className={cn(
                          "flex w-full items-start gap-2 rounded-2xl border-2 px-3 py-2 text-left text-sm font-semibold transition-colors",
                          done
                            ? "border-[var(--grass)] bg-[var(--grass-soft)]"
                            : "border-[var(--border)] hover:bg-[var(--panel)]",
                        )}
                      >
                        <span aria-hidden>{done ? "☑" : "☐"}</span>
                        <span className={cn(done && "line-through decoration-2")}>{item.text}</span>
                      </button>
                    </li>
                  );
                })}
              </ul>
            </Card>

            <InfoNote icon="🧠">
              <strong>Koi AI model use nahi hota.</strong> Ye output aapke keyword aur niche se
              banaye gaye Hinglish templates, length rules aur local JavaScript logic se bana hai —
              isi liye same topic pe same result milta hai aur &ldquo;New variation&rdquo; ek dusra
              set deta hai. Keyword aapka hi rehta hai; baaki structure DO101 add karta hai.
            </InfoNote>
          </div>
        )}
      </div>
    </div>
  );
}
